(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



ConvertFiles:=Block[{SMEFTLaTeX,LEFTLaTeX,RGEsSMEFT,RGEsSM,RGEsLEFT,SMEFTU,LEFTU},

Print["Converting files: m to mx"];

(* LaTeX files *)

SMEFTLaTeX=Import[DsixTools`DsixToolsDir<>"SMEFTOpsLatex.m"];
Export[DsixTools`DsixToolsDir<>"SMEFTOpsLatex.mx",SMEFTLaTeX];

LEFTLaTeX=Import[DsixTools`DsixToolsDir<>"LEFTOpsLatex.m"];
Export[DsixTools`DsixToolsDir<>"LEFTOpsLatex.mx",LEFTLaTeX];

(* EW matching *)

Import[DsixTools`DsixToolsDir<>"EWMatching.m"];
DumpSave[DsixTools`DsixToolsDir<>"EWMatching.mx",DsixTools`MatchEW];

(* \[Beta] functions *)

Import[DsixTools`DsixToolsDir<>"BetaSMEFT.m"];
DumpSave[DsixTools`DsixToolsDir<>"BetaSMEFT.mx",DsixTools`\[Beta]];

Import[DsixTools`DsixToolsDir<>"BetaSM.m"];
DumpSave[DsixTools`DsixToolsDir<>"BetaSM.mx",DsixTools`\[Beta]SM];

Clear[DsixTools`\[Beta]];
Import[DsixTools`DsixToolsDir<>"BetaLEFT.m"];
DumpSave[DsixTools`DsixToolsDir<>"BetaLEFT.mx",DsixTools`\[Beta]];

(* RGEs *)

RGEsSMEFT=Import[DsixTools`DsixToolsDir<>"RGEsSMEFT.m"];
Export[DsixTools`DsixToolsDir<>"RGEsSMEFT.mx",RGEsSMEFT];

RGEsSM=Import[DsixTools`DsixToolsDir<>"RGEsSM.m"];
Export[DsixTools`DsixToolsDir<>"RGEsSM.mx",RGEsSM];

RGEsLEFT=Import[DsixTools`DsixToolsDir<>"RGEsLEFT.m"];
Export[DsixTools`DsixToolsDir<>"RGEsLEFT.mx",RGEsLEFT];

(* SMEFT evolution matrix *)

SMEFTU=Import[DsixTools`DsixToolsDir<>"evolutionSMEFT.m"];
Export[DsixTools`DsixToolsDir<>"evolutionSMEFT.mx",SMEFTU];

(* LEFT evolution matrix *)

LEFTU=Import[DsixTools`DsixToolsDir<>"evolutionLEFT.m"];
Export[DsixTools`DsixToolsDir<>"evolutionLEFT.mx",LEFTU];

Print["Conversion complete!"];

];


DsixTools`ImportFiles=False;


Needs["DsixTools`"]


ConvertFiles;
