(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
 (**********************************************************************************************************************************)
 (* Code: DsixTools                                                                                                                *)
 (*                                                                                                                                *)
 (* Authors: Alejandro Celis, Javier Fuentes-Martin, Pedro Ruiz-Femenia, Avelino Vicente and Javier Virto                          *)
 (*                                                                                                                                *)
 (* Contact:                                                                                                                       *)
 (* Alejandro.Celis@physik.uni-muenchen.de, fuentes@physik.uzh.ch, pedrod.ruiz@uam.es, avelino.vicente@ific.uv.es, jvirto@mit.edu  *)
 (*                                                                                                                                *)
 (* Copyright (C) 2017                                                                                                             *)
 (*                                                                                                                                *)
 (* Summary: DsixTools is a Mathematica package for the handling of the dimension six Standard Model Effective Field               *)
 (* Theory. Among other features, DsixTools allows the user to perform the full one-loop                                           *)
 (* Renormalization Group Equations (RGEs) evolution of the Wilson coefficients in the Warsaw basis.                               *)
 (*                                                                                                                                *)
 (*                                                                                                                                *)
 (* This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public              *)
 (* License as published by the Free Software Foundation, either version 3 of the License, or any later version.                   *)
 (*                                                                                                                                *)
 (* This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied             *)
 (* warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.         *)
 (*                                                                                                                                *)
 (* You should have received a copy of the GNU General Public License along with this program.                                     *)


BeginPackage["DsixTools`"]


DsixToolsVersion::usage="DsixTools version";


DsixToolsDir::usage="DsixTools installation directory";


RGEsMethod::usage="DsixTools option. Determines the method to solve the RGEs : 1 (NDSolve), 2 (leading log) or 3 (evolution matrix)";


UseRGEsSM::usage="DsixTools option. If UseRGEsSM = 1, the SM RGEs are used to compute SM parameters at the high-energy";


SMEFTLoopOrder::usage="DsixTools option. Determines the SMEFT RGEs loop order when RGEsMethod is 1 (NDSolve) or 2 (leading log). Min = 1 and Max = 5";


LEFTLoopOrder::usage="DsixTools option. Determines the LEFT RGEs loop order when RGEsMethod is 1 (NDSolve) or 2 (leading log). Min = 1 and Max = 5";


MatchingLoopOrder::usage="DsixTools option. Determines the SMEFT-LEFT matching loop order. Min = 0 and Max = 1";


InputBasis::usage="DsixTools option. Determines the flavor basis for the input provided by the user";


InputValues::usage="Dispatch containing the input";


NonHermitianErrorsTotal::usage="List of input errors due to non-Hermiticity";


AntisymmetryErrorsTotal::usage="List of input errors due to antisymmetry";


HIGHSCALE::usage="UV Scale in units of GeV";


EWSCALE::usage="EW Scale in units of GeV";


LOWSCALE::usage="IR Scale in units of GeV";


\[Mu]::usage="Energy scale in units of GeV";


t::usage="Decimal logarithm of the energy scale: t = \!\(\*SubscriptBox[\(Log\), \(10\)]\)(\[Mu]/GeV), with \[Mu] an energy scale in units of GeV";


tHIGH::usage="Decimal logarithm of the UV scale: tHIGH = \!\(\*SubscriptBox[\(Log\), \(10\)]\)(HIGHSCALE/GeV), with HIGHSCALE the UV scale in units of GeV";


tEW::usage="Decimal logarithm of the EW scale: tEW = \!\(\*SubscriptBox[\(Log\), \(10\)]\)(EWSCALE/GeV), with EWSCALE the EW scale in units of GeV";


tLOW::usage="Decimal logarithm of the IR scale: tLOW = \!\(\*SubscriptBox[\(Log\), \(10\)]\)(LOWSCALE/GeV), with LOWSCALE the IR scale in units of GeV";


t0::usage="Evolution matrix parameter, defined as t0 = \!\(\*SubscriptBox[\(Log\), \(10\)]\)(\[Mu]Initial/GeV) with \[Mu]Initial the initial energy scale in units of GeV";


tf::usage="Evolution matrix parameter, defined as tf = \!\(\*SubscriptBox[\(Log\), \(10\)]\)(\[Mu]Final/GeV) with \[Mu]Final the final energy scale in units of GeV";


SMEFTObjectList::usage="List containing information about the SMEFT parameters: {Flavor Matrix, Name of WC, Name of Operator, Symmetry Category, Dimensions of Flavor Matrix, Canonical Dimension of Operator, EFT, Class, Broken Symmetries, LaTeX Symbol for Operator, LaTeX Expression for Operator}";


LEFTObjectList::usage="List containing information about the LEFT parameters: {Flavor Matrix, Name of WC, Name of Operator, Symmetry Category, Dimensions of Flavor Matrix, Canonical Dimension of Operator, EFT, Class, Broken Symmetries, LaTeX Symbol for Operator, LaTeX Expression for Operator}";


SMEFTParametersTotal::usage="List of all SMEFT parameters";


SMEFTOperators::usage="List of independent SMEFT operators";


LEFTParametersTotal::usage="List of all LEFT parameters";


LEFTOperators::usage="List of independent LEFT operators";


SubRedundant::usage="Dispatch that replaces all redundant Wilson coefficients by their expressions in terms of the non-redundant ones";


\[Beta]::usage="\[Beta][X] returns the \[Beta] function for the parameter X";


\[Beta]SM::usage="\[Beta]SM[X] returns the pure SM \[Beta] function for the SM parameter X";


LoopParameter::usage="Variable to set the loop order used in the \[Beta] functions and matching conditions: nth-order contributions are proportional to \!\(\*SuperscriptBox[\(LoopParameter\), \(n\)]\), with n = 2, 3, 4 and 5";


Match::usage="Dispatch that replaces all LEFT parameters by their numerical values at the matching scale";


MatchAnalytical::usage="Dispatch that replaces all LEFT parameters by their analytical matching conditions";


Qg::usage="Qg SMEFT operator";


Qgp::usage="Qgp SMEFT operator";


Qgs::usage="Qgs SMEFT operator";


Q\[Lambda]::usage="Q\[Lambda] SMEFT operator";


Qm2::usage="Qm2 SMEFT operator";


Q\[Theta]::usage="Q\[Theta] SMEFT operator";


Q\[Theta]p::usage="Q\[Theta]p SMEFT operator";


Q\[Theta]s::usage="Q\[Theta]s SMEFT operator";


QG::usage="QG SMEFT operator";


QGtilde::usage="QGtilde SMEFT operator";


QW::usage="QW SMEFT operator";


QWtilde::usage="QWtilde SMEFT operator";


QH::usage="QH SMEFT operator";


QH\[EmptySquare]::usage="QH\[EmptySquare] SMEFT operator";


QHD::usage="QHD SMEFT operator";


QHG::usage="QHG SMEFT operator";


QHB::usage="QHB SMEFT operator";


QHW::usage="QHW SMEFT operator";


QHWB::usage="QHWB SMEFT operator";


QHGtilde::usage="QHGtilde SMEFT operator";


QHBtilde::usage="QHBtilde SMEFT operator";


QHWtilde::usage="QHWtilde SMEFT operator";


QHWtildeB::usage="QHWtildeB SMEFT operator";


QGu::usage="QGu SMEFT operator";


QGd::usage="QGd SMEFT operator";


QGe::usage="QGe SMEFT operator";


QuH::usage="QuH SMEFT operator";


QdH::usage="QdH SMEFT operator";


QeH::usage="QeH SMEFT operator";


QeW::usage="QeW SMEFT operator";


QeB::usage="QeB SMEFT operator";


QuG::usage="QuG SMEFT operator";


QuW::usage="QuW SMEFT operator";


QuB::usage="QuB SMEFT operator";


QdG::usage="QdG SMEFT operator";


QdW::usage="QdW SMEFT operator";


QdB::usage="QdB SMEFT operator";


QHl1::usage="QHl1 SMEFT operator";


QHl3::usage="QHl3 SMEFT operator";


QHe::usage="QHe SMEFT operator";


QHq1::usage="QHq1 SMEFT operator";


QHq3::usage="QHq3 SMEFT operator";


QHu::usage="QHu SMEFT operator";


QHd::usage="QHd SMEFT operator";


QHud::usage="QHud SMEFT operator";


QllHH::usage="QllHH SMEFT operator";


Qll::usage="Qll SMEFT operator";


Qqq1::usage="Qqq1 SMEFT operator";


Qqq3::usage="Qqq3 SMEFT operator";


Qlq1::usage="Qlq1 SMEFT operator";


Qlq3::usage="Qlq3 SMEFT operator";


Qee::usage="Qee SMEFT operator";


Quu::usage="Quu SMEFT operator";


Qdd::usage="Qdd SMEFT operator";


Qeu::usage="Qeu SMEFT operator";


Qed::usage="Qed SMEFT operator";


Qud1::usage="Qud1 SMEFT operator";


Qud8::usage="Qud8 SMEFT operator";


Qle::usage="Qle SMEFT operator";


Qlu::usage="Qlu SMEFT operator";


Qld::usage="Qld SMEFT operator";


Qqe::usage="Qqe SMEFT operator";


Qqu1::usage="Qqu1 SMEFT operator";


Qqu8::usage="Qqu8 SMEFT operator";


Qqd1::usage="Qqd1 SMEFT operator";


Qqd8::usage="Qqd8 SMEFT operator";


Qledq::usage="Qledq SMEFT operator";


Qquqd1::usage="Qquqd1 SMEFT operator";


Qquqd8::usage="Qquqd8 SMEFT operator";


Qlequ1::usage="Qlequ1 SMEFT operator";


Qlequ3::usage="Qlequ3 SMEFT operator";


Qduql::usage="Qduql SMEFT operator";


Qqque::usage="Qqque SMEFT operator";


Qqqql::usage="Qqqql SMEFT operator";


Qduue::usage="Qduue SMEFT operator";


OgQCD::usage="OgQCD LEFT operator";


OeQED::usage="OeQED LEFT operator";


O\[Theta]QCD::usage="O\[Theta]QCD LEFT operator";


O\[Theta]QED::usage="O\[Theta]QED LEFT operator";


OG::usage="OG LEFT operator";


OGtilde::usage="OGtilde LEFT operator";


OM\[Nu]::usage="OM\[Nu] LEFT operator";


OMe::usage="OMe LEFT operator";


OMu::usage="OMu LEFT operator";


OMd::usage="OMd LEFT operator";


O\[Nu]\[Gamma]::usage="O\[Nu]\[Gamma] LEFT operator";


Oe\[Gamma]::usage="Oe\[Gamma] LEFT operator";


Ou\[Gamma]::usage="Ou\[Gamma] LEFT operator";


Od\[Gamma]::usage="Od\[Gamma] LEFT operator";


OuG::usage="OuG LEFT operator";


OdG::usage="OdG LEFT operator";


O\[Nu]\[Nu]VLL::usage="O\[Nu]\[Nu]VLL LEFT operator";


OeeVLL::usage="OeeVLL LEFT operator";


O\[Nu]eVLL::usage="O\[Nu]eVLL LEFT operator";


O\[Nu]uVLL::usage="O\[Nu]uVLL LEFT operator";


O\[Nu]dVLL::usage="O\[Nu]dVLL LEFT operator";


OeuVLL::usage="OeuVLL LEFT operator";


OedVLL::usage="OedVLL LEFT operator";


O\[Nu]eduVLL::usage="O\[Nu]eduVLL LEFT operator";


OuuVLL::usage="OuuVLL LEFT operator";


OddVLL::usage="OddVLL LEFT operator";


OudV1LL::usage="OudV1LL LEFT operator";


OudV8LL::usage="OudV8LL LEFT operator";


OeeVRR::usage="OeeVRR LEFT operator";


OeuVRR::usage="OeuVRR LEFT operator";


OedVRR::usage="OedVRR LEFT operator";


OuuVRR::usage="OuuVRR LEFT operator";


OddVRR::usage="OddVRR LEFT operator";


OudV1RR::usage="OudV1RR LEFT operator";


OudV8RR::usage="OudV8RR LEFT operator";


O\[Nu]eVLR::usage="O\[Nu]eVLR LEFT operator";


OeeVLR::usage="OeeVLR LEFT operator";


O\[Nu]uVLR::usage="O\[Nu]uVLR LEFT operator";


O\[Nu]dVLR::usage="O\[Nu]dVLR LEFT operator";


OeuVLR::usage="OeuVLR LEFT operator";


OedVLR::usage="OedVLR LEFT operator";


OueVLR::usage="OueVLR LEFT operator";


OdeVLR::usage="OdeVLR LEFT operator";


O\[Nu]eduVLR::usage="O\[Nu]eduVLR LEFT operator";


OuuV1LR::usage="OuuV1LR LEFT operator";


OuuV8LR::usage="OuuV8LR LEFT operator";


OudV1LR::usage="OudV1LR LEFT operator";


OudV8LR::usage="OudV8LR LEFT operator";


OduV1LR::usage="OduV1LR LEFT operator";


OduV8LR::usage="OduV8LR LEFT operator";


OddV1LR::usage="OddV1LR LEFT operator";


OddV8LR::usage="OddV8LR LEFT operator";


OudduV1LR::usage="OudduV1LR LEFT operator";


OudduV8LR::usage="OudduV8LR LEFT operator";


OeeSRR::usage="OeeSRR LEFT operator";


OeuSRR::usage="OeuSRR LEFT operator";


OeuTRR::usage="OeuTRR LEFT operator";


OedSRR::usage="OedSRR LEFT operator";


OedTRR::usage="OedTRR LEFT operator";


O\[Nu]eduSRR::usage="O\[Nu]eduSRR LEFT operator";


O\[Nu]eduTRR::usage="O\[Nu]eduTRR LEFT operator";


OuuS1RR::usage="OuuS1RR LEFT operator";


OuuS8RR::usage="OuuS8RR LEFT operator";


OudS1RR::usage="OudS1RR LEFT operator";


OudS8RR::usage="OudS8RR LEFT operator";


OddS1RR::usage="OddS1RR LEFT operator";


OddS8RR::usage="OddS8RR LEFT operator";


OudduS1RR::usage="OudduS1RR LEFT operator";


OudduS8RR::usage="OudduS8RR LEFT operator";


OeuSRL::usage="OeuSRL LEFT operator";


OedSRL::usage="OedSRL LEFT operator";


O\[Nu]eduSRL::usage="O\[Nu]eduSRL LEFT operator";


O\[Nu]\[Nu]SLL::usage="O\[Nu]\[Nu]SLL LEFT operator";


O\[Nu]eSLL::usage="O\[Nu]eSLL LEFT operator";


O\[Nu]eTLL::usage="O\[Nu]eTLL LEFT operator";


O\[Nu]eSLR::usage="O\[Nu]eSLR LEFT operator";


O\[Nu]uSLL::usage="O\[Nu]uSLL LEFT operator";


O\[Nu]uTLL::usage="O\[Nu]uTLL LEFT operator";


O\[Nu]uSLR::usage="O\[Nu]uSLR LEFT operator";


O\[Nu]dSLL::usage="O\[Nu]dSLL LEFT operator";


O\[Nu]dTLL::usage="O\[Nu]dTLL LEFT operator";


O\[Nu]dSLR::usage="O\[Nu]dSLR LEFT operator";


O\[Nu]eduSLL::usage="O\[Nu]eduSLL LEFT operator";


O\[Nu]eduTLL::usage="O\[Nu]eduTLL LEFT operator";


O\[Nu]eduSLR::usage="O\[Nu]eduSLR LEFT operator";


O\[Nu]eduVRL::usage="O\[Nu]eduVRL LEFT operator";


O\[Nu]eduVRR::usage="O\[Nu]eduVRR LEFT operator";


OuddSLL::usage="OuddSLL LEFT operator";


OduuSLL::usage="OduuSLL LEFT operator";


OuudSLR::usage="OuudSLR LEFT operator";


OduuSLR::usage="OduuSLR LEFT operator";


OuudSRL::usage="OuudSRL LEFT operator";


OduuSRL::usage="OduuSRL LEFT operator";


OdudSRL::usage="OdudSRL LEFT operator";


OdduSRL::usage="OdduSRL LEFT operator";


OduuSRR::usage="OduuSRR LEFT operator";


OdddSLL::usage="OdddSLL LEFT operator";


OuddSLR::usage="OuddSLR LEFT operator";


OdduSLR::usage="OdduSLR LEFT operator";


OdddSLR::usage="OdddSLR LEFT operator";


OdddSRL::usage="OdddSRL LEFT operator";


OuddSRR::usage="OuddSRR LEFT operator";


OdddSRR::usage="OdddSRR LEFT operator";


g::usage="g SMEFT parameter";


gp::usage="gp SMEFT parameter";


gs::usage="gs SMEFT parameter";


\[Lambda]::usage="\[Lambda] SMEFT parameter";


m2::usage="m2 SMEFT parameter";


Gu::usage="Gu SMEFT parameter";


Gd::usage="Gd SMEFT parameter";


Ge::usage="Ge SMEFT parameter";


\[Theta]::usage="\[Theta] SMEFT parameter";


\[Theta]p::usage="\[Theta]p SMEFT parameter";


\[Theta]s::usage="\[Theta]s SMEFT parameter";


MGu::usage="Gu SMEFT parameter in array form";


MGd::usage="Gd SMEFT parameter in array form";


MGe::usage="Ge SMEFT parameter in array form";


CG::usage="CG SMEFT Wilson coefficient";


CGtilde::usage="CGtilde SMEFT Wilson coefficient";


CW::usage="CW SMEFT Wilson coefficient";


CWtilde::usage="CWtilde SMEFT Wilson coefficient";


CH::usage="CH SMEFT Wilson coefficient";


CHbox::usage="CHbox SMEFT Wilson coefficient";


CHD::usage="CHD SMEFT Wilson coefficient";


CHG::usage="CHG SMEFT Wilson coefficient";


CHB::usage="CHB SMEFT Wilson coefficient";


CHW::usage="CHW SMEFT Wilson coefficient";


CHWB::usage="CHWB SMEFT Wilson coefficient";


CHGtilde::usage="CHGtilde SMEFT Wilson coefficient";


CHBtilde::usage="CHBtilde SMEFT Wilson coefficient";


CHWtilde::usage="CHWtilde SMEFT Wilson coefficient";


CHWtildeB::usage="CHWtildeB SMEFT Wilson coefficient";


CuH::usage="CuH SMEFT Wilson coefficient";


CdH::usage="CdH SMEFT Wilson coefficient";


CeH::usage="CeH SMEFT Wilson coefficient";


CeW::usage="CeW SMEFT Wilson coefficient";


CeB::usage="CeB SMEFT Wilson coefficient";


CuG::usage="CuG SMEFT Wilson coefficient";


CuW::usage="CuW SMEFT Wilson coefficient";


CuB::usage="CuB SMEFT Wilson coefficient";


CdG::usage="CdG SMEFT Wilson coefficient";


CdW::usage="CdW SMEFT Wilson coefficient";


CdB::usage="CdB SMEFT Wilson coefficient";


CHl1::usage="CHl1 SMEFT Wilson coefficient";


CHl3::usage="CHl3 SMEFT Wilson coefficient";


CHe::usage="CHe SMEFT Wilson coefficient";


CHq1::usage="CHq1 SMEFT Wilson coefficient";


CHq3::usage="CHq3 SMEFT Wilson coefficient";


CHu::usage="CHu SMEFT Wilson coefficient";


CHd::usage="CHd SMEFT Wilson coefficient";


CHud::usage="CHud SMEFT Wilson coefficient";


Cll::usage="Cll SMEFT Wilson coefficient";


Cqq1::usage="Cqq1 SMEFT Wilson coefficient";


Cqq3::usage="Cqq3 SMEFT Wilson coefficient";


Clq1::usage="Clq1 SMEFT Wilson coefficient";


Clq3::usage="Clq3 SMEFT Wilson coefficient";


Cee::usage="Cee SMEFT Wilson coefficient";


Cuu::usage="Cuu SMEFT Wilson coefficient";


Cdd::usage="Cdd SMEFT Wilson coefficient";


Ceu::usage="Ceu SMEFT Wilson coefficient";


Ced::usage="Ced SMEFT Wilson coefficient";


Cud1::usage="Cud1 SMEFT Wilson coefficient";


Cud8::usage="Cud8 SMEFT Wilson coefficient";


Cle::usage="Cle SMEFT Wilson coefficient";


Clu::usage="Clu SMEFT Wilson coefficient";


Cld::usage="Cld SMEFT Wilson coefficient";


Cqe::usage="Cqe SMEFT Wilson coefficient";


Cqu1::usage="Cqu1 SMEFT Wilson coefficient";


Cqu8::usage="Cqu8 SMEFT Wilson coefficient";


Cqd1::usage="Cqd1 SMEFT Wilson coefficient";


Cqd8::usage="Cqd8 SMEFT Wilson coefficient";


Cledq::usage="Cledq SMEFT Wilson coefficient";


Cquqd1::usage="Cquqd1 SMEFT Wilson coefficient";


Cquqd8::usage="Cquqd8 SMEFT Wilson coefficient";


Clequ1::usage="Clequ1 SMEFT Wilson coefficient";


Clequ3::usage="Clequ3 SMEFT Wilson coefficient";


Cduql::usage="Cduql SMEFT Wilson coefficient";


Cqque::usage="Cqque SMEFT Wilson coefficient";


Cqqql::usage="Cqqql SMEFT Wilson coefficient";


Cduue::usage="Cduue SMEFT Wilson coefficient";


CllHH::usage="CllHH SMEFT Wilson coefficient";


MCuH::usage="CuH SMEFT Wilson coefficient in array form";


MCdH::usage="CdH SMEFT Wilson coefficient in array form";


MCeH::usage="CeH SMEFT Wilson coefficient in array form";


MCeW::usage="CeW SMEFT Wilson coefficient in array form";


MCeB::usage="CeB SMEFT Wilson coefficient in array form";


MCuG::usage="CuG SMEFT Wilson coefficient in array form";


MCuW::usage="CuW SMEFT Wilson coefficient in array form";


MCuB::usage="CuB SMEFT Wilson coefficient in array form";


MCdG::usage="CdG SMEFT Wilson coefficient in array form";


MCdW::usage="CdW SMEFT Wilson coefficient in array form";


MCdB::usage="CdB SMEFT Wilson coefficient in array form";


MCHl1::usage="CHl1 SMEFT Wilson coefficient in array form";


MCHl3::usage="CHl3 SMEFT Wilson coefficient in array form";


MCHe::usage="CHe SMEFT Wilson coefficient in array form";


MCHq1::usage="CHq1 SMEFT Wilson coefficient in array form";


MCHq3::usage="CHq3 SMEFT Wilson coefficient in array form";


MCHu::usage="CHu SMEFT Wilson coefficient in array form";


MCHd::usage="CHd SMEFT Wilson coefficient in array form";


MCHud::usage="CHud SMEFT Wilson coefficient in array form";


MCll::usage="Cll SMEFT Wilson coefficient in array form";


MCqq1::usage="Cqq1 SMEFT Wilson coefficient in array form";


MCqq3::usage="Cqq3 SMEFT Wilson coefficient in array form";


MClq1::usage="Clq1 SMEFT Wilson coefficient in array form";


MClq3::usage="Clq3 SMEFT Wilson coefficient in array form";


MCee::usage="Cee SMEFT Wilson coefficient in array form";


MCuu::usage="Cuu SMEFT Wilson coefficient in array form";


MCdd::usage="Cdd SMEFT Wilson coefficient in array form";


MCeu::usage="Ceu SMEFT Wilson coefficient in array form";


MCed::usage="Ced SMEFT Wilson coefficient in array form";


MCud1::usage="Cud1 SMEFT Wilson coefficient in array form";


MCud8::usage="Cud8 SMEFT Wilson coefficient in array form";


MCle::usage="Cle SMEFT Wilson coefficient in array form";


MClu::usage="Clu SMEFT Wilson coefficient in array form";


MCld::usage="Cld SMEFT Wilson coefficient in array form";


MCqe::usage="Cqe SMEFT Wilson coefficient in array form";


MCqu1::usage="Cqu1 SMEFT Wilson coefficient in array form";


MCqu8::usage="Cqu8 SMEFT Wilson coefficient in array form";


MCqd1::usage="Cqd1 SMEFT Wilson coefficient in array form";


MCqd8::usage="Cqd8 SMEFT Wilson coefficient in array form";


MCledq::usage="Cledq SMEFT Wilson coefficient in array form";


MCquqd1::usage="Cquqd1 SMEFT Wilson coefficient in array form";


MCquqd8::usage="Cquqd8 SMEFT Wilson coefficient in array form";


MClequ1::usage="Clequ1 SMEFT Wilson coefficient in array form";


MClequ3::usage="Clequ3 SMEFT Wilson coefficient in array form";


MCduql::usage="Cduql SMEFT Wilson coefficient in array form";


MCqque::usage="Cqque SMEFT Wilson coefficient in array form";


MCqqql::usage="Cqqql SMEFT Wilson coefficient in array form";


MCduue::usage="Cduue SMEFT Wilson coefficient in array form";


MCllHH::usage="CllHH SMEFT Wilson coefficient in array form";


gQCD::usage="gQCD LEFT parameter";


eQED::usage="eQED LEFT parameter";


\[Theta]QCD::usage="\[Theta]QCD LEFT parameter";


\[Theta]QED::usage="\[Theta]QED LEFT parameter";


M\[Nu]::usage="M\[Nu] LEFT parameter";


Me::usage="Me LEFT parameter";


Mu::usage="Mu LEFT parameter";


Md::usage="Md LEFT parameter";


MM\[Nu]::usage="M\[Nu] LEFT parameter in array form";


MMe::usage="Me LEFT parameter in array form";


MMu::usage="Mu LEFT parameter in array form";


MMd::usage="Md LEFT parameter in array form";


LG::usage="LG LEFT Wilson coefficient";


LGtilde::usage="LGtilde LEFT Wilson coefficient";


L\[Nu]\[Gamma]::usage="L\[Nu]\[Gamma] LEFT Wilson coefficient";


Le\[Gamma]::usage="Le\[Gamma] LEFT Wilson coefficient";


Lu\[Gamma]::usage="Lu\[Gamma] LEFT Wilson coefficient";


Ld\[Gamma]::usage="Ld\[Gamma] LEFT Wilson coefficient";


LuG::usage="LuG LEFT Wilson coefficient";


LdG::usage="LdG LEFT Wilson coefficient";


L\[Nu]\[Nu]VLL::usage="L\[Nu]\[Nu]VLL LEFT Wilson coefficient";


LeeVLL::usage="LeeVLL LEFT Wilson coefficient";


L\[Nu]eVLL::usage="L\[Nu]eVLL LEFT Wilson coefficient";


L\[Nu]uVLL::usage="L\[Nu]uVLL LEFT Wilson coefficient";


L\[Nu]dVLL::usage="L\[Nu]dVLL LEFT Wilson coefficient";


LeuVLL::usage="LeuVLL LEFT Wilson coefficient";


LedVLL::usage="LedVLL LEFT Wilson coefficient";


L\[Nu]eduVLL::usage="L\[Nu]eduVLL LEFT Wilson coefficient";


LuuVLL::usage="LuuVLL LEFT Wilson coefficient";


LddVLL::usage="LddVLL LEFT Wilson coefficient";


LudV1LL::usage="LudV1LL LEFT Wilson coefficient";


LudV8LL::usage="LudV8LL LEFT Wilson coefficient";


LeeVRR::usage="LeeVRR LEFT Wilson coefficient";


LeuVRR::usage="LeuVRR LEFT Wilson coefficient";


LedVRR::usage="LedVRR LEFT Wilson coefficient";


LuuVRR::usage="LuuVRR LEFT Wilson coefficient";


LddVRR::usage="LddVRR LEFT Wilson coefficient";


LudV1RR::usage="LudV1RR LEFT Wilson coefficient";


LudV8RR::usage="LudV8RR LEFT Wilson coefficient";


L\[Nu]eVLR::usage="L\[Nu]eVLR LEFT Wilson coefficient";


LeeVLR::usage="LeeVLR LEFT Wilson coefficient";


L\[Nu]uVLR::usage="L\[Nu]uVLR LEFT Wilson coefficient";


L\[Nu]dVLR::usage="L\[Nu]dVLR LEFT Wilson coefficient";


LeuVLR::usage="LeuVLR LEFT Wilson coefficient";


LedVLR::usage="LedVLR LEFT Wilson coefficient";


LueVLR::usage="LueVLR LEFT Wilson coefficient";


LdeVLR::usage="LdeVLR LEFT Wilson coefficient";


L\[Nu]eduVLR::usage="L\[Nu]eduVLR LEFT Wilson coefficient";


LuuV1LR::usage="LuuV1LR LEFT Wilson coefficient";


LuuV8LR::usage="LuuV8LR LEFT Wilson coefficient";


LudV1LR::usage="LudV1LR LEFT Wilson coefficient";


LudV8LR::usage="LudV8LR LEFT Wilson coefficient";


LduV1LR::usage="LduV1LR LEFT Wilson coefficient";


LduV8LR::usage="LduV8LR LEFT Wilson coefficient";


LddV1LR::usage="LddV1LR LEFT Wilson coefficient";


LddV8LR::usage="LddV8LR LEFT Wilson coefficient";


LudduV1LR::usage="LudduV1LR LEFT Wilson coefficient";


LudduV8LR::usage="LudduV8LR LEFT Wilson coefficient";


LeeSRR::usage="LeeSRR LEFT Wilson coefficient";


LeuSRR::usage="LeuSRR LEFT Wilson coefficient";


LeuTRR::usage="LeuTRR LEFT Wilson coefficient";


LedSRR::usage="LedSRR LEFT Wilson coefficient";


LedTRR::usage="LedTRR LEFT Wilson coefficient";


L\[Nu]eduSRR::usage="L\[Nu]eduSRR LEFT Wilson coefficient";


L\[Nu]eduTRR::usage="L\[Nu]eduTRR LEFT Wilson coefficient";


LuuS1RR::usage="LuuS1RR LEFT Wilson coefficient";


LuuS8RR::usage="LuuS8RR LEFT Wilson coefficient";


LudS1RR::usage="LudS1RR LEFT Wilson coefficient";


LudS8RR::usage="LudS8RR LEFT Wilson coefficient";


LddS1RR::usage="LddS1RR LEFT Wilson coefficient";


LddS8RR::usage="LddS8RR LEFT Wilson coefficient";


LudduS1RR::usage="LudduS1RR LEFT Wilson coefficient";


LudduS8RR::usage="LudduS8RR LEFT Wilson coefficient";


LeuSRL::usage="LeuSRL LEFT Wilson coefficient";


LedSRL::usage="LedSRL LEFT Wilson coefficient";


L\[Nu]eduSRL::usage="L\[Nu]eduSRL LEFT Wilson coefficient";


L\[Nu]\[Nu]SLL::usage="L\[Nu]\[Nu]SLL LEFT Wilson coefficient";


L\[Nu]eSLL::usage="L\[Nu]eSLL LEFT Wilson coefficient";


L\[Nu]eTLL::usage="L\[Nu]eTLL LEFT Wilson coefficient";


L\[Nu]eSLR::usage="L\[Nu]eSLR LEFT Wilson coefficient";


L\[Nu]uSLL::usage="L\[Nu]uSLL LEFT Wilson coefficient";


L\[Nu]uTLL::usage="L\[Nu]uTLL LEFT Wilson coefficient";


L\[Nu]uSLR::usage="L\[Nu]uSLR LEFT Wilson coefficient";


L\[Nu]dSLL::usage="L\[Nu]dSLL LEFT Wilson coefficient";


L\[Nu]dTLL::usage="L\[Nu]dTLL LEFT Wilson coefficient";


L\[Nu]dSLR::usage="L\[Nu]dSLR LEFT Wilson coefficient";


L\[Nu]eduSLL::usage="L\[Nu]eduSLL LEFT Wilson coefficient";


L\[Nu]eduTLL::usage="L\[Nu]eduTLL LEFT Wilson coefficient";


L\[Nu]eduSLR::usage="L\[Nu]eduSLR LEFT Wilson coefficient";


L\[Nu]eduVRL::usage="L\[Nu]eduVRL LEFT Wilson coefficient";


L\[Nu]eduVRR::usage="L\[Nu]eduVRR LEFT Wilson coefficient";


LuddSLL::usage="LuddSLL LEFT Wilson coefficient";


LduuSLL::usage="LduuSLL LEFT Wilson coefficient";


LuudSLR::usage="LuudSLR LEFT Wilson coefficient";


LduuSLR::usage="LduuSLR LEFT Wilson coefficient";


LuudSRL::usage="LuudSRL LEFT Wilson coefficient";


LduuSRL::usage="LduuSRL LEFT Wilson coefficient";


LdudSRL::usage="LdudSRL LEFT Wilson coefficient";


LdduSRL::usage="LdduSRL LEFT Wilson coefficient";


LduuSRR::usage="LduuSRR LEFT Wilson coefficient";


LdddSLL::usage="LdddSLL LEFT Wilson coefficient";


LuddSLR::usage="LuddSLR LEFT Wilson coefficient";


LdduSLR::usage="LdduSLR LEFT Wilson coefficient";


LdddSLR::usage="LdddSLR LEFT Wilson coefficient";


LdddSRL::usage="LdddSRL LEFT Wilson coefficient";


LuddSRR::usage="LuddSRR LEFT Wilson coefficient";


LdddSRR::usage="LdddSRR LEFT Wilson coefficient";


ML\[Nu]\[Gamma]::usage="L\[Nu]\[Gamma] LEFT Wilson coefficient in array form";


MLe\[Gamma]::usage="Le\[Gamma] LEFT Wilson coefficient in array form";


MLu\[Gamma]::usage="Lu\[Gamma] LEFT Wilson coefficient in array form";


MLd\[Gamma]::usage="Ld\[Gamma] LEFT Wilson coefficient in array form";


MLuG::usage="LuG LEFT Wilson coefficient in array form";


MLdG::usage="LdG LEFT Wilson coefficient in array form";


ML\[Nu]\[Nu]VLL::usage="L\[Nu]\[Nu]VLL LEFT Wilson coefficient in array form";


MLeeVLL::usage="LeeVLL LEFT Wilson coefficient in array form";


ML\[Nu]eVLL::usage="L\[Nu]eVLL LEFT Wilson coefficient in array form";


ML\[Nu]uVLL::usage="L\[Nu]uVLL LEFT Wilson coefficient in array form";


ML\[Nu]dVLL::usage="L\[Nu]dVLL LEFT Wilson coefficient in array form";


MLeuVLL::usage="LeuVLL LEFT Wilson coefficient in array form";


MLedVLL::usage="LedVLL LEFT Wilson coefficient in array form";


ML\[Nu]eduVLL::usage="L\[Nu]eduVLL LEFT Wilson coefficient in array form";


MLuuVLL::usage="LuuVLL LEFT Wilson coefficient in array form";


MLddVLL::usage="LddVLL LEFT Wilson coefficient in array form";


MLudV1LL::usage="LudV1LL LEFT Wilson coefficient in array form";


MLudV8LL::usage="LudV8LL LEFT Wilson coefficient in array form";


MLeeVRR::usage="LeeVRR LEFT Wilson coefficient in array form";


MLeuVRR::usage="LeuVRR LEFT Wilson coefficient in array form";


MLedVRR::usage="LedVRR LEFT Wilson coefficient in array form";


MLuuVRR::usage="LuuVRR LEFT Wilson coefficient in array form";


MLddVRR::usage="LddVRR LEFT Wilson coefficient in array form";


MLudV1RR::usage="LudV1RR LEFT Wilson coefficient in array form";


MLudV8RR::usage="LudV8RR LEFT Wilson coefficient in array form";


ML\[Nu]eVLR::usage="L\[Nu]eVLR LEFT Wilson coefficient in array form";


MLeeVLR::usage="LeeVLR LEFT Wilson coefficient in array form";


ML\[Nu]uVLR::usage="L\[Nu]uVLR LEFT Wilson coefficient in array form";


ML\[Nu]dVLR::usage="L\[Nu]dVLR LEFT Wilson coefficient in array form";


MLeuVLR::usage="LeuVLR LEFT Wilson coefficient in array form";


MLedVLR::usage="LedVLR LEFT Wilson coefficient in array form";


MLueVLR::usage="LueVLR LEFT Wilson coefficient in array form";


MLdeVLR::usage="LdeVLR LEFT Wilson coefficient in array form";


ML\[Nu]eduVLR::usage="L\[Nu]eduVLR LEFT Wilson coefficient in array form";


MLuuV1LR::usage="LuuV1LR LEFT Wilson coefficient in array form";


MLuuV8LR::usage="LuuV8LR LEFT Wilson coefficient in array form";


MLudV1LR::usage="LudV1LR LEFT Wilson coefficient in array form";


MLudV8LR::usage="LudV8LR LEFT Wilson coefficient in array form";


MLduV1LR::usage="LduV1LR LEFT Wilson coefficient in array form";


MLduV8LR::usage="LduV8LR LEFT Wilson coefficient in array form";


MLddV1LR::usage="LddV1LR LEFT Wilson coefficient in array form";


MLddV8LR::usage="LddV8LR LEFT Wilson coefficient in array form";


MLudduV1LR::usage="LudduV1LR LEFT Wilson coefficient in array form";


MLudduV8LR::usage="LudduV8LR LEFT Wilson coefficient in array form";


MLeeSRR::usage="LeeSRR LEFT Wilson coefficient in array form";


MLeuSRR::usage="LeuSRR LEFT Wilson coefficient in array form";


MLeuTRR::usage="LeuTRR LEFT Wilson coefficient in array form";


MLedSRR::usage="LedSRR LEFT Wilson coefficient in array form";


MLedTRR::usage="LedTRR LEFT Wilson coefficient in array form";


ML\[Nu]eduSRR::usage="L\[Nu]eduSRR LEFT Wilson coefficient in array form";


ML\[Nu]eduTRR::usage="L\[Nu]eduTRR LEFT Wilson coefficient in array form";


MLuuS1RR::usage="LuuS1RR LEFT Wilson coefficient in array form";


MLuuS8RR::usage="LuuS8RR LEFT Wilson coefficient in array form";


MLudS1RR::usage="LudS1RR LEFT Wilson coefficient in array form";


MLudS8RR::usage="LudS8RR LEFT Wilson coefficient in array form";


MLddS1RR::usage="LddS1RR LEFT Wilson coefficient in array form";


MLddS8RR::usage="LddS8RR LEFT Wilson coefficient in array form";


MLudduS1RR::usage="LudduS1RR LEFT Wilson coefficient in array form";


MLudduS8RR::usage="LudduS8RR LEFT Wilson coefficient in array form";


MLeuSRL::usage="LeuSRL LEFT Wilson coefficient in array form";


MLedSRL::usage="LedSRL LEFT Wilson coefficient in array form";


ML\[Nu]eduSRL::usage="L\[Nu]eduSRL LEFT Wilson coefficient in array form";


ML\[Nu]\[Nu]SLL::usage="L\[Nu]\[Nu]SLL LEFT Wilson coefficient in array form";


ML\[Nu]eSLL::usage="L\[Nu]eSLL LEFT Wilson coefficient in array form";


ML\[Nu]eTLL::usage="L\[Nu]eTLL LEFT Wilson coefficient in array form";


ML\[Nu]eSLR::usage="L\[Nu]eSLR LEFT Wilson coefficient in array form";


ML\[Nu]uSLL::usage="L\[Nu]uSLL LEFT Wilson coefficient in array form";


ML\[Nu]uTLL::usage="L\[Nu]uTLL LEFT Wilson coefficient in array form";


ML\[Nu]uSLR::usage="L\[Nu]uSLR LEFT Wilson coefficient in array form";


ML\[Nu]dSLL::usage="L\[Nu]dSLL LEFT Wilson coefficient in array form";


ML\[Nu]dTLL::usage="L\[Nu]dTLL LEFT Wilson coefficient in array form";


ML\[Nu]dSLR::usage="L\[Nu]dSLR LEFT Wilson coefficient in array form";


ML\[Nu]eduSLL::usage="L\[Nu]eduSLL LEFT Wilson coefficient in array form";


ML\[Nu]eduTLL::usage="L\[Nu]eduTLL LEFT Wilson coefficient in array form";


ML\[Nu]eduSLR::usage="L\[Nu]eduSLR LEFT Wilson coefficient in array form";


ML\[Nu]eduVRL::usage="L\[Nu]eduVRL LEFT Wilson coefficient in array form";


ML\[Nu]eduVRR::usage="L\[Nu]eduVRR LEFT Wilson coefficient in array form";


MLuddSLL::usage="LuddSLL LEFT Wilson coefficient in array form";


MLduuSLL::usage="LduuSLL LEFT Wilson coefficient in array form";


MLuudSLR::usage="LuudSLR LEFT Wilson coefficient in array form";


MLduuSLR::usage="LduuSLR LEFT Wilson coefficient in array form";


MLuudSRL::usage="LuudSRL LEFT Wilson coefficient in array form";


MLduuSRL::usage="LduuSRL LEFT Wilson coefficient in array form";


MLdudSRL::usage="LdudSRL LEFT Wilson coefficient in array form";


MLdduSRL::usage="LdduSRL LEFT Wilson coefficient in array form";


MLduuSRR::usage="LduuSRR LEFT Wilson coefficient in array form";


MLdddSLL::usage="LdddSLL LEFT Wilson coefficient in array form";


MLuddSLR::usage="LuddSLR LEFT Wilson coefficient in array form";


MLdduSLR::usage="LdduSLR LEFT Wilson coefficient in array form";


MLdddSLR::usage="LdddSLR LEFT Wilson coefficient in array form";


MLdddSRL::usage="LdddSRL LEFT Wilson coefficient in array form";


MLuddSRR::usage="LuddSRR LEFT Wilson coefficient in array form";


MLdddSRR::usage="LdddSRR LEFT Wilson coefficient in array form";


TurnOnMessages::usage="TurnOnMessages turns on the messages written by DsixTools";


TurnOffMessages::usage="TurnOffMessages turns off the messages written by DsixTools";


SMEFTFindParameter::usage="SMEFTFindParameter[parameter] returns the position of parameter in the list of independent SMEFT parameters. SMEFTFindParameter[atributes,parameter] returns the position of parameter in a list composed by the independent SMEFT parameters with all attributes in the list attributes";


LEFTFindParameter::usage="LEFTFindParameter[parameter] returns the position of parameter in the list of independent LEFT parameters. LEFTFindParameter[atributes,parameter] returns the position of parameter in a list composed by the independent LEFT parameters with all attributes in the list attributes";


Biunitary::usage="Biunitary[mat] applies a biunitary transformation to the square matrix mat";


RunDsixTools::usage="Master DsixTools routine. RunDsixTools runs the SMEFT parameters from HIGHSCALE to EWSCALE, matches to the LEFT, and finally runs the LEFT parameters from EWSCALE to LOWSCALE";


SetRGEsMethod::usage="SetRGEsMethod[n] fixes the RGEsMethod option to n";


SetSMEFTLoopOrder::usage="SetSMEFTLoopOrder[n] fixes the SMEFTLoopOrder option to n";


SetLEFTLoopOrder::usage="SetLEFTLoopOrder[n] fixes the LEFTLoopOrder option to n";


SetMatchingLoopOrder::usage="SetMatchingLoopOrder[n] fixes the MatchingLoopOrder option to n";


ReadInputFiles::usage="ReadInputFiles[options_file,{WCsInput_file},{SMInput_file},{EFT}] reads all input files";


NewInput::usage="NewInput[list] resets the current InputValues dispatch to its default form in the theory EFT (SMEFT or LEFT) and then replaces it by a new one in which the changes in list, given as parameter \[Rule] newvalue, are applied. NewInput[list,additional] also applies the changes in additional, which can contain new input values for HIGHSCALE, EWSCALE, LOWSCALE and InputBasis";


ChangeInput::usage="ChangeInput[list] replaces the current InputValues dispatch by a new one in which the changes in list, given as parameter \[Rule] newvalue, are applied";


NewScale::usage="NewScale[list] replaces the current values of the energy scales following the changes in list, given as scale \[Rule] newvalue";


WCXFtoSLHA::usage="WCXFtoSLHA[WCXF_file,SLHA_file,EFT_] translates a WCs file in WCXF format into SLHA format";


SLHAtoWCXF::usage="SLHAtoWCXF[SLHA_file,WCXF_file,SCALE_,EFT_] translates a WCs file in SLHA format into WCXF format";


SetSMLEFTInput::usage="Routine that sets the LEFT input to a pure SM one";


D6Simplify::usage="D6Simplify[X] replaces all redundant Wilson coefficients in X by their expressions in terms of the non-redundant ones and eliminates complex conjugates on real parameters. It can also be used on analytical expressions containing several parameters";


NIndependent::usage="NIndependent[X] returns the number of independent real parameters in the parameter X: 2 for a general complex parameter, 1 for a real parameter and 0 for a redundant Wilson coefficient";


ToSymmetric::usage="ToSymmetric[X,cat] returns X in the symmetric basis, where X is an object of category cat in array form";


ToSymmetricSingle::usage="ToSymmetricSingle[X] returns the form of the SMEFT or LEFT parameter X in the symmetric basis";


ToIndependent::usage="ToIndependent[X,cat] returns X in the independent basis, where X is an object of category cat in array form";


ToIndependentSingle::usage="ToIndependentSingle[X] returns the form of the SMEFT or LEFT parameter X in the independent basis";


CheckAndSymmetrize::usage="CheckAndSymmetrize[X,cat] returns X in the symmetric basis, where X is an object of category cat in array form, after checking that all Hermiticity and antisymmetry conditions are respected. If any of the conditions are violated, some entries of X get modified";


ObjectInfo::usage="ObjectInfo[parameter] prints information about parameter";


SMEFTOperatorsMenu::usage="SMEFTOperatorsMenu displays a clickable menu with information about the parameters of the SMEFT";


LEFTOperatorsMenu::usage="LEFTOperatorsMenu displays a clickable menu with information about the parameters of the LEFT";


TotalOperatorsMenu::usage="TotalOperatorsMenu displays a clickable menu with information about all the parameters in the SMEFT and the LEFT";


SMEFTOperatorsGrid::usage="SMEFTOperatorsGrid creates a grid with all the SMEFT parameters. A window with information about any SMEFT parameter is displayed by clicking on it";


LEFTOperatorsGrid::usage="LEFTOperatorsGrid creates a grid with all the LEFT parameters. A window with information about any LEFT parameter is displayed by clicking on it";


SMEFTParameterList::usage="SMEFTParameterList[] returns the complete list of independent SMEFT parameters. SMEFTParameterList[attributes] returns a list with the independent SMEFT parameters with all attributes in the list attributes";


LEFTParameterList::usage="LEFTParameterList[] returns the complete list of independent LEFT parameters. LEFTParameterList[attributes] returns a list with the independent LEFT parameters with all attributes in the list attributes";


SMEFTRunRGEs::usage="SMEFTRunRGEs runs the SMEFT RGEs";


SMEFTEvolve::usage="SMEFTEvolve[X,x_Final,x_Initial] returns the SMEFT parameter X at x_Final=\[Mu]Final as a function of the SMEFT parameters at x_Initial=\[Mu]Initial, where both \[Mu]Initial and \[Mu]Final are energy scales given in GeV. SMEFTEvolve[X,xFinal,xInitial,'log10'] returns the SMEFT parameter X at x_Final=tFinal as a function of the SMEFT parameters at x_Initial=tInitial, with t = Log10(\[Mu]/GeV)";


(* ::Input::Initialization:: *)
SMEFTrunnerExport::usage="SMEFTrunnerExport[] exports the SMEFTrunner results to an SLHA output file. SMEFTrunnerExport[format,name] exports the SMEFTrunner results to an SLHA or WCXF output file of type format (SLHA, JSON or YAML) with a specific name";


SMEFTRotateParameters::usage="SMEFTRotateParameters[scale] returns a list containing two dispatches that transform the SMEFT parameters to the Up and Down bases at \[Mu] = scale";


SMEFTToNewBasis::usage="SMEFTToNewBasis[basis,scale] returns a dispatch that transforms the SMEFT parameters to a specific flavor basis ('up' or 'down') at \[Mu] = scale";


LEFTToNewBasis::usage="LEFTToNewBasis[scale] returns a dispatch that transforms the LEFT parameters to the Mass basis at \[Mu] = scale";


SMEFTLEFTMatch::usage="SMEFTLEFTMatch applies the complete tree-level matching between the SMEFT and the LEFT";


MatchEW::usage="MatchEW[X] returns the analytical matching condition of the LEFT parameter X";


EWmatcherExport::usage="EWmatcherExport[] exports the EWmatcher results to an SLHA output file. EWmatcherExport[format,name] exports the EWmatcher results to an SLHA or WCXF output file of type format (SLHA, JSON or YAML) with a specific name";


LEFTRunRGEs::usage="LEFTRunRGEs runs the LEFT RGEs";


LEFTEvolve::usage="LEFTEvolve[X,\[Mu]Initial,\[Mu]Final] returns the LEFT parameter X at \[Mu]=\[Mu]Final as a function of the LEFT parameters at \[Mu]=\[Mu]Initial, where both \[Mu]Initial and \[Mu]Final are energy scales given in GeV. LEFTEvolve[X,tInitial,tFinal,'log10'] returns the LEFT parameter X at t=tFinal as a function of the LEFT parameters at t=tInitial, with t = Log10(\[Mu]/GeV)";


(* ::Input::Initialization:: *)
LEFTrunnerExport::usage="LEFTrunnerExport[] exports the LEFTrunner results to an SLHA output file. LEFTrunnerExport[format,name] exports the LEFTrunner results to an SLHA or WCXF output file of type format (SLHA, JSON or YAML) with a specific name";


D6run::usage="D6run[X] returns a function of the energy scale \[Mu] with the result of running the SMEFT or LEFT parameter X from the input energy scale (HIGHSCALE or EWSCALE) to \[Mu]. D6run[X,'log10'] returns a function of t = Log10(\[Mu]/GeV) with the result of running the SMEFT or LEFT parameter X from the input energy scale (HIGHSCALE or EWSCALE) to \[Mu]";


SMEFTLagrangian::usage= "SMEFTLagrangian[\[Mu]0] gives the expression for the full SMEFT Lagrangian at \[Mu]=\[Mu]0, where \[Mu]0 is an energy scale in GeV, given the current input";


LEFTLagrangian::usage= "LEFTLagrangian[\[Mu]0] gives the expression for the full LEFT Lagrangian at \[Mu]=\[Mu]0, where \[Mu]0 is an energy scale in GeV, given the current input";


(* ::Input::Initialization:: *)
(*SetOptions[EvaluationNotebook[],CommonDefaultFormatTypes\[Rule]{"Output"\[Rule]StandardForm}];*)


(* ::Input::Initialization:: *)
DsixToolsVersion="2.0";


(* ::Input::Initialization:: *)
CellPrint[TextCell["DsixTools "<>ToString[DsixToolsVersion],"Text",Purple,Background->LightBlue,FontSize->14]];

Print["by Alejandro Celis, Javier Fuentes-Martin, Pedro Ruiz-Femenia, Avelino Vicente and Javier Virto \n",
"References: ",Hyperlink["arXiv:1704.04504","https://arxiv.org/abs/1704.04504"]," and ",Hyperlink["arXiv:2010.xxxxx","https://arxiv.org/abs/2010.xxxxx"],"\n",
"Website: ",Hyperlink["https://dsixtools.github.io/","https://dsixtools.github.io/"]];

(*Print[StyleForm["This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.",FontSize\[Rule]10]];*)


(* ::Input::Initialization:: *)
DsixToolsDir=DirectoryName[$InputFileName]<>"Package/";


Begin["`Private`"]


(* ::Input::Initialization:: *)
rs0=Table[0,{r,3},{s,3}];
rspt0=Table[0,{r,3},{s,3},{p,3},{t,3}];
I3=IdentityMatrix[3];


(* ::Input::Initialization:: *)
sWsq=0.2312;
\[Theta]W=ArcSin[Sqrt[sWsq]]; (* Weak mixing angle *)
\[Alpha]EM=1/137.036;
eEM=Sqrt[4Pi \[Alpha]EM]; (* Electromagnetic coupling *)
\[Alpha]S=0.1181; (* Strong coupling *)
m\[Tau]=1.77682; (* tau-lepton mass [GeV] -- PDG value *)
mc=1.275; (* c-quark MSbar mass [GeV] -- PDG value *)
mb=4.18; (* b-quark MSbar mass [GeV] -- PDG value *)
mh=125.0; (* Higgs boson mass [GeV] *)
mW=80.385; (* W-boson mass [GeV] *)
mZ=91.1876; (* Z-boson mass [GeV] *)
GF=1.16638*10^(-5); (* Fermi constant [GeV^(-2)] *)
v=(Sqrt[2]GF)^(-1/2); (* Higgs VEV *)


RGEsMethod=3;
UseRGEsSM=1;
SMEFTLoopOrder=5;
LEFTLoopOrder=4;
MatchingLoopOrder=1;
ImportFilesFlag=True;
InputBasis="down";


(* Flag that sets whether the files containing \[Beta] functions, evolution matrices and matching relations are loaded or not *)
If[!ImportFiles,ImportFilesFlag=False];


nu=2;
nd=3;
n\[Nu]=3;
ne=3;


(* ::Input::Initialization:: *)
InputFixed=False;
NonHermitianErrors={};
AntisymmetryErrors={};
NonHermitianErrorsTotal={};
AntisymmetryErrorsTotal={};


InitInput=False;
SMEFTrunner=False;
LEFTrunner=False;
EWmatcher=False;


Protect[HIGHSCALE];
Protect[EWSCALE];
Protect[LOWSCALE];
Protect[tHIGH];
Protect[tEW];
Protect[tLOW];
Protect[RGEsMethod];
Protect[SMEFTLoopOrder];
Protect[LEFTLoopOrder];
Protect[MatchingLoopOrder];
Protect[InputBasis];
Protect[LoopParameter];


(* ::Input::Initialization:: *)
PrintMessages=True;


BennyHill:=SoundNote[#[[1]],#[[2]],"Clarinet"]&/@Transpose[{{0,5,5,2,0,-3,-3,0,0,2,2,0,-3,-5,-7,-7,None,-3,-3,0,0,2,0,5,None,5,None},0.4/{0.4,2,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,1.5,4,0.5}}]//Sound//EmitSound;
Ouch:=Sound[SoundNote[Range[12],2]]//EmitSound;
Murder:=Block[{},
EmitSound[Sound[SoundNote[30,1,"Gunshot"]]];
Pause[1];EmitSound[Get[DsixToolsDir<>"scream.m"]]];


If[Round[Date[][[-1]]/100]==1,Murder]


Block[{},

Get[DsixToolsDir<>"input.m"];
Get[DsixToolsDir<>"output.m"];
Get[DsixToolsDir<>"tools.m"];
Get[DsixToolsDir<>"definitions.m"];

];


(* ::Input::Initialization:: *)
DefineParameters;


(* ::Input::Initialization:: *)
GenerateDefaultInput;
NewScale[{HIGHSCALE-> HIGHSCALE,EWSCALE->mZ,LOWSCALE->5}];


Block[{},

InitializeSMEFTrunnerInput;
InitializeEWmatcherInput;
InitializeLEFTrunnerInput;

];


If[ImportFilesFlag,
If[FileExistsQ[DsixToolsDir<>"BetaSMEFT.mx"],Import[DsixToolsDir<>"BetaSMEFT.mx"],Import[DsixToolsDir<>"BetaSMEFT.m"]];
If[FileExistsQ[DsixToolsDir<>"BetaSM.mx"],Import[DsixToolsDir<>"BetaSM.mx"],Import[DsixToolsDir<>"BetaSM.m"]];
If[FileExistsQ[DsixToolsDir<>"evolutionSMEFT.mx"],USMEFT=Import[DsixToolsDir<>"evolutionSMEFT.mx"],USMEFT=Import[DsixToolsDir<>"evolutionSMEFT.m"]];
If[FileExistsQ[DsixToolsDir<>"EWMatching.mx"],Import[DsixToolsDir<>"EWMatching.mx"],Import[DsixToolsDir<>"EWMatching.m"]];
If[FileExistsQ[DsixToolsDir<>"BetaLEFT.mx"],Import[DsixToolsDir<>"BetaLEFT.mx"];,Import[DsixToolsDir<>"BetaLEFT.m"]];
If[FileExistsQ[DsixToolsDir<>"evolutionLEFT.mx"],ULEFT=Import[DsixToolsDir<>"evolutionLEFT.mx"],ULEFT=Import[DsixToolsDir<>"evolutionLEFT.m"]];
BuildAllRGEs;
];


End[]


EndPackage[]
