(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Print[StyleForm["WETrunner","Section",FontSize->22,Bold]];
Print[StyleForm["DsixTools module for the RGE running of the Weak Effective Theory",FontSize->16]];
WETrunnerDir=DsixToolsDir<>"WETrunner/";
WETrunner=True;
InitializeWETrunnerInput;


RunRGEsWET:=Block[{},

MyPrint["Running"];
Get[WETrunnerDir<>"WETrun.m"];
MyPrint["Running finished!"];

];


ExportWETrunner:=Block[{},

If[exportWETrunner==1,
MyPrint["Exporting WETrunner results"];
dataOutput=Chop[Join[BS2Low,BC1Low,BS1unprimedLow,BS1primedLow]/.t->Log[10,mb],$MachineEpsilon];
outname="Output_WETrunner.dat";
WriteWETrunnerOutputFile[outname,dataOutput,mb];
];

];
