(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Get[WETrunnerDir<>"EvolutionMatrices.m"];


(* ::Input::Initialization:: *)
\[Eta]s=1+\[Beta]s/(2Pi)\[Alpha]S Log[10](t-tLOW);


(* QCD evolution matrix *)
UBS2qcd=Us[I];


(* ::Input::Initialization:: *)
(* QED evolution matrix *)
UBS2qed=Ue[I]/.{\[Alpha]s[\[Mu]0]->\[Alpha]S,\[Alpha]em->\[Alpha]EM};


(* ::Input::Initialization:: *)
(* Result *)
BS2Low=(UBS2qcd+UBS2qed).BS2;


(* QCD evolution matrix *)
UBC1qcd=ArrayFlatten[{{Us[II],Table[0,{5},{5}],Table[0,{5},{5}]},{Table[0,{5},{5}],Us[II],Table[0,{5},{5}]},{Table[0,{5},{5}],Table[0,{5},{5}],Us[II]}}];


(* ::Input::Initialization:: *)
(* QED evolution matrix *)
UBC1qed=ArrayFlatten[{{Ue[II],Table[0,{5},{5}],Table[0,{5},{5}]},{Table[0,{5},{5}],Ue[II],Table[0,{5},{5}]},{Table[0,{5},{5}],Table[0,{5},{5}],Ue[II]}}]/.{\[Alpha]s[\[Mu]0]->\[Alpha]S,\[Alpha]em->\[Alpha]EM};


(* ::Input::Initialization:: *)
(* Result *)
BC1Low=(UBC1qcd+UBC1qed).BC1;


(* ::Input::Initialization:: *)
(* QCD evolution matrix *)
UBS1qcd=Us[V];


(* QED evolution matrix *)
UBS1qed=Ue[V]/.{\[Alpha]s[\[Mu]0]->\[Alpha]S,\[Alpha]em->\[Alpha]EM};


(* ::Input::Initialization:: *)
(* Result *)
BS1unprimedLow=(UBS1qcd+UBS1qed).BS1unprimed;
BS1primedLow=(UBS1qcd+UBS1qed).BS1primed;
