(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



MatchCBC1[e][1]=(v^2 LQ3[1,1,3,3] VCKM[c,b])/HIGHSCALE^2+(v^2 LQ3[1,1,1,3] VCKM[c,d])/HIGHSCALE^2+(v^2 LQ3[1,1,2,3] VCKM[c,s])/HIGHSCALE^2-(v^2 VCKM[c,d] \[CurlyPhi]Q3[1,3])/HIGHSCALE^2-(v^2 VCKM[c,s] \[CurlyPhi]Q3[2,3])/HIGHSCALE^2-(v^2 VCKM[c,b] \[CurlyPhi]Q3[3,3])/HIGHSCALE^2;


MatchCBC1[\[Mu]][1]=(v^2 LQ3[2,2,3,3] VCKM[c,b])/HIGHSCALE^2+(v^2 LQ3[2,2,1,3] VCKM[c,d])/HIGHSCALE^2+(v^2 LQ3[2,2,2,3] VCKM[c,s])/HIGHSCALE^2-(v^2 VCKM[c,d] \[CurlyPhi]Q3[1,3])/HIGHSCALE^2-(v^2 VCKM[c,s] \[CurlyPhi]Q3[2,3])/HIGHSCALE^2-(v^2 VCKM[c,b] \[CurlyPhi]Q3[3,3])/HIGHSCALE^2;


MatchCBC1[\[Tau]][1]=(v^2 LQ3[3,3,3,3] VCKM[c,b])/HIGHSCALE^2+(v^2 LQ3[3,3,1,3] VCKM[c,d])/HIGHSCALE^2+(v^2 LQ3[3,3,2,3] VCKM[c,s])/HIGHSCALE^2-(v^2 VCKM[c,d] \[CurlyPhi]Q3[1,3])/HIGHSCALE^2-(v^2 VCKM[c,s] \[CurlyPhi]Q3[2,3])/HIGHSCALE^2-(v^2 VCKM[c,b] \[CurlyPhi]Q3[3,3])/HIGHSCALE^2;


MatchCBC1[e][5]=(v^2 CC[LEDQ[1,1,3,3]] VCKM[c,b])/(2 HIGHSCALE^2)+(v^2 CC[LEDQ[1,1,3,1]] VCKM[c,d])/(2 HIGHSCALE^2)+(v^2 CC[LEDQ[1,1,3,2]] VCKM[c,s])/(2 HIGHSCALE^2);


MatchCBC1[\[Mu]][5]=(v^2 CC[LEDQ[2,2,3,3]] VCKM[c,b])/(2HIGHSCALE^2)+(v^2 CC[LEDQ[2,2,3,1]] VCKM[c,d])/(2 HIGHSCALE^2)+(v^2 CC[LEDQ[2,2,3,2]] VCKM[c,s])/(2 HIGHSCALE^2);


MatchCBC1[\[Tau]][5]=(v^2 CC[LEDQ[3,3,3,3]] VCKM[c,b])/(2HIGHSCALE^2)+(v^2 CC[LEDQ[3,3,3,1]] VCKM[c,d])/(2HIGHSCALE^2)+(v^2 CC[LEDQ[3,3,3,2]] VCKM[c,s])/(2 HIGHSCALE^2);


MatchCBC1p[e][1]=-((v^2 \[CurlyPhi]UD[2,3])/(2HIGHSCALE^2));


MatchCBC1p[\[Mu]][1]=-((v^2 \[CurlyPhi]UD[2,3])/(2HIGHSCALE^2));


MatchCBC1p[\[Tau]][1]=-((v^2 \[CurlyPhi]UD[2,3])/(2 HIGHSCALE^2));


MatchCBC1p[e][5]=(v^2 CC[LEQU1[1,1,3,3]] VCKM[c,b])/(2HIGHSCALE^2)+(v^2 CC[LEQU1[1,1,3,1]] VCKM[c,d])/(2HIGHSCALE^2)+(v^2 CC[LEQU1[1,1,3,2]] VCKM[c,s])/(2HIGHSCALE^2);


MatchCBC1p[\[Mu]][5]=(v^2 CC[LEQU1[2,2,3,3]] VCKM[c,b])/(2HIGHSCALE^2)+(v^2 CC[LEQU1[2,2,3,1]] VCKM[c,d])/(2HIGHSCALE^2)+(v^2 CC[LEQU1[2,2,3,2]] VCKM[c,s])/(2 HIGHSCALE^2);


MatchCBC1p[\[Tau]][5]=(v^2 CC[LEQU1[3,3,3,3]] VCKM[c,b])/(2 HIGHSCALE^2)+(v^2 CC[LEQU1[3,3,3,1]] VCKM[c,d])/(2HIGHSCALE^2)+(v^2 CC[LEQU1[3,3,3,2]] VCKM[c,s])/(2HIGHSCALE^2);


MatchCBC1p[e][7]=(v^2 CC[LEQU3[1,1,3,3]] VCKM[c,b])/(2HIGHSCALE^2)+(v^2 CC[LEQU3[1,1,3,1]] VCKM[c,d])/(2HIGHSCALE^2)+(v^2 CC[LEQU3[1,1,3,2]] VCKM[c,s])/(2HIGHSCALE^2);


MatchCBC1p[\[Mu]][7]=(v^2 CC[LEQU3[2,2,3,3]] VCKM[c,b])/(2HIGHSCALE^2)+(v^2 CC[LEQU3[2,2,3,1]] VCKM[c,d])/(2HIGHSCALE^2)+(v^2 CC[LEQU3[2,2,3,2]] VCKM[c,s])/(2 HIGHSCALE^2);


MatchCBC1p[\[Tau]][7]=(v^2 CC[LEQU3[3,3,3,3]] VCKM[c,b])/(2HIGHSCALE^2)+(v^2 CC[LEQU3[3,3,3,1]] VCKM[c,d])/(2HIGHSCALE^2)+(v^2 CC[LEQU3[3,3,3,2]] VCKM[c,s])/(2 HIGHSCALE^2);
