(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



MatchCBS1[u][1]=-((v^2 \[CurlyPhi]Q1[2,3])/(6 HIGHSCALE^2))-(v^2 \[CurlyPhi]Q3[2,3])/(6 HIGHSCALE^2)+(2 v^2 QU1[2,3,1,1])/(3 HIGHSCALE^2)-(2 v^2 \[CurlyPhi]Q1[2,3] Sin[\[Theta]W]^2)/(3 HIGHSCALE^2)-(2 v^2 \[CurlyPhi]Q3[2,3] Sin[\[Theta]W]^2)/(3 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3] VV[u,b,u,b])/(9 HIGHSCALE^2)-(v^2 QQ1[2,3,3,3] VV[u,b,u,b])/(6 HIGHSCALE^2)+(v^2 QQ3[2,3,3,3] VV[u,b,u,b])/(18 HIGHSCALE^2)-(v^2 QQ1[1,3,2,3] VV[u,b,u,d])/(6 HIGHSCALE^2)+(v^2 QQ3[1,3,2,3] VV[u,b,u,d])/(18 HIGHSCALE^2)-(v^2 QQ1[2,3,2,3] VV[u,b,u,s])/(3 HIGHSCALE^2)+(v^2 QQ3[2,3,2,3] VV[u,b,u,s])/(9 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,1] VV[u,d,u,b])/(9 HIGHSCALE^2)-(v^2 QQ1[2,3,3,1] VV[u,d,u,b])/(6 HIGHSCALE^2)-(v^2 QQ3[2,1,3,3] VV[u,d,u,b])/(9 HIGHSCALE^2)+(v^2 QQ3[2,3,3,1] VV[u,d,u,b])/(6 HIGHSCALE^2)-(v^2 QQ1[1,1,2,3] VV[u,d,u,d])/(6 HIGHSCALE^2)+(v^2 QQ3[1,1,2,3] VV[u,d,u,d])/(6 HIGHSCALE^2)-(v^2 QQ3[1,3,2,1] VV[u,d,u,d])/(9 HIGHSCALE^2)-(v^2 QQ1[2,1,2,3] VV[u,d,u,s])/(6 HIGHSCALE^2)+(v^2 QQ3[2,1,2,3] VV[u,d,u,s])/(18 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,2] VV[u,s,u,b])/(9 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[3,3] VV[u,s,u,b])/(9 HIGHSCALE^2)-(v^2 QQ1[2,3,3,2] VV[u,s,u,b])/(6 HIGHSCALE^2)-(v^2 QQ3[2,2,3,3] VV[u,s,u,b])/(9 HIGHSCALE^2)+(v^2 QQ3[2,3,3,2] VV[u,s,u,b])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[1,3] VV[u,s,u,d])/(9 HIGHSCALE^2)-(v^2 QQ1[1,2,2,3] VV[u,s,u,d])/(6 HIGHSCALE^2)+(v^2 QQ3[1,2,2,3] VV[u,s,u,d])/(6 HIGHSCALE^2)-(v^2 QQ3[1,3,2,2] VV[u,s,u,d])/(9 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3] VV[u,s,u,s])/(9 HIGHSCALE^2)-(v^2 QQ1[2,2,2,3] VV[u,s,u,s])/(6 HIGHSCALE^2)+(v^2 QQ3[2,2,2,3] VV[u,s,u,s])/(18 HIGHSCALE^2);


MatchCBS1[u][2]=(2 v^2 QU8[2,3,1,1])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]Q3[2,3] VV[u,b,u,b])/(3 HIGHSCALE^2)-(2 v^2 QQ3[2,3,3,3] VV[u,b,u,b])/(3 HIGHSCALE^2)-(2 v^2 QQ3[1,3,2,3] VV[u,b,u,d])/(3 HIGHSCALE^2)-(4 v^2 QQ3[2,3,2,3] VV[u,b,u,s])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]Q3[2,1] VV[u,d,u,b])/(3 HIGHSCALE^2)-(2 v^2 QQ3[2,1,3,3] VV[u,d,u,b])/(3 HIGHSCALE^2)-(2 v^2 QQ3[1,3,2,1] VV[u,d,u,d])/(3 HIGHSCALE^2)-(2 v^2 QQ3[2,1,2,3] VV[u,d,u,s])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]Q3[2,2] VV[u,s,u,b])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]Q3[3,3] VV[u,s,u,b])/(3 HIGHSCALE^2)-(2 v^2 QQ3[2,2,3,3] VV[u,s,u,b])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]Q3[1,3] VV[u,s,u,d])/(3 HIGHSCALE^2)-(2 v^2 QQ3[1,3,2,2] VV[u,s,u,d])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]Q3[2,3] VV[u,s,u,s])/(3 HIGHSCALE^2)-(2 v^2 QQ3[2,2,2,3] VV[u,s,u,s])/(3 HIGHSCALE^2);


MatchCBS1[u][3]=(v^2 \[CurlyPhi]Q1[2,3])/(24 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3])/(24 HIGHSCALE^2)-(v^2 QU1[2,3,1,1])/(24 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,3] VV[u,b,u,b])/(36 HIGHSCALE^2)+(v^2 QQ1[2,3,3,3] VV[u,b,u,b])/(24 HIGHSCALE^2)-(v^2 QQ3[2,3,3,3] VV[u,b,u,b])/(72 HIGHSCALE^2)+(v^2 QQ1[1,3,2,3] VV[u,b,u,d])/(24 HIGHSCALE^2)-(v^2 QQ3[1,3,2,3] VV[u,b,u,d])/(72 HIGHSCALE^2)+(v^2 QQ1[2,3,2,3] VV[u,b,u,s])/(12 HIGHSCALE^2)-(v^2 QQ3[2,3,2,3] VV[u,b,u,s])/(36 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,1] VV[u,d,u,b])/(36 HIGHSCALE^2)+(v^2 QQ1[2,3,3,1] VV[u,d,u,b])/(24 HIGHSCALE^2)+(v^2 QQ3[2,1,3,3] VV[u,d,u,b])/(36 HIGHSCALE^2)-(v^2 QQ3[2,3,3,1] VV[u,d,u,b])/(24 HIGHSCALE^2)+(v^2 QQ1[1,1,2,3] VV[u,d,u,d])/(24 HIGHSCALE^2)-(v^2 QQ3[1,1,2,3] VV[u,d,u,d])/(24 HIGHSCALE^2)+(v^2 QQ3[1,3,2,1] VV[u,d,u,d])/(36 HIGHSCALE^2)+(v^2 QQ1[2,1,2,3] VV[u,d,u,s])/(24 HIGHSCALE^2)-(v^2 QQ3[2,1,2,3] VV[u,d,u,s])/(72 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,2] VV[u,s,u,b])/(36 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[3,3] VV[u,s,u,b])/(36 HIGHSCALE^2)+(v^2 QQ1[2,3,3,2] VV[u,s,u,b])/(24 HIGHSCALE^2)+(v^2 QQ3[2,2,3,3] VV[u,s,u,b])/(36 HIGHSCALE^2)-(v^2 QQ3[2,3,3,2] VV[u,s,u,b])/(24 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[1,3] VV[u,s,u,d])/(36 HIGHSCALE^2)+(v^2 QQ1[1,2,2,3] VV[u,s,u,d])/(24 HIGHSCALE^2)-(v^2 QQ3[1,2,2,3] VV[u,s,u,d])/(24 HIGHSCALE^2)+(v^2 QQ3[1,3,2,2] VV[u,s,u,d])/(36 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,3] VV[u,s,u,s])/(36 HIGHSCALE^2)+(v^2 QQ1[2,2,2,3] VV[u,s,u,s])/(24 HIGHSCALE^2)-(v^2 QQ3[2,2,2,3] VV[u,s,u,s])/(72 HIGHSCALE^2);


MatchCBS1[u][4]=-((v^2 QU8[2,3,1,1])/(24 HIGHSCALE^2))-(v^2 \[CurlyPhi]Q3[2,3] VV[u,b,u,b])/(6 HIGHSCALE^2)+(v^2 QQ3[2,3,3,3] VV[u,b,u,b])/(6 HIGHSCALE^2)+(v^2 QQ3[1,3,2,3] VV[u,b,u,d])/(6 HIGHSCALE^2)+(v^2 QQ3[2,3,2,3] VV[u,b,u,s])/(3 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,1] VV[u,d,u,b])/(6 HIGHSCALE^2)+(v^2 QQ3[2,1,3,3] VV[u,d,u,b])/(6 HIGHSCALE^2)+(v^2 QQ3[1,3,2,1] VV[u,d,u,d])/(6 HIGHSCALE^2)+(v^2 QQ3[2,1,2,3] VV[u,d,u,s])/(6 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,2] VV[u,s,u,b])/(6 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[3,3] VV[u,s,u,b])/(6 HIGHSCALE^2)+(v^2 QQ3[2,2,3,3] VV[u,s,u,b])/(6 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[1,3] VV[u,s,u,d])/(6 HIGHSCALE^2)+(v^2 QQ3[1,3,2,2] VV[u,s,u,d])/(6 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,3] VV[u,s,u,s])/(6 HIGHSCALE^2)+(v^2 QQ3[2,2,2,3] VV[u,s,u,s])/(6 HIGHSCALE^2);


MatchCBS1[u][5]=-((4 v^2 CC[VCKM[u,s]] \[CurlyPhi]UD[1,3])/(9 HIGHSCALE^2))-(v^2 QUQD1[1,1,2,3])/(6 HIGHSCALE^2)-(v^2 QUQD1[2,1,3,3] VV[c,s,u,b])/(36 HIGHSCALE^2)-(v^2 QUQD8[2,1,3,3] VV[c,s,u,b])/(27 HIGHSCALE^2)-(v^2 QUQD1[2,1,1,3] VV[c,s,u,d])/(36 HIGHSCALE^2)-(v^2 QUQD8[2,1,1,3] VV[c,s,u,d])/(27 HIGHSCALE^2)-(v^2 QUQD1[2,1,2,3] VV[c,s,u,s])/(36 HIGHSCALE^2)-(v^2 QUQD8[2,1,2,3] VV[c,s,u,s])/(27 HIGHSCALE^2)-(v^2 QUQD1[3,1,3,3] VV[t,s,u,b])/(36 HIGHSCALE^2)-(v^2 QUQD8[3,1,3,3] VV[t,s,u,b])/(27 HIGHSCALE^2)-(v^2 QUQD1[3,1,1,3] VV[t,s,u,d])/(36 HIGHSCALE^2)-(v^2 QUQD8[3,1,1,3] VV[t,s,u,d])/(27 HIGHSCALE^2)-(v^2 QUQD1[3,1,2,3] VV[t,s,u,s])/(36 HIGHSCALE^2)-(v^2 QUQD8[3,1,2,3] VV[t,s,u,s])/(27 HIGHSCALE^2)-(v^2 QUQD1[1,1,3,3] VV[u,s,u,b])/(36 HIGHSCALE^2)-(v^2 QUQD8[1,1,3,3] VV[u,s,u,b])/(27 HIGHSCALE^2)-(v^2 QUQD1[1,1,1,3] VV[u,s,u,d])/(36 HIGHSCALE^2)-(v^2 QUQD8[1,1,1,3] VV[u,s,u,d])/(27 HIGHSCALE^2)-(v^2 QUQD1[1,1,2,3] VV[u,s,u,s])/(36 HIGHSCALE^2)-(v^2 QUQD8[1,1,2,3] VV[u,s,u,s])/(27 HIGHSCALE^2);


MatchCBS1[u][6]=-((8 v^2 CC[VCKM[u,s]] \[CurlyPhi]UD[1,3])/(3 HIGHSCALE^2))-(v^2 QUQD8[1,1,2,3])/(6 HIGHSCALE^2)-(v^2 QUQD1[2,1,3,3] VV[c,s,u,b])/(6 HIGHSCALE^2)+(v^2 QUQD8[2,1,3,3] VV[c,s,u,b])/(36 HIGHSCALE^2)-(v^2 QUQD1[2,1,1,3] VV[c,s,u,d])/(6 HIGHSCALE^2)+(v^2 QUQD8[2,1,1,3] VV[c,s,u,d])/(36 HIGHSCALE^2)-(v^2 QUQD1[2,1,2,3] VV[c,s,u,s])/(6 HIGHSCALE^2)+(v^2 QUQD8[2,1,2,3] VV[c,s,u,s])/(36 HIGHSCALE^2)-(v^2 QUQD1[3,1,3,3] VV[t,s,u,b])/(6 HIGHSCALE^2)+(v^2 QUQD8[3,1,3,3] VV[t,s,u,b])/(36 HIGHSCALE^2)-(v^2 QUQD1[3,1,1,3] VV[t,s,u,d])/(6 HIGHSCALE^2)+(v^2 QUQD8[3,1,1,3] VV[t,s,u,d])/(36 HIGHSCALE^2)-(v^2 QUQD1[3,1,2,3] VV[t,s,u,s])/(6 HIGHSCALE^2)+(v^2 QUQD8[3,1,2,3] VV[t,s,u,s])/(36 HIGHSCALE^2)-(v^2 QUQD1[1,1,3,3] VV[u,s,u,b])/(6 HIGHSCALE^2)+(v^2 QUQD8[1,1,3,3] VV[u,s,u,b])/(36 HIGHSCALE^2)-(v^2 QUQD1[1,1,1,3] VV[u,s,u,d])/(6 HIGHSCALE^2)+(v^2 QUQD8[1,1,1,3] VV[u,s,u,d])/(36 HIGHSCALE^2)-(v^2 QUQD1[1,1,2,3] VV[u,s,u,s])/(6 HIGHSCALE^2)+(v^2 QUQD8[1,1,2,3] VV[u,s,u,s])/(36 HIGHSCALE^2);


MatchCBS1[u][7]=(v^2 CC[VCKM[u,s]] \[CurlyPhi]UD[1,3])/(9 HIGHSCALE^2)+(v^2 QUQD1[1,1,2,3])/(6 HIGHSCALE^2)+(7 v^2 QUQD1[2,1,3,3] VV[c,s,u,b])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[2,1,3,3] VV[c,s,u,b])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[2,1,1,3] VV[c,s,u,d])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[2,1,1,3] VV[c,s,u,d])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[2,1,2,3] VV[c,s,u,s])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[2,1,2,3] VV[c,s,u,s])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[3,1,3,3] VV[t,s,u,b])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[3,1,3,3] VV[t,s,u,b])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[3,1,1,3] VV[t,s,u,d])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[3,1,1,3] VV[t,s,u,d])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[3,1,2,3] VV[t,s,u,s])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[3,1,2,3] VV[t,s,u,s])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[1,1,3,3] VV[u,s,u,b])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[1,1,3,3] VV[u,s,u,b])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[1,1,1,3] VV[u,s,u,d])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[1,1,1,3] VV[u,s,u,d])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[1,1,2,3] VV[u,s,u,s])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[1,1,2,3] VV[u,s,u,s])/(108 HIGHSCALE^2);


MatchCBS1[u][8]=(2 v^2 CC[VCKM[u,s]] \[CurlyPhi]UD[1,3])/(3 HIGHSCALE^2)+(v^2 QUQD8[1,1,2,3])/(6 HIGHSCALE^2)+(7 v^2 QUQD1[2,1,3,3] VV[c,s,u,b])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[2,1,3,3] VV[c,s,u,b])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[2,1,1,3] VV[c,s,u,d])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[2,1,1,3] VV[c,s,u,d])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[2,1,2,3] VV[c,s,u,s])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[2,1,2,3] VV[c,s,u,s])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[3,1,3,3] VV[t,s,u,b])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[3,1,3,3] VV[t,s,u,b])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[3,1,1,3] VV[t,s,u,d])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[3,1,1,3] VV[t,s,u,d])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[3,1,2,3] VV[t,s,u,s])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[3,1,2,3] VV[t,s,u,s])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[1,1,3,3] VV[u,s,u,b])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[1,1,3,3] VV[u,s,u,b])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[1,1,1,3] VV[u,s,u,d])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[1,1,1,3] VV[u,s,u,d])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[1,1,2,3] VV[u,s,u,s])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[1,1,2,3] VV[u,s,u,s])/(144 HIGHSCALE^2);


MatchCBS1[u][9]=(v^2 CC[VCKM[u,s]] \[CurlyPhi]UD[1,3])/(144 HIGHSCALE^2)+(v^2 QUQD1[1,1,2,3])/(96 HIGHSCALE^2)+(v^2 QUQD1[2,1,3,3] VV[c,s,u,b])/(576 HIGHSCALE^2)+(v^2 QUQD8[2,1,3,3] VV[c,s,u,b])/(432 HIGHSCALE^2)+(v^2 QUQD1[2,1,1,3] VV[c,s,u,d])/(576 HIGHSCALE^2)+(v^2 QUQD8[2,1,1,3] VV[c,s,u,d])/(432 HIGHSCALE^2)+(v^2 QUQD1[2,1,2,3] VV[c,s,u,s])/(576 HIGHSCALE^2)+(v^2 QUQD8[2,1,2,3] VV[c,s,u,s])/(432 HIGHSCALE^2)+(v^2 QUQD1[3,1,3,3] VV[t,s,u,b])/(576 HIGHSCALE^2)+(v^2 QUQD8[3,1,3,3] VV[t,s,u,b])/(432 HIGHSCALE^2)+(v^2 QUQD1[3,1,1,3] VV[t,s,u,d])/(576 HIGHSCALE^2)+(v^2 QUQD8[3,1,1,3] VV[t,s,u,d])/(432 HIGHSCALE^2)+(v^2 QUQD1[3,1,2,3] VV[t,s,u,s])/(576 HIGHSCALE^2)+(v^2 QUQD8[3,1,2,3] VV[t,s,u,s])/(432 HIGHSCALE^2)+(v^2 QUQD1[1,1,3,3] VV[u,s,u,b])/(576 HIGHSCALE^2)+(v^2 QUQD8[1,1,3,3] VV[u,s,u,b])/(432 HIGHSCALE^2)+(v^2 QUQD1[1,1,1,3] VV[u,s,u,d])/(576 HIGHSCALE^2)+(v^2 QUQD8[1,1,1,3] VV[u,s,u,d])/(432 HIGHSCALE^2)+(v^2 QUQD1[1,1,2,3] VV[u,s,u,s])/(576 HIGHSCALE^2)+(v^2 QUQD8[1,1,2,3] VV[u,s,u,s])/(432 HIGHSCALE^2);


MatchCBS1[u][10]=(v^2 CC[VCKM[u,s]] \[CurlyPhi]UD[1,3])/(24 HIGHSCALE^2)+(v^2 QUQD8[1,1,2,3])/(96 HIGHSCALE^2)+(v^2 QUQD1[2,1,3,3] VV[c,s,u,b])/(96 HIGHSCALE^2)-(v^2 QUQD8[2,1,3,3] VV[c,s,u,b])/(576 HIGHSCALE^2)+(v^2 QUQD1[2,1,1,3] VV[c,s,u,d])/(96 HIGHSCALE^2)-(v^2 QUQD8[2,1,1,3] VV[c,s,u,d])/(576 HIGHSCALE^2)+(v^2 QUQD1[2,1,2,3] VV[c,s,u,s])/(96 HIGHSCALE^2)-(v^2 QUQD8[2,1,2,3] VV[c,s,u,s])/(576 HIGHSCALE^2)+(v^2 QUQD1[3,1,3,3] VV[t,s,u,b])/(96 HIGHSCALE^2)-(v^2 QUQD8[3,1,3,3] VV[t,s,u,b])/(576 HIGHSCALE^2)+(v^2 QUQD1[3,1,1,3] VV[t,s,u,d])/(96 HIGHSCALE^2)-(v^2 QUQD8[3,1,1,3] VV[t,s,u,d])/(576 HIGHSCALE^2)+(v^2 QUQD1[3,1,2,3] VV[t,s,u,s])/(96 HIGHSCALE^2)-(v^2 QUQD8[3,1,2,3] VV[t,s,u,s])/(576 HIGHSCALE^2)+(v^2 QUQD1[1,1,3,3] VV[u,s,u,b])/(96 HIGHSCALE^2)-(v^2 QUQD8[1,1,3,3] VV[u,s,u,b])/(576 HIGHSCALE^2)+(v^2 QUQD1[1,1,1,3] VV[u,s,u,d])/(96 HIGHSCALE^2)-(v^2 QUQD8[1,1,1,3] VV[u,s,u,d])/(576 HIGHSCALE^2)+(v^2 QUQD1[1,1,2,3] VV[u,s,u,s])/(96 HIGHSCALE^2)-(v^2 QUQD8[1,1,2,3] VV[u,s,u,s])/(576 HIGHSCALE^2);


MatchCBS1[d][1]=(v^2 \[CurlyPhi]Q1[2,3])/(3 HIGHSCALE^2)-(v^2 Cos[2 \[Theta]W] \[CurlyPhi]Q1[2,3])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3])/(3 HIGHSCALE^2)-(v^2 Cos[2 \[Theta]W] \[CurlyPhi]Q3[2,3])/(6 HIGHSCALE^2)+(2 v^2 QD1[2,3,1,1])/(3 HIGHSCALE^2)-(v^2 QQ1[1,1,2,3])/(6 HIGHSCALE^2)-(v^2 QQ1[1,3,2,1])/(18 HIGHSCALE^2)-(v^2 QQ3[1,1,2,3])/(6 HIGHSCALE^2)-(v^2 QQ3[1,3,2,1])/(18 HIGHSCALE^2);


MatchCBS1[d][2]=(2 v^2 QD8[2,3,1,1])/(3 HIGHSCALE^2)-(v^2 QQ1[1,3,2,1])/(3 HIGHSCALE^2)-(v^2 QQ3[1,3,2,1])/(3 HIGHSCALE^2);


MatchCBS1[d][3]=-((v^2 \[CurlyPhi]Q1[2,3])/(24 HIGHSCALE^2))-(v^2 \[CurlyPhi]Q3[2,3])/(24 HIGHSCALE^2)-(v^2 QD1[2,3,1,1])/(24 HIGHSCALE^2)+(v^2 QQ1[1,1,2,3])/(24 HIGHSCALE^2)+(v^2 QQ1[1,3,2,1])/(72 HIGHSCALE^2)+(v^2 QQ3[1,1,2,3])/(24 HIGHSCALE^2)+(v^2 QQ3[1,3,2,1])/(72 HIGHSCALE^2);


MatchCBS1[d][4]=-((v^2 QD8[2,3,1,1])/(24 HIGHSCALE^2))+(v^2 QQ1[1,3,2,1])/(12 HIGHSCALE^2)+(v^2 QQ3[1,3,2,1])/(12 HIGHSCALE^2);


MatchCBS1[d][5]=0;


MatchCBS1[d][6]=0;


MatchCBS1[d][7]=0;


MatchCBS1[d][8]=0;


MatchCBS1[d][9]=0;


MatchCBS1[d][10]=0;


MatchCBS1[c][1]=-((v^2 \[CurlyPhi]Q1[2,3])/(6 HIGHSCALE^2))-(v^2 \[CurlyPhi]Q3[2,3])/(6 HIGHSCALE^2)+(2 v^2 QU1[2,3,2,2])/(3 HIGHSCALE^2)-(2 v^2 \[CurlyPhi]Q1[2,3] Sin[\[Theta]W]^2)/(3 HIGHSCALE^2)-(2 v^2 \[CurlyPhi]Q3[2,3] Sin[\[Theta]W]^2)/(3 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3] VV[c,b,c,b])/(9 HIGHSCALE^2)-(v^2 QQ1[2,3,3,3] VV[c,b,c,b])/(6 HIGHSCALE^2)+(v^2 QQ3[2,3,3,3] VV[c,b,c,b])/(18 HIGHSCALE^2)-(v^2 QQ1[1,3,2,3] VV[c,b,c,d])/(6 HIGHSCALE^2)+(v^2 QQ3[1,3,2,3] VV[c,b,c,d])/(18 HIGHSCALE^2)-(v^2 QQ1[2,3,2,3] VV[c,b,c,s])/(3 HIGHSCALE^2)+(v^2 QQ3[2,3,2,3] VV[c,b,c,s])/(9 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,1] VV[c,d,c,b])/(9 HIGHSCALE^2)-(v^2 QQ1[2,3,3,1] VV[c,d,c,b])/(6 HIGHSCALE^2)-(v^2 QQ3[2,1,3,3] VV[c,d,c,b])/(9 HIGHSCALE^2)+(v^2 QQ3[2,3,3,1] VV[c,d,c,b])/(6 HIGHSCALE^2)-(v^2 QQ1[1,1,2,3] VV[c,d,c,d])/(6 HIGHSCALE^2)+(v^2 QQ3[1,1,2,3] VV[c,d,c,d])/(6 HIGHSCALE^2)-(v^2 QQ3[1,3,2,1] VV[c,d,c,d])/(9 HIGHSCALE^2)-(v^2 QQ1[2,1,2,3] VV[c,d,c,s])/(6 HIGHSCALE^2)+(v^2 QQ3[2,1,2,3] VV[c,d,c,s])/(18 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,2] VV[c,s,c,b])/(9 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[3,3] VV[c,s,c,b])/(9 HIGHSCALE^2)-(v^2 QQ1[2,3,3,2] VV[c,s,c,b])/(6 HIGHSCALE^2)-(v^2 QQ3[2,2,3,3] VV[c,s,c,b])/(9 HIGHSCALE^2)+(v^2 QQ3[2,3,3,2] VV[c,s,c,b])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[1,3] VV[c,s,c,d])/(9 HIGHSCALE^2)-(v^2 QQ1[1,2,2,3] VV[c,s,c,d])/(6 HIGHSCALE^2)+(v^2 QQ3[1,2,2,3] VV[c,s,c,d])/(6 HIGHSCALE^2)-(v^2 QQ3[1,3,2,2] VV[c,s,c,d])/(9 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3] VV[c,s,c,s])/(9 HIGHSCALE^2)-(v^2 QQ1[2,2,2,3] VV[c,s,c,s])/(6 HIGHSCALE^2)+(v^2 QQ3[2,2,2,3] VV[c,s,c,s])/(18 HIGHSCALE^2);


MatchCBS1[c][2]=(2 v^2 QU8[2,3,2,2])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]Q3[2,3] VV[c,b,c,b])/(3 HIGHSCALE^2)-(2 v^2 QQ3[2,3,3,3] VV[c,b,c,b])/(3 HIGHSCALE^2)-(2 v^2 QQ3[1,3,2,3] VV[c,b,c,d])/(3 HIGHSCALE^2)-(4 v^2 QQ3[2,3,2,3] VV[c,b,c,s])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]Q3[2,1] VV[c,d,c,b])/(3 HIGHSCALE^2)-(2 v^2 QQ3[2,1,3,3] VV[c,d,c,b])/(3 HIGHSCALE^2)-(2 v^2 QQ3[1,3,2,1] VV[c,d,c,d])/(3 HIGHSCALE^2)-(2 v^2 QQ3[2,1,2,3] VV[c,d,c,s])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]Q3[2,2] VV[c,s,c,b])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]Q3[3,3] VV[c,s,c,b])/(3 HIGHSCALE^2)-(2 v^2 QQ3[2,2,3,3] VV[c,s,c,b])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]Q3[1,3] VV[c,s,c,d])/(3 HIGHSCALE^2)-(2 v^2 QQ3[1,3,2,2] VV[c,s,c,d])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]Q3[2,3] VV[c,s,c,s])/(3 HIGHSCALE^2)-(2 v^2 QQ3[2,2,2,3] VV[c,s,c,s])/(3 HIGHSCALE^2);


MatchCBS1[c][3]=(v^2 \[CurlyPhi]Q1[2,3])/(24 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3])/(24 HIGHSCALE^2)-(v^2 QU1[2,3,2,2])/(24 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,3] VV[c,b,c,b])/(36 HIGHSCALE^2)+(v^2 QQ1[2,3,3,3] VV[c,b,c,b])/(24 HIGHSCALE^2)-(v^2 QQ3[2,3,3,3] VV[c,b,c,b])/(72 HIGHSCALE^2)+(v^2 QQ1[1,3,2,3] VV[c,b,c,d])/(24 HIGHSCALE^2)-(v^2 QQ3[1,3,2,3] VV[c,b,c,d])/(72 HIGHSCALE^2)+(v^2 QQ1[2,3,2,3] VV[c,b,c,s])/(12 HIGHSCALE^2)-(v^2 QQ3[2,3,2,3] VV[c,b,c,s])/(36 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,1] VV[c,d,c,b])/(36 HIGHSCALE^2)+(v^2 QQ1[2,3,3,1] VV[c,d,c,b])/(24 HIGHSCALE^2)+(v^2 QQ3[2,1,3,3] VV[c,d,c,b])/(36 HIGHSCALE^2)-(v^2 QQ3[2,3,3,1] VV[c,d,c,b])/(24 HIGHSCALE^2)+(v^2 QQ1[1,1,2,3] VV[c,d,c,d])/(24 HIGHSCALE^2)-(v^2 QQ3[1,1,2,3] VV[c,d,c,d])/(24 HIGHSCALE^2)+(v^2 QQ3[1,3,2,1] VV[c,d,c,d])/(36 HIGHSCALE^2)+(v^2 QQ1[2,1,2,3] VV[c,d,c,s])/(24 HIGHSCALE^2)-(v^2 QQ3[2,1,2,3] VV[c,d,c,s])/(72 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,2] VV[c,s,c,b])/(36 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[3,3] VV[c,s,c,b])/(36 HIGHSCALE^2)+(v^2 QQ1[2,3,3,2] VV[c,s,c,b])/(24 HIGHSCALE^2)+(v^2 QQ3[2,2,3,3] VV[c,s,c,b])/(36 HIGHSCALE^2)-(v^2 QQ3[2,3,3,2] VV[c,s,c,b])/(24 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[1,3] VV[c,s,c,d])/(36 HIGHSCALE^2)+(v^2 QQ1[1,2,2,3] VV[c,s,c,d])/(24 HIGHSCALE^2)-(v^2 QQ3[1,2,2,3] VV[c,s,c,d])/(24 HIGHSCALE^2)+(v^2 QQ3[1,3,2,2] VV[c,s,c,d])/(36 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,3] VV[c,s,c,s])/(36 HIGHSCALE^2)+(v^2 QQ1[2,2,2,3] VV[c,s,c,s])/(24 HIGHSCALE^2)-(v^2 QQ3[2,2,2,3] VV[c,s,c,s])/(72 HIGHSCALE^2);


MatchCBS1[c][4]=-((v^2 QU8[2,3,2,2])/(24 HIGHSCALE^2))-(v^2 \[CurlyPhi]Q3[2,3] VV[c,b,c,b])/(6 HIGHSCALE^2)+(v^2 QQ3[2,3,3,3] VV[c,b,c,b])/(6 HIGHSCALE^2)+(v^2 QQ3[1,3,2,3] VV[c,b,c,d])/(6 HIGHSCALE^2)+(v^2 QQ3[2,3,2,3] VV[c,b,c,s])/(3 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,1] VV[c,d,c,b])/(6 HIGHSCALE^2)+(v^2 QQ3[2,1,3,3] VV[c,d,c,b])/(6 HIGHSCALE^2)+(v^2 QQ3[1,3,2,1] VV[c,d,c,d])/(6 HIGHSCALE^2)+(v^2 QQ3[2,1,2,3] VV[c,d,c,s])/(6 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,2] VV[c,s,c,b])/(6 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[3,3] VV[c,s,c,b])/(6 HIGHSCALE^2)+(v^2 QQ3[2,2,3,3] VV[c,s,c,b])/(6 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[1,3] VV[c,s,c,d])/(6 HIGHSCALE^2)+(v^2 QQ3[1,3,2,2] VV[c,s,c,d])/(6 HIGHSCALE^2)-(v^2 \[CurlyPhi]Q3[2,3] VV[c,s,c,s])/(6 HIGHSCALE^2)+(v^2 QQ3[2,2,2,3] VV[c,s,c,s])/(6 HIGHSCALE^2);


MatchCBS1[c][5]=-((4 v^2 CC[VCKM[c,s]] \[CurlyPhi]UD[2,3])/(9 HIGHSCALE^2))-(v^2 QUQD1[2,2,2,3])/(6 HIGHSCALE^2)-(v^2 QUQD1[2,2,3,3] VV[c,s,c,b])/(36 HIGHSCALE^2)-(v^2 QUQD8[2,2,3,3] VV[c,s,c,b])/(27 HIGHSCALE^2)-(v^2 QUQD1[2,2,1,3] VV[c,s,c,d])/(36 HIGHSCALE^2)-(v^2 QUQD8[2,2,1,3] VV[c,s,c,d])/(27 HIGHSCALE^2)-(v^2 QUQD1[2,2,2,3] VV[c,s,c,s])/(36 HIGHSCALE^2)-(v^2 QUQD8[2,2,2,3] VV[c,s,c,s])/(27 HIGHSCALE^2)-(v^2 QUQD1[3,2,3,3] VV[t,s,c,b])/(36 HIGHSCALE^2)-(v^2 QUQD8[3,2,3,3] VV[t,s,c,b])/(27 HIGHSCALE^2)-(v^2 QUQD1[3,2,1,3] VV[t,s,c,d])/(36 HIGHSCALE^2)-(v^2 QUQD8[3,2,1,3] VV[t,s,c,d])/(27 HIGHSCALE^2)-(v^2 QUQD1[3,2,2,3] VV[t,s,c,s])/(36 HIGHSCALE^2)-(v^2 QUQD8[3,2,2,3] VV[t,s,c,s])/(27 HIGHSCALE^2)-(v^2 QUQD1[1,2,3,3] VV[u,s,c,b])/(36 HIGHSCALE^2)-(v^2 QUQD8[1,2,3,3] VV[u,s,c,b])/(27 HIGHSCALE^2)-(v^2 QUQD1[1,2,1,3] VV[u,s,c,d])/(36 HIGHSCALE^2)-(v^2 QUQD8[1,2,1,3] VV[u,s,c,d])/(27 HIGHSCALE^2)-(v^2 QUQD1[1,2,2,3] VV[u,s,c,s])/(36 HIGHSCALE^2)-(v^2 QUQD8[1,2,2,3] VV[u,s,c,s])/(27 HIGHSCALE^2);


MatchCBS1[c][6]=-((8 v^2 CC[VCKM[c,s]] \[CurlyPhi]UD[2,3])/(3 HIGHSCALE^2))-(v^2 QUQD8[2,2,2,3])/(6 HIGHSCALE^2)-(v^2 QUQD1[2,2,3,3] VV[c,s,c,b])/(6 HIGHSCALE^2)+(v^2 QUQD8[2,2,3,3] VV[c,s,c,b])/(36 HIGHSCALE^2)-(v^2 QUQD1[2,2,1,3] VV[c,s,c,d])/(6 HIGHSCALE^2)+(v^2 QUQD8[2,2,1,3] VV[c,s,c,d])/(36 HIGHSCALE^2)-(v^2 QUQD1[2,2,2,3] VV[c,s,c,s])/(6 HIGHSCALE^2)+(v^2 QUQD8[2,2,2,3] VV[c,s,c,s])/(36 HIGHSCALE^2)-(v^2 QUQD1[3,2,3,3] VV[t,s,c,b])/(6 HIGHSCALE^2)+(v^2 QUQD8[3,2,3,3] VV[t,s,c,b])/(36 HIGHSCALE^2)-(v^2 QUQD1[3,2,1,3] VV[t,s,c,d])/(6 HIGHSCALE^2)+(v^2 QUQD8[3,2,1,3] VV[t,s,c,d])/(36 HIGHSCALE^2)-(v^2 QUQD1[3,2,2,3] VV[t,s,c,s])/(6 HIGHSCALE^2)+(v^2 QUQD8[3,2,2,3] VV[t,s,c,s])/(36 HIGHSCALE^2)-(v^2 QUQD1[1,2,3,3] VV[u,s,c,b])/(6 HIGHSCALE^2)+(v^2 QUQD8[1,2,3,3] VV[u,s,c,b])/(36 HIGHSCALE^2)-(v^2 QUQD1[1,2,1,3] VV[u,s,c,d])/(6 HIGHSCALE^2)+(v^2 QUQD8[1,2,1,3] VV[u,s,c,d])/(36 HIGHSCALE^2)-(v^2 QUQD1[1,2,2,3] VV[u,s,c,s])/(6 HIGHSCALE^2)+(v^2 QUQD8[1,2,2,3] VV[u,s,c,s])/(36 HIGHSCALE^2);


MatchCBS1[c][7]=(v^2 CC[VCKM[c,s]] \[CurlyPhi]UD[2,3])/(9 HIGHSCALE^2)+(v^2 QUQD1[2,2,2,3])/(6 HIGHSCALE^2)+(7 v^2 QUQD1[2,2,3,3] VV[c,s,c,b])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[2,2,3,3] VV[c,s,c,b])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[2,2,1,3] VV[c,s,c,d])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[2,2,1,3] VV[c,s,c,d])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[2,2,2,3] VV[c,s,c,s])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[2,2,2,3] VV[c,s,c,s])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[3,2,3,3] VV[t,s,c,b])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[3,2,3,3] VV[t,s,c,b])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[3,2,1,3] VV[t,s,c,d])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[3,2,1,3] VV[t,s,c,d])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[3,2,2,3] VV[t,s,c,s])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[3,2,2,3] VV[t,s,c,s])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[1,2,3,3] VV[u,s,c,b])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[1,2,3,3] VV[u,s,c,b])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[1,2,1,3] VV[u,s,c,d])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[1,2,1,3] VV[u,s,c,d])/(108 HIGHSCALE^2)+(7 v^2 QUQD1[1,2,2,3] VV[u,s,c,s])/(144 HIGHSCALE^2)+(7 v^2 QUQD8[1,2,2,3] VV[u,s,c,s])/(108 HIGHSCALE^2);


MatchCBS1[c][8]=(2 v^2 CC[VCKM[c,s]] \[CurlyPhi]UD[2,3])/(3 HIGHSCALE^2)+(v^2 QUQD8[2,2,2,3])/(6 HIGHSCALE^2)+(7 v^2 QUQD1[2,2,3,3] VV[c,s,c,b])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[2,2,3,3] VV[c,s,c,b])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[2,2,1,3] VV[c,s,c,d])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[2,2,1,3] VV[c,s,c,d])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[2,2,2,3] VV[c,s,c,s])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[2,2,2,3] VV[c,s,c,s])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[3,2,3,3] VV[t,s,c,b])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[3,2,3,3] VV[t,s,c,b])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[3,2,1,3] VV[t,s,c,d])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[3,2,1,3] VV[t,s,c,d])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[3,2,2,3] VV[t,s,c,s])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[3,2,2,3] VV[t,s,c,s])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[1,2,3,3] VV[u,s,c,b])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[1,2,3,3] VV[u,s,c,b])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[1,2,1,3] VV[u,s,c,d])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[1,2,1,3] VV[u,s,c,d])/(144 HIGHSCALE^2)+(7 v^2 QUQD1[1,2,2,3] VV[u,s,c,s])/(24 HIGHSCALE^2)-(7 v^2 QUQD8[1,2,2,3] VV[u,s,c,s])/(144 HIGHSCALE^2);


MatchCBS1[c][9]=(v^2 CC[VCKM[c,s]] \[CurlyPhi]UD[2,3])/(144 HIGHSCALE^2)+(v^2 QUQD1[2,2,2,3])/(96 HIGHSCALE^2)+(v^2 QUQD1[2,2,3,3] VV[c,s,c,b])/(576 HIGHSCALE^2)+(v^2 QUQD8[2,2,3,3] VV[c,s,c,b])/(432 HIGHSCALE^2)+(v^2 QUQD1[2,2,1,3] VV[c,s,c,d])/(576 HIGHSCALE^2)+(v^2 QUQD8[2,2,1,3] VV[c,s,c,d])/(432 HIGHSCALE^2)+(v^2 QUQD1[2,2,2,3] VV[c,s,c,s])/(576 HIGHSCALE^2)+(v^2 QUQD8[2,2,2,3] VV[c,s,c,s])/(432 HIGHSCALE^2)+(v^2 QUQD1[3,2,3,3] VV[t,s,c,b])/(576 HIGHSCALE^2)+(v^2 QUQD8[3,2,3,3] VV[t,s,c,b])/(432 HIGHSCALE^2)+(v^2 QUQD1[3,2,1,3] VV[t,s,c,d])/(576 HIGHSCALE^2)+(v^2 QUQD8[3,2,1,3] VV[t,s,c,d])/(432 HIGHSCALE^2)+(v^2 QUQD1[3,2,2,3] VV[t,s,c,s])/(576 HIGHSCALE^2)+(v^2 QUQD8[3,2,2,3] VV[t,s,c,s])/(432 HIGHSCALE^2)+(v^2 QUQD1[1,2,3,3] VV[u,s,c,b])/(576 HIGHSCALE^2)+(v^2 QUQD8[1,2,3,3] VV[u,s,c,b])/(432 HIGHSCALE^2)+(v^2 QUQD1[1,2,1,3] VV[u,s,c,d])/(576 HIGHSCALE^2)+(v^2 QUQD8[1,2,1,3] VV[u,s,c,d])/(432 HIGHSCALE^2)+(v^2 QUQD1[1,2,2,3] VV[u,s,c,s])/(576 HIGHSCALE^2)+(v^2 QUQD8[1,2,2,3] VV[u,s,c,s])/(432 HIGHSCALE^2);


MatchCBS1[c][10]=(v^2 CC[VCKM[c,s]] \[CurlyPhi]UD[2,3])/(24 HIGHSCALE^2)+(v^2 QUQD8[2,2,2,3])/(96 HIGHSCALE^2)+(v^2 QUQD1[2,2,3,3] VV[c,s,c,b])/(96 HIGHSCALE^2)-(v^2 QUQD8[2,2,3,3] VV[c,s,c,b])/(576 HIGHSCALE^2)+(v^2 QUQD1[2,2,1,3] VV[c,s,c,d])/(96 HIGHSCALE^2)-(v^2 QUQD8[2,2,1,3] VV[c,s,c,d])/(576 HIGHSCALE^2)+(v^2 QUQD1[2,2,2,3] VV[c,s,c,s])/(96 HIGHSCALE^2)-(v^2 QUQD8[2,2,2,3] VV[c,s,c,s])/(576 HIGHSCALE^2)+(v^2 QUQD1[3,2,3,3] VV[t,s,c,b])/(96 HIGHSCALE^2)-(v^2 QUQD8[3,2,3,3] VV[t,s,c,b])/(576 HIGHSCALE^2)+(v^2 QUQD1[3,2,1,3] VV[t,s,c,d])/(96 HIGHSCALE^2)-(v^2 QUQD8[3,2,1,3] VV[t,s,c,d])/(576 HIGHSCALE^2)+(v^2 QUQD1[3,2,2,3] VV[t,s,c,s])/(96 HIGHSCALE^2)-(v^2 QUQD8[3,2,2,3] VV[t,s,c,s])/(576 HIGHSCALE^2)+(v^2 QUQD1[1,2,3,3] VV[u,s,c,b])/(96 HIGHSCALE^2)-(v^2 QUQD8[1,2,3,3] VV[u,s,c,b])/(576 HIGHSCALE^2)+(v^2 QUQD1[1,2,1,3] VV[u,s,c,d])/(96 HIGHSCALE^2)-(v^2 QUQD8[1,2,1,3] VV[u,s,c,d])/(576 HIGHSCALE^2)+(v^2 QUQD1[1,2,2,3] VV[u,s,c,s])/(96 HIGHSCALE^2)-(v^2 QUQD8[1,2,2,3] VV[u,s,c,s])/(576 HIGHSCALE^2);


MatchCBS1[s][1]=(v^2 \[CurlyPhi]Q1[2,3])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3])/(6 HIGHSCALE^2)+(2 v^2 QD1[2,3,2,2])/(3 HIGHSCALE^2)-(v^2 QD8[2,3,2,2])/(9 HIGHSCALE^2)-(v^2 QQ1[2,2,2,3])/(6 HIGHSCALE^2)-(v^2 QQ3[2,2,2,3])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q1[2,3] Sin[\[Theta]W]^2)/(3 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3] Sin[\[Theta]W]^2)/(3 HIGHSCALE^2);


MatchCBS1[s][3]=-((v^2 \[CurlyPhi]Q1[2,3])/(24 HIGHSCALE^2))-(v^2 \[CurlyPhi]Q3[2,3])/(24 HIGHSCALE^2)-(v^2 QD1[2,3,2,2])/(24 HIGHSCALE^2)+(v^2 QD8[2,3,2,2])/(144 HIGHSCALE^2)+(v^2 QQ1[2,2,2,3])/(24 HIGHSCALE^2)+(v^2 QQ3[2,2,2,3])/(24 HIGHSCALE^2);


MatchCBS1[s][5]=-((2 v^2 QD8[2,2,2,3])/(3 HIGHSCALE^2));


MatchCBS1[s][7]=(v^2 QD8[2,2,2,3])/(6 HIGHSCALE^2);


MatchCBS1[s][9]=(v^2 QD8[2,2,2,3])/(96 HIGHSCALE^2);


MatchCBS1[b][1]=(v^2 \[CurlyPhi]Q1[2,3])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3])/(6 HIGHSCALE^2)+(2 v^2 QD1[2,3,3,3])/(3 HIGHSCALE^2)-(v^2 QD8[2,3,3,3])/(9 HIGHSCALE^2)-(v^2 QQ1[2,3,3,3])/(6 HIGHSCALE^2)-(v^2 QQ3[2,3,3,3])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q1[2,3] Sin[\[Theta]W]^2)/(3 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3] Sin[\[Theta]W]^2)/(3 HIGHSCALE^2);


MatchCBS1[b][3]=-((v^2 \[CurlyPhi]Q1[2,3])/(24 HIGHSCALE^2))-(v^2 \[CurlyPhi]Q3[2,3])/(24 HIGHSCALE^2)-(v^2 QD1[2,3,3,3])/(24 HIGHSCALE^2)+(v^2 QD8[2,3,3,3])/(144 HIGHSCALE^2)+(v^2 QQ1[2,3,3,3])/(24 HIGHSCALE^2)+(v^2 QQ3[2,3,3,3])/(24 HIGHSCALE^2);


MatchCBS1[b][5]=-((2 v^2 QD8[2,3,3,3])/(3 HIGHSCALE^2))-(mb mW v^2 D\[CurlyPhi][2,3] Sin[\[Theta]W])/(Sqrt[2] e HIGHSCALE^2 mh^2);


MatchCBS1[b][7]=(v^2 QD8[2,3,3,3])/(6 HIGHSCALE^2);


MatchCBS1[b][9]=(v^2 QD8[2,3,3,3])/(96 HIGHSCALE^2);


MatchCBS1[M][7]=(mW v^2 \[Alpha]S Cos[\[Theta]W] DB[2,3] Sin[\[Theta]W])/(Sqrt[2] HIGHSCALE^2 mb \[Alpha]EM)-(mW v^2 \[Alpha]S DW[2,3] Sin[\[Theta]W]^2)/(Sqrt[2] HIGHSCALE^2 mb \[Alpha]EM);


MatchCBS1[M][8]=(mW v^2 \[Alpha]S DG[2,3] Sin[\[Theta]W])/(Sqrt[2] HIGHSCALE^2 mb Sqrt[\[Alpha]EM \[Alpha]S]);


MatchCBS1[e][1]=(v^2 \[CurlyPhi]Q1[2,3])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3])/(6 HIGHSCALE^2)-(v^2 LQ1[1,1,2,3])/(6 HIGHSCALE^2)-(v^2 LQ3[1,1,2,3])/(6 HIGHSCALE^2)+(2 v^2 QE[2,3,1,1])/(3 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q1[2,3] Sin[\[Theta]W]^2)/HIGHSCALE^2+(v^2 \[CurlyPhi]Q3[2,3] Sin[\[Theta]W]^2)/HIGHSCALE^2;


MatchCBS1[e][3]=-((v^2 \[CurlyPhi]Q1[2,3])/(24 HIGHSCALE^2))-(v^2 \[CurlyPhi]Q3[2,3])/(24 HIGHSCALE^2)+(v^2 LQ1[1,1,2,3])/(24 HIGHSCALE^2)+(v^2 LQ3[1,1,2,3])/(24 HIGHSCALE^2)-(v^2 QE[2,3,1,1])/(24 HIGHSCALE^2);


MatchCBS1[e][5]=(2 v^2 CC[LEDQ[1,1,3,2]])/(3 HIGHSCALE^2);


MatchCBS1[e][7]=-((v^2 CC[LEDQ[1,1,3,2]])/(6 HIGHSCALE^2));


MatchCBS1[e][9]=-((v^2 CC[LEDQ[1,1,3,2]])/(96 HIGHSCALE^2));


MatchCBS1[\[Mu]][1]=(v^2 \[CurlyPhi]Q1[2,3])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3])/(6 HIGHSCALE^2)-(v^2 LQ1[2,2,2,3])/(6 HIGHSCALE^2)-(v^2 LQ3[2,2,2,3])/(6 HIGHSCALE^2)+(2 v^2 QE[2,3,2,2])/(3 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q1[2,3] Sin[\[Theta]W]^2)/HIGHSCALE^2+(v^2 \[CurlyPhi]Q3[2,3] Sin[\[Theta]W]^2)/HIGHSCALE^2;


MatchCBS1[\[Mu]][3]=-((v^2 \[CurlyPhi]Q1[2,3])/(24 HIGHSCALE^2))-(v^2 \[CurlyPhi]Q3[2,3])/(24 HIGHSCALE^2)+(v^2 LQ1[2,2,2,3])/(24 HIGHSCALE^2)+(v^2 LQ3[2,2,2,3])/(24 HIGHSCALE^2)-(v^2 QE[2,3,2,2])/(24 HIGHSCALE^2);


MatchCBS1[\[Mu]][5]=(2 v^2 CC[LEDQ[2,2,3,2]])/(3 HIGHSCALE^2);


MatchCBS1[\[Mu]][7]=-((v^2 CC[LEDQ[2,2,3,2]])/(6 HIGHSCALE^2));


MatchCBS1[\[Mu]][9]=-((v^2 CC[LEDQ[2,2,3,2]])/(96 HIGHSCALE^2));


MatchCBS1[\[Tau]][1]=(v^2 \[CurlyPhi]Q1[2,3])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q3[2,3])/(6 HIGHSCALE^2)-(v^2 LQ1[3,3,2,3])/(6 HIGHSCALE^2)-(v^2 LQ3[3,3,2,3])/(6 HIGHSCALE^2)+(2 v^2 QE[2,3,3,3])/(3 HIGHSCALE^2)+(v^2 \[CurlyPhi]Q1[2,3] Sin[\[Theta]W]^2)/HIGHSCALE^2+(v^2 \[CurlyPhi]Q3[2,3] Sin[\[Theta]W]^2)/HIGHSCALE^2;


MatchCBS1[\[Tau]][3]=-((v^2 \[CurlyPhi]Q1[2,3])/(24 HIGHSCALE^2))-(v^2 \[CurlyPhi]Q3[2,3])/(24 HIGHSCALE^2)+(v^2 LQ1[3,3,2,3])/(24 HIGHSCALE^2)+(v^2 LQ3[3,3,2,3])/(24 HIGHSCALE^2)-(v^2 QE[2,3,3,3])/(24 HIGHSCALE^2);


MatchCBS1[\[Tau]][5]=(2 v^2 CC[LEDQ[3,3,3,2]])/(3 HIGHSCALE^2);


MatchCBS1[\[Tau]][7]=-((v^2 CC[LEDQ[3,3,3,2]])/(6 HIGHSCALE^2));


MatchCBS1[\[Tau]][9]=-((v^2 CC[LEDQ[3,3,3,2]])/(96 HIGHSCALE^2));


MatchCBS1p[u][1]=-((v^2 UD1[1,1,2,3])/(6 HIGHSCALE^2))+(2 v^2 \[CurlyPhi]D[2,3])/(3 HIGHSCALE^2)-(2 v^2 \[CurlyPhi]D[2,3] Sin[\[Theta]W]^2)/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,d]] QD1[3,1,2,3] VCKM[u,b])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,s]] QD1[3,2,2,3] VCKM[u,b])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,b]] QD1[3,3,2,3] VCKM[u,b])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,d]] QD1[1,1,2,3] VCKM[u,d])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,s]] QD1[1,2,2,3] VCKM[u,d])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,b]] QD1[1,3,2,3] VCKM[u,d])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,d]] QD1[2,1,2,3] VCKM[u,s])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,s]] QD1[2,2,2,3] VCKM[u,s])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,b]] QD1[2,3,2,3] VCKM[u,s])/(3 HIGHSCALE^2);


MatchCBS1p[u][2]=-((v^2 UD8[1,1,2,3])/(6 HIGHSCALE^2))+(2 v^2 CC[VCKM[u,d]] QD8[3,1,2,3] VCKM[u,b])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,s]] QD8[3,2,2,3] VCKM[u,b])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,b]] QD8[3,3,2,3] VCKM[u,b])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,d]] QD8[1,1,2,3] VCKM[u,d])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,s]] QD8[1,2,2,3] VCKM[u,d])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,b]] QD8[1,3,2,3] VCKM[u,d])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,d]] QD8[2,1,2,3] VCKM[u,s])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,s]] QD8[2,2,2,3] VCKM[u,s])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[u,b]] QD8[2,3,2,3] VCKM[u,s])/(3 HIGHSCALE^2);


MatchCBS1p[u][3]=(v^2 UD1[1,1,2,3])/(24 HIGHSCALE^2)-(v^2 \[CurlyPhi]D[2,3])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,d]] QD1[3,1,2,3] VCKM[u,b])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,s]] QD1[3,2,2,3] VCKM[u,b])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,b]] QD1[3,3,2,3] VCKM[u,b])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,d]] QD1[1,1,2,3] VCKM[u,d])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,s]] QD1[1,2,2,3] VCKM[u,d])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,b]] QD1[1,3,2,3] VCKM[u,d])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,d]] QD1[2,1,2,3] VCKM[u,s])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,s]] QD1[2,2,2,3] VCKM[u,s])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,b]] QD1[2,3,2,3] VCKM[u,s])/(24 HIGHSCALE^2);


MatchCBS1p[u][4]=(v^2 UD8[1,1,2,3])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,d]] QD8[3,1,2,3] VCKM[u,b])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,s]] QD8[3,2,2,3] VCKM[u,b])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,b]] QD8[3,3,2,3] VCKM[u,b])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,d]] QD8[1,1,2,3] VCKM[u,d])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,s]] QD8[1,2,2,3] VCKM[u,d])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,b]] QD8[1,3,2,3] VCKM[u,d])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,d]] QD8[2,1,2,3] VCKM[u,s])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,s]] QD8[2,2,2,3] VCKM[u,s])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[u,b]] QD8[2,3,2,3] VCKM[u,s])/(24 HIGHSCALE^2);


MatchCBS1p[u][5]=-((v^2 CC[QUQD1[1,1,3,2]])/(6 HIGHSCALE^2))-(v^2 CC[QUQD1[2,1,3,2]] CC[VCKM[u,b]] VCKM[c,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[2,1,3,2]] CC[VCKM[u,b]] VCKM[c,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[2,1,1,2]] CC[VCKM[u,d]] VCKM[c,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[2,1,1,2]] CC[VCKM[u,d]] VCKM[c,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[2,1,2,2]] CC[VCKM[u,s]] VCKM[c,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[2,1,2,2]] CC[VCKM[u,s]] VCKM[c,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[3,1,3,2]] CC[VCKM[u,b]] VCKM[t,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[3,1,3,2]] CC[VCKM[u,b]] VCKM[t,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[3,1,1,2]] CC[VCKM[u,d]] VCKM[t,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[3,1,1,2]] CC[VCKM[u,d]] VCKM[t,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[3,1,2,2]] CC[VCKM[u,s]] VCKM[t,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[3,1,2,2]] CC[VCKM[u,s]] VCKM[t,b])/(27 HIGHSCALE^2)-(4 v^2 CC[\[CurlyPhi]UD[1,2]] VCKM[u,b])/(9 HIGHSCALE^2)-(v^2 CC[QUQD1[1,1,3,2]] CC[VCKM[u,b]] VCKM[u,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[1,1,3,2]] CC[VCKM[u,b]] VCKM[u,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[1,1,1,2]] CC[VCKM[u,d]] VCKM[u,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[1,1,1,2]] CC[VCKM[u,d]] VCKM[u,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[1,1,2,2]] CC[VCKM[u,s]] VCKM[u,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[1,1,2,2]] CC[VCKM[u,s]] VCKM[u,b])/(27 HIGHSCALE^2);


MatchCBS1p[u][6]=-((v^2 CC[QUQD8[1,1,3,2]])/(6 HIGHSCALE^2))-(v^2 CC[QUQD1[2,1,3,2]] CC[VCKM[u,b]] VCKM[c,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[2,1,3,2]] CC[VCKM[u,b]] VCKM[c,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[2,1,1,2]] CC[VCKM[u,d]] VCKM[c,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[2,1,1,2]] CC[VCKM[u,d]] VCKM[c,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[2,1,2,2]] CC[VCKM[u,s]] VCKM[c,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[2,1,2,2]] CC[VCKM[u,s]] VCKM[c,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[3,1,3,2]] CC[VCKM[u,b]] VCKM[t,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[3,1,3,2]] CC[VCKM[u,b]] VCKM[t,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[3,1,1,2]] CC[VCKM[u,d]] VCKM[t,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[3,1,1,2]] CC[VCKM[u,d]] VCKM[t,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[3,1,2,2]] CC[VCKM[u,s]] VCKM[t,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[3,1,2,2]] CC[VCKM[u,s]] VCKM[t,b])/(36 HIGHSCALE^2)-(8 v^2 CC[\[CurlyPhi]UD[1,2]] VCKM[u,b])/(3 HIGHSCALE^2)-(v^2 CC[QUQD1[1,1,3,2]] CC[VCKM[u,b]] VCKM[u,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[1,1,3,2]] CC[VCKM[u,b]] VCKM[u,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[1,1,1,2]] CC[VCKM[u,d]] VCKM[u,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[1,1,1,2]] CC[VCKM[u,d]] VCKM[u,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[1,1,2,2]] CC[VCKM[u,s]] VCKM[u,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[1,1,2,2]] CC[VCKM[u,s]] VCKM[u,b])/(36 HIGHSCALE^2);


MatchCBS1p[u][7]=(v^2 CC[QUQD1[1,1,3,2]])/(6 HIGHSCALE^2)+(7 v^2 CC[QUQD1[2,1,3,2]] CC[VCKM[u,b]] VCKM[c,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[2,1,3,2]] CC[VCKM[u,b]] VCKM[c,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[2,1,1,2]] CC[VCKM[u,d]] VCKM[c,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[2,1,1,2]] CC[VCKM[u,d]] VCKM[c,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[2,1,2,2]] CC[VCKM[u,s]] VCKM[c,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[2,1,2,2]] CC[VCKM[u,s]] VCKM[c,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[3,1,3,2]] CC[VCKM[u,b]] VCKM[t,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[3,1,3,2]] CC[VCKM[u,b]] VCKM[t,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[3,1,1,2]] CC[VCKM[u,d]] VCKM[t,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[3,1,1,2]] CC[VCKM[u,d]] VCKM[t,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[3,1,2,2]] CC[VCKM[u,s]] VCKM[t,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[3,1,2,2]] CC[VCKM[u,s]] VCKM[t,b])/(108 HIGHSCALE^2)+(v^2 CC[\[CurlyPhi]UD[1,2]] VCKM[u,b])/(9 HIGHSCALE^2)+(7 v^2 CC[QUQD1[1,1,3,2]] CC[VCKM[u,b]] VCKM[u,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[1,1,3,2]] CC[VCKM[u,b]] VCKM[u,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[1,1,1,2]] CC[VCKM[u,d]] VCKM[u,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[1,1,1,2]] CC[VCKM[u,d]] VCKM[u,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[1,1,2,2]] CC[VCKM[u,s]] VCKM[u,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[1,1,2,2]] CC[VCKM[u,s]] VCKM[u,b])/(108 HIGHSCALE^2);


MatchCBS1p[u][8]=(v^2 CC[QUQD8[1,1,3,2]])/(6 HIGHSCALE^2)+(7 v^2 CC[QUQD1[2,1,3,2]] CC[VCKM[u,b]] VCKM[c,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[2,1,3,2]] CC[VCKM[u,b]] VCKM[c,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[2,1,1,2]] CC[VCKM[u,d]] VCKM[c,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[2,1,1,2]] CC[VCKM[u,d]] VCKM[c,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[2,1,2,2]] CC[VCKM[u,s]] VCKM[c,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[2,1,2,2]] CC[VCKM[u,s]] VCKM[c,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[3,1,3,2]] CC[VCKM[u,b]] VCKM[t,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[3,1,3,2]] CC[VCKM[u,b]] VCKM[t,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[3,1,1,2]] CC[VCKM[u,d]] VCKM[t,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[3,1,1,2]] CC[VCKM[u,d]] VCKM[t,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[3,1,2,2]] CC[VCKM[u,s]] VCKM[t,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[3,1,2,2]] CC[VCKM[u,s]] VCKM[t,b])/(144 HIGHSCALE^2)+(2 v^2 CC[\[CurlyPhi]UD[1,2]] VCKM[u,b])/(3 HIGHSCALE^2)+(7 v^2 CC[QUQD1[1,1,3,2]] CC[VCKM[u,b]] VCKM[u,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[1,1,3,2]] CC[VCKM[u,b]] VCKM[u,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[1,1,1,2]] CC[VCKM[u,d]] VCKM[u,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[1,1,1,2]] CC[VCKM[u,d]] VCKM[u,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[1,1,2,2]] CC[VCKM[u,s]] VCKM[u,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[1,1,2,2]] CC[VCKM[u,s]] VCKM[u,b])/(144 HIGHSCALE^2);


MatchCBS1p[u][9]=(v^2 CC[QUQD1[1,1,3,2]])/(96 HIGHSCALE^2)+(v^2 CC[QUQD1[2,1,3,2]] CC[VCKM[u,b]] VCKM[c,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[2,1,3,2]] CC[VCKM[u,b]] VCKM[c,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[2,1,1,2]] CC[VCKM[u,d]] VCKM[c,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[2,1,1,2]] CC[VCKM[u,d]] VCKM[c,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[2,1,2,2]] CC[VCKM[u,s]] VCKM[c,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[2,1,2,2]] CC[VCKM[u,s]] VCKM[c,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[3,1,3,2]] CC[VCKM[u,b]] VCKM[t,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[3,1,3,2]] CC[VCKM[u,b]] VCKM[t,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[3,1,1,2]] CC[VCKM[u,d]] VCKM[t,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[3,1,1,2]] CC[VCKM[u,d]] VCKM[t,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[3,1,2,2]] CC[VCKM[u,s]] VCKM[t,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[3,1,2,2]] CC[VCKM[u,s]] VCKM[t,b])/(432 HIGHSCALE^2)+(v^2 CC[\[CurlyPhi]UD[1,2]] VCKM[u,b])/(144 HIGHSCALE^2)+(v^2 CC[QUQD1[1,1,3,2]] CC[VCKM[u,b]] VCKM[u,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[1,1,3,2]] CC[VCKM[u,b]] VCKM[u,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[1,1,1,2]] CC[VCKM[u,d]] VCKM[u,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[1,1,1,2]] CC[VCKM[u,d]] VCKM[u,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[1,1,2,2]] CC[VCKM[u,s]] VCKM[u,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[1,1,2,2]] CC[VCKM[u,s]] VCKM[u,b])/(432 HIGHSCALE^2);


MatchCBS1p[u][10]=(v^2 CC[QUQD8[1,1,3,2]])/(96 HIGHSCALE^2)+(v^2 CC[QUQD1[2,1,3,2]] CC[VCKM[u,b]] VCKM[c,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[2,1,3,2]] CC[VCKM[u,b]] VCKM[c,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[2,1,1,2]] CC[VCKM[u,d]] VCKM[c,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[2,1,1,2]] CC[VCKM[u,d]] VCKM[c,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[2,1,2,2]] CC[VCKM[u,s]] VCKM[c,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[2,1,2,2]] CC[VCKM[u,s]] VCKM[c,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[3,1,3,2]] CC[VCKM[u,b]] VCKM[t,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[3,1,3,2]] CC[VCKM[u,b]] VCKM[t,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[3,1,1,2]] CC[VCKM[u,d]] VCKM[t,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[3,1,1,2]] CC[VCKM[u,d]] VCKM[t,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[3,1,2,2]] CC[VCKM[u,s]] VCKM[t,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[3,1,2,2]] CC[VCKM[u,s]] VCKM[t,b])/(576 HIGHSCALE^2)+(v^2 CC[\[CurlyPhi]UD[1,2]] VCKM[u,b])/(24 HIGHSCALE^2)+(v^2 CC[QUQD1[1,1,3,2]] CC[VCKM[u,b]] VCKM[u,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[1,1,3,2]] CC[VCKM[u,b]] VCKM[u,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[1,1,1,2]] CC[VCKM[u,d]] VCKM[u,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[1,1,1,2]] CC[VCKM[u,d]] VCKM[u,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[1,1,2,2]] CC[VCKM[u,s]] VCKM[u,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[1,1,2,2]] CC[VCKM[u,s]] VCKM[u,b])/(576 HIGHSCALE^2);


MatchCBS1p[d][1]=-((v^2 DD[1,1,2,3])/(6 HIGHSCALE^2))-(v^2 DD[1,3,2,1])/(6 HIGHSCALE^2)+(2 v^2 QD1[1,1,2,3])/(3 HIGHSCALE^2)-(2 v^2 \[CurlyPhi]D[2,3])/(3 HIGHSCALE^2)+(v^2 Sin[\[Theta]W]^2 \[CurlyPhi]D[2,3])/(3 HIGHSCALE^2);


MatchCBS1p[d][2]=-((v^2 DD[1,3,2,1])/(9 HIGHSCALE^2))+(2 v^2 QD8[1,1,2,3])/(3 HIGHSCALE^2);


MatchCBS1p[d][3]=(v^2 DD[1,1,2,3])/(24 HIGHSCALE^2)+(v^2 DD[1,3,2,1])/(72 HIGHSCALE^2)-(v^2 QD1[1,1,2,3])/(24 HIGHSCALE^2)+(v^2 \[CurlyPhi]D[2,3])/(24 HIGHSCALE^2);


MatchCBS1p[d][4]=(v^2 DD[1,3,2,1])/(36 HIGHSCALE^2)-(v^2 QD8[1,1,2,3])/(24 HIGHSCALE^2);


MatchCBS1p[d][5]=0;


MatchCBS1p[d][6]=0;


MatchCBS1p[d][7]=(v^2 CC[QUQD1[2,1,3,2]] CC[VCKM[d,b]] VCKM[c,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD8[2,1,3,2]] CC[VCKM[d,b]] VCKM[c,b])/(36 HIGHSCALE^2)+(v^2 CC[QUQD1[2,1,1,2]] CC[VCKM[d,d]] VCKM[c,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD8[2,1,1,2]] CC[VCKM[d,d]] VCKM[c,b])/(36 HIGHSCALE^2)+(v^2 CC[QUQD1[2,1,2,2]] CC[VCKM[d,s]] VCKM[c,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD8[2,1,2,2]] CC[VCKM[d,s]] VCKM[c,b])/(36 HIGHSCALE^2)+(v^2 CC[QUQD1[3,1,3,2]] CC[VCKM[d,b]] VCKM[t,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD8[3,1,3,2]] CC[VCKM[d,b]] VCKM[t,b])/(36 HIGHSCALE^2)+(v^2 CC[QUQD1[3,1,1,2]] CC[VCKM[d,d]] VCKM[t,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD8[3,1,1,2]] CC[VCKM[d,d]] VCKM[t,b])/(36 HIGHSCALE^2)+(v^2 CC[QUQD1[3,1,2,2]] CC[VCKM[d,s]] VCKM[t,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD8[3,1,2,2]] CC[VCKM[d,s]] VCKM[t,b])/(36 HIGHSCALE^2)+(v^2 CC[QUQD1[1,1,3,2]] CC[VCKM[d,b]] VCKM[u,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD8[1,1,3,2]] CC[VCKM[d,b]] VCKM[u,b])/(36 HIGHSCALE^2)+(v^2 CC[QUQD1[1,1,1,2]] CC[VCKM[d,d]] VCKM[u,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD8[1,1,1,2]] CC[VCKM[d,d]] VCKM[u,b])/(36 HIGHSCALE^2)+(v^2 CC[QUQD1[1,1,2,2]] CC[VCKM[d,s]] VCKM[u,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD8[1,1,2,2]] CC[VCKM[d,s]] VCKM[u,b])/(36 HIGHSCALE^2);


MatchCBS1p[d][8]=(v^2 CC[QUQD1[2,1,3,2]] CC[VCKM[d,b]] VCKM[c,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[2,1,3,2]] CC[VCKM[d,b]] VCKM[c,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[2,1,1,2]] CC[VCKM[d,d]] VCKM[c,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[2,1,1,2]] CC[VCKM[d,d]] VCKM[c,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[2,1,2,2]] CC[VCKM[d,s]] VCKM[c,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[2,1,2,2]] CC[VCKM[d,s]] VCKM[c,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[3,1,3,2]] CC[VCKM[d,b]] VCKM[t,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[3,1,3,2]] CC[VCKM[d,b]] VCKM[t,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[3,1,1,2]] CC[VCKM[d,d]] VCKM[t,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[3,1,1,2]] CC[VCKM[d,d]] VCKM[t,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[3,1,2,2]] CC[VCKM[d,s]] VCKM[t,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[3,1,2,2]] CC[VCKM[d,s]] VCKM[t,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[1,1,3,2]] CC[VCKM[d,b]] VCKM[u,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[1,1,3,2]] CC[VCKM[d,b]] VCKM[u,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[1,1,1,2]] CC[VCKM[d,d]] VCKM[u,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[1,1,1,2]] CC[VCKM[d,d]] VCKM[u,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[1,1,2,2]] CC[VCKM[d,s]] VCKM[u,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[1,1,2,2]] CC[VCKM[d,s]] VCKM[u,b])/(48 HIGHSCALE^2);


MatchCBS1p[d][9]=0;


MatchCBS1p[d][10]=0;


MatchCBS1p[c][1]=-((v^2 UD1[2,2,2,3])/(6 HIGHSCALE^2))+(2 v^2 CC[VCKM[c,d]] QD1[3,1,2,3] VCKM[c,b])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,s]] QD1[3,2,2,3] VCKM[c,b])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,b]] QD1[3,3,2,3] VCKM[c,b])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,d]] QD1[1,1,2,3] VCKM[c,d])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,s]] QD1[1,2,2,3] VCKM[c,d])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,b]] QD1[1,3,2,3] VCKM[c,d])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,d]] QD1[2,1,2,3] VCKM[c,s])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,s]] QD1[2,2,2,3] VCKM[c,s])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,b]] QD1[2,3,2,3] VCKM[c,s])/(3 HIGHSCALE^2)+(2 v^2 \[CurlyPhi]D[2,3])/(3 HIGHSCALE^2)-(2 v^2 Sin[\[Theta]W]^2 \[CurlyPhi]D[2,3])/(3 HIGHSCALE^2);


MatchCBS1p[c][2]=-((v^2 UD8[2,2,2,3])/(6 HIGHSCALE^2))+(2 v^2 CC[VCKM[c,d]] QD8[3,1,2,3] VCKM[c,b])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,s]] QD8[3,2,2,3] VCKM[c,b])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,b]] QD8[3,3,2,3] VCKM[c,b])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,d]] QD8[1,1,2,3] VCKM[c,d])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,s]] QD8[1,2,2,3] VCKM[c,d])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,b]] QD8[1,3,2,3] VCKM[c,d])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,d]] QD8[2,1,2,3] VCKM[c,s])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,s]] QD8[2,2,2,3] VCKM[c,s])/(3 HIGHSCALE^2)+(2 v^2 CC[VCKM[c,b]] QD8[2,3,2,3] VCKM[c,s])/(3 HIGHSCALE^2);


MatchCBS1p[c][3]=(v^2 UD1[2,2,2,3])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,d]] QD1[3,1,2,3] VCKM[c,b])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,s]] QD1[3,2,2,3] VCKM[c,b])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,b]] QD1[3,3,2,3] VCKM[c,b])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,d]] QD1[1,1,2,3] VCKM[c,d])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,s]] QD1[1,2,2,3] VCKM[c,d])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,b]] QD1[1,3,2,3] VCKM[c,d])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,d]] QD1[2,1,2,3] VCKM[c,s])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,s]] QD1[2,2,2,3] VCKM[c,s])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,b]] QD1[2,3,2,3] VCKM[c,s])/(24 HIGHSCALE^2)-(v^2 \[CurlyPhi]D[2,3])/(24 HIGHSCALE^2);


MatchCBS1p[c][4]=(v^2 UD8[2,2,2,3])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,d]] QD8[3,1,2,3] VCKM[c,b])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,s]] QD8[3,2,2,3] VCKM[c,b])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,b]] QD8[3,3,2,3] VCKM[c,b])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,d]] QD8[1,1,2,3] VCKM[c,d])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,s]] QD8[1,2,2,3] VCKM[c,d])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,b]] QD8[1,3,2,3] VCKM[c,d])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,d]] QD8[2,1,2,3] VCKM[c,s])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,s]] QD8[2,2,2,3] VCKM[c,s])/(24 HIGHSCALE^2)-(v^2 CC[VCKM[c,b]] QD8[2,3,2,3] VCKM[c,s])/(24 HIGHSCALE^2);


MatchCBS1p[c][5]=-((v^2 CC[QUQD1[2,2,3,2]])/(6 HIGHSCALE^2))-(v^2 CC[QUQD1[2,2,3,2]] CC[VCKM[c,b]] VCKM[c,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[2,2,3,2]] CC[VCKM[c,b]] VCKM[c,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[2,2,1,2]] CC[VCKM[c,d]] VCKM[c,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[2,2,1,2]] CC[VCKM[c,d]] VCKM[c,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[2,2,2,2]] CC[VCKM[c,s]] VCKM[c,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[2,2,2,2]] CC[VCKM[c,s]] VCKM[c,b])/(27 HIGHSCALE^2)-(4 v^2 CC[\[CurlyPhi]UD[2,2]] VCKM[c,b])/(9 HIGHSCALE^2)-(v^2 CC[QUQD1[3,2,3,2]] CC[VCKM[c,b]] VCKM[t,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[3,2,3,2]] CC[VCKM[c,b]] VCKM[t,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[3,2,1,2]] CC[VCKM[c,d]] VCKM[t,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[3,2,1,2]] CC[VCKM[c,d]] VCKM[t,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[3,2,2,2]] CC[VCKM[c,s]] VCKM[t,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[3,2,2,2]] CC[VCKM[c,s]] VCKM[t,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[1,2,3,2]] CC[VCKM[c,b]] VCKM[u,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[1,2,3,2]] CC[VCKM[c,b]] VCKM[u,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[1,2,1,2]] CC[VCKM[c,d]] VCKM[u,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[1,2,1,2]] CC[VCKM[c,d]] VCKM[u,b])/(27 HIGHSCALE^2)-(v^2 CC[QUQD1[1,2,2,2]] CC[VCKM[c,s]] VCKM[u,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD8[1,2,2,2]] CC[VCKM[c,s]] VCKM[u,b])/(27 HIGHSCALE^2);


MatchCBS1p[c][6]=-((v^2 CC[QUQD8[2,2,3,2]])/(6 HIGHSCALE^2))-(v^2 CC[QUQD1[2,2,3,2]] CC[VCKM[c,b]] VCKM[c,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[2,2,3,2]] CC[VCKM[c,b]] VCKM[c,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[2,2,1,2]] CC[VCKM[c,d]] VCKM[c,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[2,2,1,2]] CC[VCKM[c,d]] VCKM[c,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[2,2,2,2]] CC[VCKM[c,s]] VCKM[c,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[2,2,2,2]] CC[VCKM[c,s]] VCKM[c,b])/(36 HIGHSCALE^2)-(8 v^2 CC[\[CurlyPhi]UD[2,2]] VCKM[c,b])/(3 HIGHSCALE^2)-(v^2 CC[QUQD1[3,2,3,2]] CC[VCKM[c,b]] VCKM[t,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[3,2,3,2]] CC[VCKM[c,b]] VCKM[t,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[3,2,1,2]] CC[VCKM[c,d]] VCKM[t,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[3,2,1,2]] CC[VCKM[c,d]] VCKM[t,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[3,2,2,2]] CC[VCKM[c,s]] VCKM[t,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[3,2,2,2]] CC[VCKM[c,s]] VCKM[t,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[1,2,3,2]] CC[VCKM[c,b]] VCKM[u,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[1,2,3,2]] CC[VCKM[c,b]] VCKM[u,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[1,2,1,2]] CC[VCKM[c,d]] VCKM[u,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[1,2,1,2]] CC[VCKM[c,d]] VCKM[u,b])/(36 HIGHSCALE^2)-(v^2 CC[QUQD1[1,2,2,2]] CC[VCKM[c,s]] VCKM[u,b])/(6 HIGHSCALE^2)+(v^2 CC[QUQD8[1,2,2,2]] CC[VCKM[c,s]] VCKM[u,b])/(36 HIGHSCALE^2);


MatchCBS1p[c][7]=(v^2 CC[QUQD1[2,2,3,2]])/(6 HIGHSCALE^2)+(7 v^2 CC[QUQD1[2,2,3,2]] CC[VCKM[c,b]] VCKM[c,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[2,2,3,2]] CC[VCKM[c,b]] VCKM[c,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[2,2,1,2]] CC[VCKM[c,d]] VCKM[c,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[2,2,1,2]] CC[VCKM[c,d]] VCKM[c,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[2,2,2,2]] CC[VCKM[c,s]] VCKM[c,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[2,2,2,2]] CC[VCKM[c,s]] VCKM[c,b])/(108 HIGHSCALE^2)+(v^2 CC[\[CurlyPhi]UD[2,2]] VCKM[c,b])/(9 HIGHSCALE^2)+(7 v^2 CC[QUQD1[3,2,3,2]] CC[VCKM[c,b]] VCKM[t,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[3,2,3,2]] CC[VCKM[c,b]] VCKM[t,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[3,2,1,2]] CC[VCKM[c,d]] VCKM[t,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[3,2,1,2]] CC[VCKM[c,d]] VCKM[t,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[3,2,2,2]] CC[VCKM[c,s]] VCKM[t,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[3,2,2,2]] CC[VCKM[c,s]] VCKM[t,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[1,2,3,2]] CC[VCKM[c,b]] VCKM[u,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[1,2,3,2]] CC[VCKM[c,b]] VCKM[u,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[1,2,1,2]] CC[VCKM[c,d]] VCKM[u,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[1,2,1,2]] CC[VCKM[c,d]] VCKM[u,b])/(108 HIGHSCALE^2)+(7 v^2 CC[QUQD1[1,2,2,2]] CC[VCKM[c,s]] VCKM[u,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD8[1,2,2,2]] CC[VCKM[c,s]] VCKM[u,b])/(108 HIGHSCALE^2);


MatchCBS1p[c][8]=(v^2 CC[QUQD8[2,2,3,2]])/(6 HIGHSCALE^2)+(7 v^2 CC[QUQD1[2,2,3,2]] CC[VCKM[c,b]] VCKM[c,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[2,2,3,2]] CC[VCKM[c,b]] VCKM[c,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[2,2,1,2]] CC[VCKM[c,d]] VCKM[c,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[2,2,1,2]] CC[VCKM[c,d]] VCKM[c,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[2,2,2,2]] CC[VCKM[c,s]] VCKM[c,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[2,2,2,2]] CC[VCKM[c,s]] VCKM[c,b])/(144 HIGHSCALE^2)+(2 v^2 CC[\[CurlyPhi]UD[2,2]] VCKM[c,b])/(3 HIGHSCALE^2)+(7 v^2 CC[QUQD1[3,2,3,2]] CC[VCKM[c,b]] VCKM[t,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[3,2,3,2]] CC[VCKM[c,b]] VCKM[t,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[3,2,1,2]] CC[VCKM[c,d]] VCKM[t,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[3,2,1,2]] CC[VCKM[c,d]] VCKM[t,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[3,2,2,2]] CC[VCKM[c,s]] VCKM[t,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[3,2,2,2]] CC[VCKM[c,s]] VCKM[t,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[1,2,3,2]] CC[VCKM[c,b]] VCKM[u,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[1,2,3,2]] CC[VCKM[c,b]] VCKM[u,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[1,2,1,2]] CC[VCKM[c,d]] VCKM[u,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[1,2,1,2]] CC[VCKM[c,d]] VCKM[u,b])/(144 HIGHSCALE^2)+(7 v^2 CC[QUQD1[1,2,2,2]] CC[VCKM[c,s]] VCKM[u,b])/(24 HIGHSCALE^2)-(7 v^2 CC[QUQD8[1,2,2,2]] CC[VCKM[c,s]] VCKM[u,b])/(144 HIGHSCALE^2);


MatchCBS1p[c][9]=(v^2 CC[QUQD1[2,2,3,2]])/(96 HIGHSCALE^2)+(v^2 CC[QUQD1[2,2,3,2]] CC[VCKM[c,b]] VCKM[c,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[2,2,3,2]] CC[VCKM[c,b]] VCKM[c,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[2,2,1,2]] CC[VCKM[c,d]] VCKM[c,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[2,2,1,2]] CC[VCKM[c,d]] VCKM[c,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[2,2,2,2]] CC[VCKM[c,s]] VCKM[c,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[2,2,2,2]] CC[VCKM[c,s]] VCKM[c,b])/(432 HIGHSCALE^2)+(v^2 CC[\[CurlyPhi]UD[2,2]] VCKM[c,b])/(144 HIGHSCALE^2)+(v^2 CC[QUQD1[3,2,3,2]] CC[VCKM[c,b]] VCKM[t,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[3,2,3,2]] CC[VCKM[c,b]] VCKM[t,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[3,2,1,2]] CC[VCKM[c,d]] VCKM[t,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[3,2,1,2]] CC[VCKM[c,d]] VCKM[t,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[3,2,2,2]] CC[VCKM[c,s]] VCKM[t,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[3,2,2,2]] CC[VCKM[c,s]] VCKM[t,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[1,2,3,2]] CC[VCKM[c,b]] VCKM[u,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[1,2,3,2]] CC[VCKM[c,b]] VCKM[u,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[1,2,1,2]] CC[VCKM[c,d]] VCKM[u,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[1,2,1,2]] CC[VCKM[c,d]] VCKM[u,b])/(432 HIGHSCALE^2)+(v^2 CC[QUQD1[1,2,2,2]] CC[VCKM[c,s]] VCKM[u,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD8[1,2,2,2]] CC[VCKM[c,s]] VCKM[u,b])/(432 HIGHSCALE^2);


MatchCBS1p[c][10]=(v^2 CC[QUQD8[2,2,3,2]])/(96 HIGHSCALE^2)+(v^2 CC[QUQD1[2,2,3,2]] CC[VCKM[c,b]] VCKM[c,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[2,2,3,2]] CC[VCKM[c,b]] VCKM[c,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[2,2,1,2]] CC[VCKM[c,d]] VCKM[c,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[2,2,1,2]] CC[VCKM[c,d]] VCKM[c,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[2,2,2,2]] CC[VCKM[c,s]] VCKM[c,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[2,2,2,2]] CC[VCKM[c,s]] VCKM[c,b])/(576 HIGHSCALE^2)+(v^2 CC[\[CurlyPhi]UD[2,2]] VCKM[c,b])/(24 HIGHSCALE^2)+(v^2 CC[QUQD1[3,2,3,2]] CC[VCKM[c,b]] VCKM[t,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[3,2,3,2]] CC[VCKM[c,b]] VCKM[t,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[3,2,1,2]] CC[VCKM[c,d]] VCKM[t,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[3,2,1,2]] CC[VCKM[c,d]] VCKM[t,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[3,2,2,2]] CC[VCKM[c,s]] VCKM[t,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[3,2,2,2]] CC[VCKM[c,s]] VCKM[t,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[1,2,3,2]] CC[VCKM[c,b]] VCKM[u,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[1,2,3,2]] CC[VCKM[c,b]] VCKM[u,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[1,2,1,2]] CC[VCKM[c,d]] VCKM[u,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[1,2,1,2]] CC[VCKM[c,d]] VCKM[u,b])/(576 HIGHSCALE^2)+(v^2 CC[QUQD1[1,2,2,2]] CC[VCKM[c,s]] VCKM[u,b])/(96 HIGHSCALE^2)-(v^2 CC[QUQD8[1,2,2,2]] CC[VCKM[c,s]] VCKM[u,b])/(576 HIGHSCALE^2);


MatchCBS1p[s][1]=-((v^2 DD[2,2,2,3])/(6 HIGHSCALE^2))+(2 v^2 QD1[2,2,2,3])/(3 HIGHSCALE^2)-(v^2 QD8[2,2,2,3])/(9 HIGHSCALE^2)-(v^2 \[CurlyPhi]D[2,3])/(2 HIGHSCALE^2)-(v^2 Cos[2 \[Theta]W] \[CurlyPhi]D[2,3])/(6 HIGHSCALE^2);


MatchCBS1p[s][3]=(v^2 DD[2,2,2,3])/(24 HIGHSCALE^2)-(v^2 QD1[2,2,2,3])/(24 HIGHSCALE^2)+(v^2 QD8[2,2,2,3])/(144 HIGHSCALE^2)+(v^2 \[CurlyPhi]D[2,3])/(24 HIGHSCALE^2);


MatchCBS1p[s][5]=-((2 v^2 QD8[2,3,2,2])/(3 HIGHSCALE^2))+(v^2 CC[QUQD1[2,2,3,2]] CC[VCKM[s,b]] VCKM[c,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[2,2,3,2]] CC[VCKM[s,b]] VCKM[c,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[2,2,1,2]] CC[VCKM[s,d]] VCKM[c,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[2,2,1,2]] CC[VCKM[s,d]] VCKM[c,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[2,2,2,2]] CC[VCKM[s,s]] VCKM[c,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[2,2,2,2]] CC[VCKM[s,s]] VCKM[c,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[3,2,3,2]] CC[VCKM[s,b]] VCKM[t,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[3,2,3,2]] CC[VCKM[s,b]] VCKM[t,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[3,2,1,2]] CC[VCKM[s,d]] VCKM[t,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[3,2,1,2]] CC[VCKM[s,d]] VCKM[t,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[3,2,2,2]] CC[VCKM[s,s]] VCKM[t,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[3,2,2,2]] CC[VCKM[s,s]] VCKM[t,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[1,2,3,2]] CC[VCKM[s,b]] VCKM[u,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[1,2,3,2]] CC[VCKM[s,b]] VCKM[u,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[1,2,1,2]] CC[VCKM[s,d]] VCKM[u,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[1,2,1,2]] CC[VCKM[s,d]] VCKM[u,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[1,2,2,2]] CC[VCKM[s,s]] VCKM[u,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[1,2,2,2]] CC[VCKM[s,s]] VCKM[u,b])/(48 HIGHSCALE^2);


MatchCBS1p[s][7]=(v^2 QD8[2,3,2,2])/(6 HIGHSCALE^2)-(3 v^2 CC[QUQD1[2,2,3,2]] CC[VCKM[s,b]] VCKM[c,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[2,2,3,2]] CC[VCKM[s,b]] VCKM[c,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[2,2,1,2]] CC[VCKM[s,d]] VCKM[c,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[2,2,1,2]] CC[VCKM[s,d]] VCKM[c,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[2,2,2,2]] CC[VCKM[s,s]] VCKM[c,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[2,2,2,2]] CC[VCKM[s,s]] VCKM[c,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[3,2,3,2]] CC[VCKM[s,b]] VCKM[t,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[3,2,3,2]] CC[VCKM[s,b]] VCKM[t,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[3,2,1,2]] CC[VCKM[s,d]] VCKM[t,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[3,2,1,2]] CC[VCKM[s,d]] VCKM[t,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[3,2,2,2]] CC[VCKM[s,s]] VCKM[t,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[3,2,2,2]] CC[VCKM[s,s]] VCKM[t,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[1,2,3,2]] CC[VCKM[s,b]] VCKM[u,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[1,2,3,2]] CC[VCKM[s,b]] VCKM[u,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[1,2,1,2]] CC[VCKM[s,d]] VCKM[u,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[1,2,1,2]] CC[VCKM[s,d]] VCKM[u,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[1,2,2,2]] CC[VCKM[s,s]] VCKM[u,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[1,2,2,2]] CC[VCKM[s,s]] VCKM[u,b])/(64 HIGHSCALE^2);


MatchCBS1p[s][9]=(v^2 QD8[2,3,2,2])/(96 HIGHSCALE^2)-(v^2 CC[QUQD1[2,2,3,2]] CC[VCKM[s,b]] VCKM[c,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[2,2,3,2]] CC[VCKM[s,b]] VCKM[c,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[2,2,1,2]] CC[VCKM[s,d]] VCKM[c,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[2,2,1,2]] CC[VCKM[s,d]] VCKM[c,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[2,2,2,2]] CC[VCKM[s,s]] VCKM[c,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[2,2,2,2]] CC[VCKM[s,s]] VCKM[c,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[3,2,3,2]] CC[VCKM[s,b]] VCKM[t,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[3,2,3,2]] CC[VCKM[s,b]] VCKM[t,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[3,2,1,2]] CC[VCKM[s,d]] VCKM[t,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[3,2,1,2]] CC[VCKM[s,d]] VCKM[t,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[3,2,2,2]] CC[VCKM[s,s]] VCKM[t,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[3,2,2,2]] CC[VCKM[s,s]] VCKM[t,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[1,2,3,2]] CC[VCKM[s,b]] VCKM[u,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[1,2,3,2]] CC[VCKM[s,b]] VCKM[u,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[1,2,1,2]] CC[VCKM[s,d]] VCKM[u,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[1,2,1,2]] CC[VCKM[s,d]] VCKM[u,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[1,2,2,2]] CC[VCKM[s,s]] VCKM[u,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[1,2,2,2]] CC[VCKM[s,s]] VCKM[u,b])/(768 HIGHSCALE^2);


MatchCBS1p[b][1]=-((v^2 DD[2,3,3,3])/(6 HIGHSCALE^2))+(2 v^2 QD1[3,3,2,3])/(3 HIGHSCALE^2)-(v^2 QD8[3,3,2,3])/(9 HIGHSCALE^2)-(v^2 \[CurlyPhi]D[2,3])/(2 HIGHSCALE^2)-(v^2 Cos[2 \[Theta]W] \[CurlyPhi]D[2,3])/(6 HIGHSCALE^2);


MatchCBS1p[b][3]=(v^2 DD[2,3,3,3])/(24 HIGHSCALE^2)-(v^2 QD1[3,3,2,3])/(24 HIGHSCALE^2)+(v^2 QD8[3,3,2,3])/(144 HIGHSCALE^2)+(v^2 \[CurlyPhi]D[2,3])/(24 HIGHSCALE^2);


MatchCBS1p[b][5]=-((2 v^2 QD8[3,3,2,3])/(3 HIGHSCALE^2))-(mb mW v^2 CC[D\[CurlyPhi][3,2]] Sin[\[Theta]W])/(Sqrt[2] e HIGHSCALE^2 mh^2)+(v^2 CC[QUQD1[2,3,3,2]] CC[VCKM[b,b]] VCKM[c,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[2,3,3,2]] CC[VCKM[b,b]] VCKM[c,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[2,3,1,2]] CC[VCKM[b,d]] VCKM[c,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[2,3,1,2]] CC[VCKM[b,d]] VCKM[c,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[2,3,2,2]] CC[VCKM[b,s]] VCKM[c,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[2,3,2,2]] CC[VCKM[b,s]] VCKM[c,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[3,3,3,2]] CC[VCKM[b,b]] VCKM[t,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[3,3,3,2]] CC[VCKM[b,b]] VCKM[t,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[3,3,1,2]] CC[VCKM[b,d]] VCKM[t,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[3,3,1,2]] CC[VCKM[b,d]] VCKM[t,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[3,3,2,2]] CC[VCKM[b,s]] VCKM[t,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[3,3,2,2]] CC[VCKM[b,s]] VCKM[t,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[1,3,3,2]] CC[VCKM[b,b]] VCKM[u,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[1,3,3,2]] CC[VCKM[b,b]] VCKM[u,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[1,3,1,2]] CC[VCKM[b,d]] VCKM[u,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[1,3,1,2]] CC[VCKM[b,d]] VCKM[u,b])/(48 HIGHSCALE^2)+(v^2 CC[QUQD1[1,3,2,2]] CC[VCKM[b,s]] VCKM[u,b])/(8 HIGHSCALE^2)-(v^2 CC[QUQD8[1,3,2,2]] CC[VCKM[b,s]] VCKM[u,b])/(48 HIGHSCALE^2);


MatchCBS1p[b][7]=(v^2 QD8[3,3,2,3])/(6 HIGHSCALE^2)-(3 v^2 CC[QUQD1[2,3,3,2]] CC[VCKM[b,b]] VCKM[c,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[2,3,3,2]] CC[VCKM[b,b]] VCKM[c,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[2,3,1,2]] CC[VCKM[b,d]] VCKM[c,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[2,3,1,2]] CC[VCKM[b,d]] VCKM[c,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[2,3,2,2]] CC[VCKM[b,s]] VCKM[c,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[2,3,2,2]] CC[VCKM[b,s]] VCKM[c,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[3,3,3,2]] CC[VCKM[b,b]] VCKM[t,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[3,3,3,2]] CC[VCKM[b,b]] VCKM[t,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[3,3,1,2]] CC[VCKM[b,d]] VCKM[t,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[3,3,1,2]] CC[VCKM[b,d]] VCKM[t,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[3,3,2,2]] CC[VCKM[b,s]] VCKM[t,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[3,3,2,2]] CC[VCKM[b,s]] VCKM[t,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[1,3,3,2]] CC[VCKM[b,b]] VCKM[u,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[1,3,3,2]] CC[VCKM[b,b]] VCKM[u,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[1,3,1,2]] CC[VCKM[b,d]] VCKM[u,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[1,3,1,2]] CC[VCKM[b,d]] VCKM[u,b])/(64 HIGHSCALE^2)-(3 v^2 CC[QUQD1[1,3,2,2]] CC[VCKM[b,s]] VCKM[u,b])/(32 HIGHSCALE^2)+(3 v^2 CC[QUQD8[1,3,2,2]] CC[VCKM[b,s]] VCKM[u,b])/(64 HIGHSCALE^2);


MatchCBS1p[b][9]=(v^2 QD8[3,3,2,3])/(96 HIGHSCALE^2)-(v^2 CC[QUQD1[2,3,3,2]] CC[VCKM[b,b]] VCKM[c,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[2,3,3,2]] CC[VCKM[b,b]] VCKM[c,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[2,3,1,2]] CC[VCKM[b,d]] VCKM[c,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[2,3,1,2]] CC[VCKM[b,d]] VCKM[c,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[2,3,2,2]] CC[VCKM[b,s]] VCKM[c,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[2,3,2,2]] CC[VCKM[b,s]] VCKM[c,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[3,3,3,2]] CC[VCKM[b,b]] VCKM[t,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[3,3,3,2]] CC[VCKM[b,b]] VCKM[t,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[3,3,1,2]] CC[VCKM[b,d]] VCKM[t,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[3,3,1,2]] CC[VCKM[b,d]] VCKM[t,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[3,3,2,2]] CC[VCKM[b,s]] VCKM[t,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[3,3,2,2]] CC[VCKM[b,s]] VCKM[t,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[1,3,3,2]] CC[VCKM[b,b]] VCKM[u,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[1,3,3,2]] CC[VCKM[b,b]] VCKM[u,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[1,3,1,2]] CC[VCKM[b,d]] VCKM[u,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[1,3,1,2]] CC[VCKM[b,d]] VCKM[u,b])/(768 HIGHSCALE^2)-(v^2 CC[QUQD1[1,3,2,2]] CC[VCKM[b,s]] VCKM[u,b])/(128 HIGHSCALE^2)+(v^2 CC[QUQD8[1,3,2,2]] CC[VCKM[b,s]] VCKM[u,b])/(768 HIGHSCALE^2);


MatchCBS1p[M][7]=(mW v^2 \[Alpha]S CC[DB[3,2]] Cos[\[Theta]W] Sin[\[Theta]W])/(Sqrt[2] HIGHSCALE^2 mb \[Alpha]EM)-(mW v^2 \[Alpha]S CC[DW[3,2]] Sin[\[Theta]W]^2)/(Sqrt[2] HIGHSCALE^2 mb \[Alpha]EM);


MatchCBS1p[M][8]=(mW v^2 \[Alpha]S CC[DG[3,2]] Sin[\[Theta]W])/(Sqrt[2] HIGHSCALE^2 mb Sqrt[\[Alpha]EM \[Alpha]S]);


MatchCBS1p[e][1]=(2 v^2 ED[1,1,2,3])/(3 HIGHSCALE^2)-(v^2 LD[1,1,2,3])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]D[2,3])/(6 HIGHSCALE^2)+(v^2 Sin[\[Theta]W]^2 \[CurlyPhi]D[2,3])/HIGHSCALE^2;


MatchCBS1p[e][3]=-((v^2 ED[1,1,2,3])/(24 HIGHSCALE^2))+(v^2 LD[1,1,2,3])/(24 HIGHSCALE^2)-(v^2 \[CurlyPhi]D[2,3])/(24 HIGHSCALE^2);


MatchCBS1p[e][5]=-((v^2 LEDQ[1,1,2,3])/(6 HIGHSCALE^2));


MatchCBS1p[e][7]=(v^2 LEDQ[1,1,2,3])/(6 HIGHSCALE^2);


MatchCBS1p[e][9]=(v^2 LEDQ[1,1,2,3])/(96 HIGHSCALE^2);


MatchCBS1p[\[Mu]][1]=(2 v^2 ED[2,2,2,3])/(3 HIGHSCALE^2)-(v^2 LD[2,2,2,3])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]D[2,3])/(6 HIGHSCALE^2)+(v^2 Sin[\[Theta]W]^2 \[CurlyPhi]D[2,3])/HIGHSCALE^2;


MatchCBS1p[\[Mu]][3]=-((v^2 ED[2,2,2,3])/(24 HIGHSCALE^2))+(v^2 LD[2,2,2,3])/(24 HIGHSCALE^2)-(v^2 \[CurlyPhi]D[2,3])/(24 HIGHSCALE^2);


MatchCBS1p[\[Mu]][5]=-((v^2 LEDQ[2,2,2,3])/(6 HIGHSCALE^2));


MatchCBS1p[\[Mu]][7]=(v^2 LEDQ[2,2,2,3])/(6 HIGHSCALE^2);


MatchCBS1p[\[Mu]][9]=(v^2 LEDQ[2,2,2,3])/(96 HIGHSCALE^2);


MatchCBS1p[\[Tau]][1]=(2 v^2 ED[3,3,2,3])/(3 HIGHSCALE^2)-(v^2 LD[3,3,2,3])/(6 HIGHSCALE^2)+(v^2 \[CurlyPhi]D[2,3])/(6 HIGHSCALE^2)+(v^2 Sin[\[Theta]W]^2 \[CurlyPhi]D[2,3])/HIGHSCALE^2;


MatchCBS1p[\[Tau]][3]=-((v^2 ED[3,3,2,3])/(24 HIGHSCALE^2))+(v^2 LD[3,3,2,3])/(24 HIGHSCALE^2)-(v^2 \[CurlyPhi]D[2,3])/(24 HIGHSCALE^2);


MatchCBS1p[\[Tau]][5]=-((v^2 LEDQ[3,3,2,3])/(6 HIGHSCALE^2));


MatchCBS1p[\[Tau]][7]=(v^2 LEDQ[3,3,2,3])/(6 HIGHSCALE^2);


MatchCBS1p[\[Tau]][9]=(v^2 LEDQ[3,3,2,3])/(96 HIGHSCALE^2);
