(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* WCs *)

(* \[Psi]^2\[CurlyPhi]^3 *)
Cu\[CurlyPhi]tilde=Sum[Table[Cu\[CurlyPhi]EW[[m,n]]ULh[[i,m]]UR[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
Cd\[CurlyPhi]tilde=Sum[Table[Cd\[CurlyPhi]EW[[m,n]]DLh[[i,m]]DR[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
Ce\[CurlyPhi]tilde=Sum[Table[Ce\[CurlyPhi]EW[[m,n]]ELh[[i,m]]ER[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];

(* \[Psi]^2X \[CurlyPhi] *)
CeWtilde=Sum[Table[CeWEW[[m,n]]ELh[[i,m]]ER[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
CeBtilde=Sum[Table[CeBEW[[m,n]]ELh[[i,m]]ER[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
CuGtilde=Sum[Table[CuGEW[[m,n]]ULh[[i,m]]UR[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
CuWtilde=Sum[Table[CuWEW[[m,n]]ULh[[i,m]]UR[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
CuBtilde=Sum[Table[CuBEW[[m,n]]ULh[[i,m]]UR[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
CdGtilde=Sum[Table[CdGEW[[m,n]]DLh[[i,m]]DR[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
CdWtilde=Sum[Table[CdWEW[[m,n]]DLh[[i,m]]DR[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
CdBtilde=Sum[Table[CdBEW[[m,n]]DLh[[i,m]]DR[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];

(* \[Psi]^2\[CurlyPhi]^2D *)
C\[CurlyPhi]l1tilde=Sum[Table[C\[CurlyPhi]l1EW[[m,n]]ELh[[i,m]]EL[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
C\[CurlyPhi]l3tilde=Sum[Table[C\[CurlyPhi]l3EW[[m,n]]ELh[[i,m]]EL[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
C\[CurlyPhi]etilde=Sum[Table[C\[CurlyPhi]eEW[[m,n]]ERh[[i,m]]ER[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
C\[CurlyPhi]q1tilde=Sum[Table[C\[CurlyPhi]q1EW[[m,n]]DLh[[i,m]]DL[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
C\[CurlyPhi]q3tilde=Sum[Table[C\[CurlyPhi]q3EW[[m,n]]DLh[[i,m]]DL[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
C\[CurlyPhi]utilde=Sum[Table[C\[CurlyPhi]uEW[[m,n]]URh[[i,m]]UR[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
C\[CurlyPhi]dtilde=Sum[Table[C\[CurlyPhi]dEW[[m,n]]DRh[[i,m]]DR[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
C\[CurlyPhi]udtilde=Sum[Table[C\[CurlyPhi]udEW[[m,n]]URh[[i,m]]DR[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];

(* LL LL *)
Clltilde=Sum[Table[CllEW[[p,q,r,s]]ELh[[i,p]]EL[[q,j]]ELh[[k,r]]EL[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cqq1tilde=Sum[Table[Cqq1EW[[p,q,r,s]]DLh[[i,p]]DL[[q,j]]DLh[[k,r]]DL[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cqq3tilde=Sum[Table[Cqq3EW[[p,q,r,s]]DLh[[i,p]]DL[[q,j]]DLh[[k,r]]DL[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Clq1tilde=Sum[Table[Clq1EW[[p,q,r,s]]ELh[[i,p]]EL[[q,j]]DLh[[k,r]]DL[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Clq3tilde=Sum[Table[Clq3EW[[p,q,r,s]]ELh[[i,p]]EL[[q,j]]DLh[[k,r]]DL[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];

(* RR RR *)
Ceetilde=Sum[Table[CeeEW[[p,q,r,s]]ERh[[i,p]]ER[[q,j]]ERh[[k,r]]ER[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cuutilde=Sum[Table[CuuEW[[p,q,r,s]]URh[[i,p]]UR[[q,j]]URh[[k,r]]UR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cddtilde=Sum[Table[CddEW[[p,q,r,s]]DRh[[i,p]]DR[[q,j]]DRh[[k,r]]DR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Ceutilde=Sum[Table[CeuEW[[p,q,r,s]]ERh[[i,p]]ER[[q,j]]URh[[k,r]]UR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cedtilde=Sum[Table[CedEW[[p,q,r,s]]ERh[[i,p]]ER[[q,j]]DRh[[k,r]]DR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cud1tilde=Sum[Table[Cud1EW[[p,q,r,s]]URh[[i,p]]UR[[q,j]]DRh[[k,r]]DR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cud8tilde=Sum[Table[Cud8EW[[p,q,r,s]]URh[[i,p]]UR[[q,j]]DRh[[k,r]]DR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];

(* LL RR *)
Cletilde=Sum[Table[CleEW[[p,q,r,s]]ELh[[i,p]]EL[[q,j]]ERh[[k,r]]ER[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Clutilde=Sum[Table[CluEW[[p,q,r,s]]ELh[[i,p]]EL[[q,j]]URh[[k,r]]UR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cldtilde=Sum[Table[CldEW[[p,q,r,s]]ELh[[i,p]]EL[[q,j]]DRh[[k,r]]DR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cqetilde=Sum[Table[CqeEW[[p,q,r,s]]DLh[[i,p]]DL[[q,j]]ERh[[k,r]]ER[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cqu1tilde=Sum[Table[Cqu1EW[[p,q,r,s]]DLh[[i,p]]DL[[q,j]]URh[[k,r]]UR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cqu8tilde=Sum[Table[Cqu8EW[[p,q,r,s]]DLh[[i,p]]DL[[q,j]]URh[[k,r]]UR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cqd1tilde=Sum[Table[Cqd1EW[[p,q,r,s]]DLh[[i,p]]DL[[q,j]]DRh[[k,r]]DR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cqd8tilde=Sum[Table[Cqd8EW[[p,q,r,s]]DLh[[i,p]]DL[[q,j]]DRh[[k,r]]DR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];

(* LR RL *)
Cledqtilde=Sum[Table[CledqEW[[p,q,r,s]]ELh[[i,p]]ER[[q,j]]DRh[[k,r]]DL[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];

(* LR LR *)
Cquqd1tilde=Sum[Table[Cquqd1EW[[p,q,r,s]]ULh[[i,p]]UR[[q,j]]DLh[[k,r]]DR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cquqd8tilde=Sum[Table[Cquqd8EW[[p,q,r,s]]ULh[[i,p]]UR[[q,j]]DLh[[k,r]]DR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Clequ1tilde=Sum[Table[Clequ1EW[[p,q,r,s]]ELh[[i,p]]ER[[q,j]]ULh[[k,r]]UR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Clequ3tilde=Sum[Table[Clequ3EW[[p,q,r,s]]ELh[[i,p]]ER[[q,j]]ULh[[k,r]]UR[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];

(* B-violating *)
Cduqltilde=Sum[Table[CduqlEW[[p,q,r,s]]DR[[p,i]]UR[[q,j]]DL[[r,k]]NL[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cqquetilde=Sum[Table[CqqueEW[[p,q,r,s]]DL[[p,i]]UL[[q,j]]UR[[r,k]]ER[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cqqqltilde=Sum[Table[CqqqlEW[[p,q,r,s]]DL[[p,i]]DL[[q,j]]UL[[r,k]]EL[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];
Cduuetilde=Sum[Table[CduueEW[[p,q,r,s]]DR[[p,i]]UR[[q,j]]UR[[r,k]]ER[[s,l]],{i,1,3},{j,1,3},{k,1,3},{l,1,3}],{p,1,3},{q,1,3},{r,1,3},{s,1,3}];


(* dim-5 *)
Cll\[CurlyPhi]\[CurlyPhi]tilde=Sum[Table[Cll\[CurlyPhi]\[CurlyPhi]EW[[m,n]]EL[[m,i]]EL[[n,j]],{i,1,3},{j,1,3}],{m,1,3},{n,1,3}];
