(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



\[Beta][g]=-19/6g^3-8g m2/HIGHSCALE^2 WC[\[CurlyPhi]W];


\[Beta][gp]=41/6gp^3-8gp m2/HIGHSCALE^2 WC[\[CurlyPhi]B];


\[Beta][gs]=-7gs^3-8gs m2/HIGHSCALE^2 WC[\[CurlyPhi]G];


\[Beta][\[Lambda]]=12\[Lambda]^2+3/4gp^4+3/2g^2gp^2+9/4g^4-3(gp^2+3g^2)\[Lambda]+4\[Lambda] \[Gamma]H-4(3TrGdGdhGdGdh+3TrGuGuhGuGuh+TrGeGehGeGeh)+4m2/HIGHSCALE^2 (12 WC[\[CurlyPhi]]+(-16\[Lambda]+10/3g^2)WC[\[CurlyPhi]\[EmptySquare]]+(6\[Lambda]+3/2(gp^2-g^2))WC[\[CurlyPhi]D]+2(\[Eta]1+\[Eta]2)+9g^2WC[\[CurlyPhi]W]+3gp^2WC[\[CurlyPhi]B]+3g gp WC[\[CurlyPhi]WB]+4/3g^2(TrC\[CurlyPhi]l3+3TrC\[CurlyPhi]q3));


\[Beta][m2]=m2(6\[Lambda]-9/2g^2-3/2gp^2+2\[Gamma]H+4m2/HIGHSCALE^2(WC[\[CurlyPhi]D]-2WC[\[CurlyPhi]\[EmptySquare]]));


\[Beta][GuX]=3/2(GuGuhGu-GdGdhGu)+(\[Gamma]H-9/4g^2-17/12gp^2-8gs^2)Gu+2m2/HIGHSCALE^2(3WC[u\[CurlyPhi]]+1/2(WC[\[CurlyPhi]D]-2WC[\[CurlyPhi]\[EmptySquare]])Gu-C\[CurlyPhi]q1hGu+3C\[CurlyPhi]q3hGu+GuC\[CurlyPhi]uh-GdC\[CurlyPhi]udh-2(Cqu1Gu[rpts,pt]+4/3Cqu8Gu[rpts,pt])-Clequ1Gec[ptrs,pt]+3Cquqd1Gdc[rspt,pt]+1/2(Cquqd1Gdc[psrt,pt]+4/3Cquqd8Gdc[psrt,pt]));


\[Beta][GdX]=3/2(GdGdhGd-GuGuhGd)+(\[Gamma]H-9/4g^2-5/12gp^2-8gs^2)Gd+2m2/HIGHSCALE^2(3WC[d\[CurlyPhi]]+1/2(WC[\[CurlyPhi]D]-2WC[\[CurlyPhi]\[EmptySquare]])Gd+C\[CurlyPhi]q1hGd+3C\[CurlyPhi]q3hGd-GdC\[CurlyPhi]dh-GuC\[CurlyPhi]ud-2(Cqd1Gd[rpts,pt]+4/3Cqd8Gd[rpts,pt])+CledqcGec[ptsr,tp]+3Cquqd1Guc[ptrs,pt]+1/2(Cquqd1Guc[rpts,pt]+4/3Cquqd8Guc[rpts,pt]));


\[Beta][GeX]=3/2GeGehGe+(\[Gamma]H-3/4(3g^2+5gp^2))Ge+2m2/HIGHSCALE^2(3WC[e\[CurlyPhi]]+1/2(WC[\[CurlyPhi]D]-2WC[\[CurlyPhi]\[EmptySquare]])Ge+C\[CurlyPhi]l1hGe+3C\[CurlyPhi]l3hGe-GeC\[CurlyPhi]eh-2CleGe[rpts,pt]+3CledqGd[rspt,tp]-3Clequ1Guc[rspt,pt]);


\[Beta][\[Theta]]=-iCPV 128Pi^2/g^2m2/HIGHSCALE^2 WC[\[CurlyPhi]Wtilde];


\[Beta][\[Theta]p]=-iCPV 128Pi^2/gp^2m2/HIGHSCALE^2 WC[\[CurlyPhi]Btilde];


\[Beta][\[Theta]s]=-iCPV 128Pi^2/gs^2m2/HIGHSCALE^2 WC[\[CurlyPhi]Gtilde];


\[Beta]SM[g]=-19/6g^3;


\[Beta]SM[gp]=41/6gp^3;


\[Beta]SM[gs]=-7gs^3;


\[Beta]SM[\[Lambda]]=12\[Lambda]^2+3/4gp^4+3/2g^2gp^2+9/4g^4-3(gp^2+3g^2)\[Lambda]+4\[Lambda] \[Gamma]H-4(3TrGdGdhGdGdh+3TrGuGuhGuGuh+TrGeGehGeGeh);


\[Beta]SM[m2]=m2(6\[Lambda]-9/2g^2-3/2gp^2+2\[Gamma]H);


\[Beta]SM[GuX]=3/2(GuGuhGu-GdGdhGu)+(\[Gamma]H-9/4g^2-17/12gp^2-8gs^2)Gu;


\[Beta]SM[GdX]=3/2(GdGdhGd-GuGuhGd)+(\[Gamma]H-9/4g^2-5/12gp^2-8gs^2)Gd;


\[Beta]SM[GeX]=3/2GeGehGe+(\[Gamma]H-3/4(3g^2+5gp^2))Ge;


\[Beta]SM[\[Theta]]=0;


\[Beta]SM[\[Theta]p]=0;


\[Beta]SM[\[Theta]s]=0;


\[Beta][G]=15 gs^2 WC[G];


\[Beta][Gtilde]=15 gs^2 WC[Gtilde];


\[Beta][W]=29/2g^2WC[W];


\[Beta][Wtilde]=29/2g^2WC[Wtilde];


\[Beta][\[CurlyPhi]]=-9/2(3g^2+gp^2)WC[\[CurlyPhi]]+\[Lambda](20/3g^2WC[\[CurlyPhi]\[EmptySquare]]+3(gp^2-g^2)WC[\[CurlyPhi]D])-3/4(g^2+gp^2)^2WC[\[CurlyPhi]D]+6\[Lambda](3 g^2WC[\[CurlyPhi]W]+gp^2WC[\[CurlyPhi]B]+g gp WC[\[CurlyPhi]WB])-3(g^2 gp^2+3g^4)WC[\[CurlyPhi]W]-3(gp^4+g^2 gp^2)WC[\[CurlyPhi]B]-3(g gp^3+g^3gp)WC[\[CurlyPhi]WB]+8/3\[Lambda] g^2(TrC\[CurlyPhi]l3+3 TrC\[CurlyPhi]q3)+54\[Lambda] WC[\[CurlyPhi]]-40\[Lambda]^2WC[\[CurlyPhi]\[EmptySquare]]+12\[Lambda]^2WC[\[CurlyPhi]D]+4\[Lambda](\[Eta]1+\[Eta]2)-4(3 TrCu\[CurlyPhi]GuhGuGuh+3TrCd\[CurlyPhi]GdhGdGdh+TrCe\[CurlyPhi]GehGeGeh+3 cTrCu\[CurlyPhi]GuhGuGuh+3cTrCd\[CurlyPhi]GdhGdGdh+cTrCe\[CurlyPhi]GehGeGeh)+6\[Gamma]H WC[\[CurlyPhi]];


\[Beta][\[CurlyPhi]\[EmptySquare]]=-(4g^2+4/3gp^2)WC[\[CurlyPhi]\[EmptySquare]]+5/3gp^2WC[\[CurlyPhi]D]+2g^2(TrC\[CurlyPhi]l3+3 TrC\[CurlyPhi]q3)+2/3gp^2(2 TrC\[CurlyPhi]u-TrC\[CurlyPhi]d-TrC\[CurlyPhi]e+TrC\[CurlyPhi]q1-TrC\[CurlyPhi]l1)+12\[Lambda] WC[\[CurlyPhi]\[EmptySquare]]-2\[Eta]3+4\[Gamma]H WC[\[CurlyPhi]\[EmptySquare]];


\[Beta][\[CurlyPhi]D]=20/3gp^2WC[\[CurlyPhi]\[EmptySquare]]+(9/2g^2-5/6gp^2)WC[\[CurlyPhi]D]+8/3gp^2(2 TrC\[CurlyPhi]u-TrC\[CurlyPhi]d-TrC\[CurlyPhi]e+TrC\[CurlyPhi]q1-TrC\[CurlyPhi]l1)+6\[Lambda] WC[\[CurlyPhi]D]-2\[Eta]4+4\[Gamma]H WC[\[CurlyPhi]D];


\[Beta][\[CurlyPhi]G]=(-3/2gp^2-9/2g^2-14gs^2)WC[\[CurlyPhi]G]+6\[Lambda] WC[\[CurlyPhi]G]-2gs(TrCuGGuh+TrCdGGdh+cTrCuGGuh+cTrCdGGdh)+2\[Gamma]H WC[\[CurlyPhi]G];


\[Beta][\[CurlyPhi]B]=(85/6gp^2-9/2g^2)WC[\[CurlyPhi]B]+3g gp WC[\[CurlyPhi]WB]+6\[Lambda] WC[\[CurlyPhi]B]+gp(-5TrCuBGuh+TrCdBGdh+3TrCeBGeh-5cTrCuBGuh+cTrCdBGdh+3cTrCeBGeh)+2\[Gamma]H WC[\[CurlyPhi]B];


\[Beta][\[CurlyPhi]W]=(-3/2gp^2-53/6g^2)WC[\[CurlyPhi]W]+g gp WC[\[CurlyPhi]WB]-15g^3WC[W]+6\[Lambda] WC[\[CurlyPhi]W]-g(3 TrCuWGuh+3TrCdWGdh+TrCeWGeh+3 cTrCuWGuh+3cTrCdWGdh+cTrCeWGeh)+2\[Gamma]H WC[\[CurlyPhi]W];


\[Beta][\[CurlyPhi]WB]=(19/3gp^2+4/3g^2)WC[\[CurlyPhi]WB]+2g gp(WC[\[CurlyPhi]B]+WC[\[CurlyPhi]W])+3g^2gp WC[W]+2\[Lambda] WC[\[CurlyPhi]WB]+g(3TrCuBGuh-3 TrCdBGdh-TrCeBGeh+3cTrCuBGuh-3 cTrCdBGdh-cTrCeBGeh)+gp(5 TrCuWGuh+TrCdWGdh+3TrCeWGeh+5 cTrCuWGuh+cTrCdWGdh+3cTrCeWGeh)+2\[Gamma]H WC[\[CurlyPhi]WB];


\[Beta][\[CurlyPhi]Gtilde]=(-3/2gp^2-9/2g^2-14gs^2)WC[\[CurlyPhi]Gtilde]+6\[Lambda] WC[\[CurlyPhi]Gtilde]+2I iCPV gs(TrCuGGuh+TrCdGGdh-cTrCuGGuh-cTrCdGGdh)+2\[Gamma]H WC[\[CurlyPhi]Gtilde];


\[Beta][\[CurlyPhi]Btilde]=(85/6gp^2-9/2g^2)WC[\[CurlyPhi]Btilde]+3g gp WC[\[CurlyPhi]WtildeB]+6\[Lambda] WC[\[CurlyPhi]Btilde]-I iCPV gp(-5TrCuBGuh+TrCdBGdh+3TrCeBGeh+5cTrCuBGuh-cTrCdBGdh-3cTrCeBGeh)+2\[Gamma]H WC[\[CurlyPhi]Btilde];


\[Beta][\[CurlyPhi]Wtilde]=(-3/2gp^2-53/6g^2)WC[\[CurlyPhi]Wtilde]+g gp WC[\[CurlyPhi]WtildeB]-15g^3WC[Wtilde]+6\[Lambda] WC[\[CurlyPhi]Wtilde]+I iCPV g(3 TrCuWGuh+3TrCdWGdh+TrCeWGeh-3 cTrCuWGuh-3cTrCdWGdh-cTrCeWGeh)+2\[Gamma]H WC[\[CurlyPhi]Wtilde];


\[Beta][\[CurlyPhi]WtildeB]=(19/3gp^2+4/3g^2)WC[\[CurlyPhi]WtildeB]+2g gp(WC[\[CurlyPhi]Btilde]+WC[\[CurlyPhi]Wtilde])+3g^2gp WC[Wtilde]+2\[Lambda] WC[\[CurlyPhi]WtildeB]-I iCPV g(3TrCuBGuh-3 TrCdBGdh-TrCeBGeh-3cTrCuBGuh+3 cTrCdBGdh+cTrCeBGeh)-I iCPV gp(5 TrCuWGuh+TrCdWGdh+3TrCeWGeh-5 cTrCuWGuh-cTrCdWGdh-3cTrCeWGeh)+2\[Gamma]H WC[\[CurlyPhi]WtildeB];


\[Beta][u\[CurlyPhi]]=(10/3g^2 WC[\[CurlyPhi]\[EmptySquare]]+3/2(gp^2-g^2)WC[\[CurlyPhi]D]+32gs^2(WC[\[CurlyPhi]G]+I iCPV WC[\[CurlyPhi]Gtilde])+9g^2(WC[\[CurlyPhi]W]+I iCPV WC[\[CurlyPhi]Wtilde])+17/3gp^2(WC[\[CurlyPhi]B]+I iCPV WC[\[CurlyPhi]Btilde])-g gp(WC[\[CurlyPhi]WB]+I iCPV WC[\[CurlyPhi]WtildeB])+4/3g^2(TrC\[CurlyPhi]l3+3TrC\[CurlyPhi]q3))Gu-(35/12gp^2+27/4g^2+8gs^2)WC[u\[CurlyPhi]]-gp(5gp^2-3g^2)WC[uB]+g(5gp^2-9g^2)WC[uW]-(3g^2-gp^2)GuC\[CurlyPhi]u+3g^2GdC\[CurlyPhi]udh+4gp^2C\[CurlyPhi]q1Gu-4gp^2C\[CurlyPhi]q3Gu-5gp(CuBGuhGu+GuGuhCuB)-3g(CuWGuhGu-GuGuhCuW)-16gs(CuGGuhGu+GuGuhCuG)-12g GdGdhCuW-6g CdWGdhGu+\[Lambda](12 WC[u\[CurlyPhi]]-2C\[CurlyPhi]q1Gu+6C\[CurlyPhi]q3Gu+2GuC\[CurlyPhi]u-2GdC\[CurlyPhi]udh-2WC[\[CurlyPhi]\[EmptySquare]]Gu+WC[\[CurlyPhi]D]Gu-4Cqu1Gu[rpts,pt]-16/3Cqu8Gu[rpts,pt]-2Clequ1Gec[ptrs,pt]+6Cquqd1Gdc[rspt,pt]+Cquqd1Gdc[psrt,pt]+4/3Cquqd8Gdc[psrt,pt])+2(\[Eta]1+\[Eta]2-\[Eta]5)Gu+(WC[\[CurlyPhi]D]-6WC[\[CurlyPhi]\[EmptySquare]])GuGuhGu-2C\[CurlyPhi]q1GuGuhGu+6C\[CurlyPhi]q3GdGdhGu+2GuGuhGuC\[CurlyPhi]u-2GdGdhGdC\[CurlyPhi]udh+8(Cqu1GuGuhGu[rpts,pt]+4/3Cqu8GuGuhGu[rpts,pt])-2(Cquqd1GdhGdGdh[tsrp,pt]+4/3Cquqd8GdhGdGdh[tsrp,pt])-12Cquqd1GdhGdGdh[rstp,pt]+4Clequ1GeGehGe[tprs,pt]+4Cu\[CurlyPhi]GuhGu+5GuGuhCu\[CurlyPhi]-2GdCd\[CurlyPhi]hGu-Cd\[CurlyPhi]GdhGu-2GdGdhCu\[CurlyPhi]+3\[Gamma]H WC[u\[CurlyPhi]]+\[Gamma]qCu\[CurlyPhi]+Cu\[CurlyPhi]\[Gamma]u;


\[Beta][d\[CurlyPhi]]=(10/3g^2 WC[\[CurlyPhi]\[EmptySquare]]+3/2(gp^2-g^2)WC[\[CurlyPhi]D]+32gs^2(WC[\[CurlyPhi]G]+I iCPV WC[\[CurlyPhi]Gtilde])+9g^2(WC[\[CurlyPhi]W]+I iCPV WC[\[CurlyPhi]Wtilde])+5/3gp^2(WC[\[CurlyPhi]B]+I iCPV WC[\[CurlyPhi]Btilde])+g gp(WC[\[CurlyPhi]WB]+I iCPV WC[\[CurlyPhi]WtildeB])+4/3g^2(TrC\[CurlyPhi]l3+3TrC\[CurlyPhi]q3))Gd-(23/12gp^2+27/4g^2+8gs^2)WC[d\[CurlyPhi]]-gp(3g^2-gp^2)WC[dB]-g(9g^2-gp^2)WC[dW]+(3g^2+gp^2)GdC\[CurlyPhi]d+3g^2GuC\[CurlyPhi]ud-2gp^2C\[CurlyPhi]q1Gd-2gp^2C\[CurlyPhi]q3Gd+gp(CdBGdhGd+GdGdhCdB)-3g(CdWGdhGd-GdGdhCdW)-16gs(CdGGdhGd+GdGdhCdG)-12g GuGuhCdW-6g CuWGuhGd+\[Lambda](12 WC[d\[CurlyPhi]]+2C\[CurlyPhi]q1Gd+6C\[CurlyPhi]q3Gd-2GdC\[CurlyPhi]d-2GuC\[CurlyPhi]ud-2WC[\[CurlyPhi]\[EmptySquare]]Gd+WC[\[CurlyPhi]D]Gd-4Cqd1Gd[rpts,pt]-16/3Cqd8Gd[rpts,pt]+2CledqcGec[ptsr,tp]+6Cquqd1Guc[ptrs,pt]+Cquqd1Guc[rtps,pt]+4/3Cquqd8Guc[rtps,pt])+2(\[Eta]1+\[Eta]2+\[Eta]5)Gd+(WC[\[CurlyPhi]D]-6WC[\[CurlyPhi]\[EmptySquare]])GdGdhGd+2C\[CurlyPhi]q1GdGdhGd+6C\[CurlyPhi]q3GuGuhGd-2GdGdhGdC\[CurlyPhi]d-2GuGuhGuC\[CurlyPhi]ud+8(Cqd1GdGdhGd[rpts,pt]+4/3Cqd8GdGdhGd[rpts,pt])-2(Cquqd1GuhGuGuh[rpts,pt]+4/3Cquqd8GuhGuGuh[rpts,pt])-12Cquqd1GuGuhGu[tprs,pt]-4CledqcGeGehGe[ptsr,pt]+4Cd\[CurlyPhi]GdhGd+5GdGdhCd\[CurlyPhi]-2GuCu\[CurlyPhi]hGd-Cu\[CurlyPhi]GuhGd-2GuGuhCd\[CurlyPhi]+3\[Gamma]H WC[d\[CurlyPhi]]+\[Gamma]qCd\[CurlyPhi]+Cd\[CurlyPhi]\[Gamma]d;


\[Beta][e\[CurlyPhi]]=(10/3g^2 WC[\[CurlyPhi]\[EmptySquare]]+3/2(gp^2-g^2)WC[\[CurlyPhi]D]+9g^2(WC[\[CurlyPhi]W]+I iCPV WC[\[CurlyPhi]Wtilde])+15gp^2(WC[\[CurlyPhi]B]+I iCPV WC[\[CurlyPhi]Btilde])-3g gp(WC[\[CurlyPhi]WB]+I iCPV WC[\[CurlyPhi]WtildeB])+4/3g^2(TrC\[CurlyPhi]l3+3TrC\[CurlyPhi]q3))Ge-3/4(7gp^2+9g^2)WC[e\[CurlyPhi]]-3gp(g^2-3gp^2)WC[eB]-9g(g^2-gp^2)WC[eW]+3(g^2-gp^2)GeC\[CurlyPhi]e-6gp^2C\[CurlyPhi]l1Ge-6gp^2C\[CurlyPhi]l3Ge+9gp(CeBGehGe+GeGehCeB)-3g(CeWGehGe-GeGehCeW)+\[Lambda](12 WC[e\[CurlyPhi]]+2C\[CurlyPhi]l1Ge+6C\[CurlyPhi]l3Ge-2GeC\[CurlyPhi]e-2WC[\[CurlyPhi]\[EmptySquare]]Ge+WC[\[CurlyPhi]D]Ge-4CleGe[rpts,pt]+6CledqGd[rspt,pt]-6Clequ1Guc[rspt,pt])+2(\[Eta]1+\[Eta]2+\[Eta]5)Ge+(WC[\[CurlyPhi]D]-6WC[\[CurlyPhi]\[EmptySquare]])GeGehGe+2C\[CurlyPhi]l1GeGehGe-2GeGehGeC\[CurlyPhi]e+8CleGeGehGe[rpts,pt]-12CledqGdGdhGd[rspt,tp]+12Clequ1GuhGuGuh[rstp,pt]+4Ce\[CurlyPhi]GehGe+5GeGehCe\[CurlyPhi]+3\[Gamma]H WC[e\[CurlyPhi]]+\[Gamma]lCe\[CurlyPhi]+Ce\[CurlyPhi]\[Gamma]e;


\[Beta][eW]=1/12(3gp^2-11g^2)WC[eW]-1/2 g gp WC[eB]-(g(WC[\[CurlyPhi]W]+I iCPV WC[\[CurlyPhi]Wtilde])-3/2gp(WC[\[CurlyPhi]WB]+I iCPV WC[\[CurlyPhi]WtildeB]))Ge-6g Clequ3Guc[rspt,pt]+CeWGehGe+\[Gamma]H WC[eW]+\[Gamma]lCeW+CeW\[Gamma]e;


\[Beta][eB]=1/4(151/3gp^2-9g^2)WC[eB]-3/2g gp WC[eW]-(3/2g(WC[\[CurlyPhi]WB]+I iCPV WC[\[CurlyPhi]WtildeB])-3gp(WC[\[CurlyPhi]B]+I iCPV WC[\[CurlyPhi]Btilde]))Ge+10gp Clequ3Guc[rspt,pt]+CeBGehGe+2GeGehCeB+\[Gamma]H WC[eB]+\[Gamma]lCeB+CeB\[Gamma]e;


\[Beta][uG]=-1/36(81g^2+19gp^2+204gs^2)WC[uG]+6g gs WC[uW]+10/3gp gs WC[uB]-gs(4(WC[\[CurlyPhi]G]+I iCPV WC[\[CurlyPhi]Gtilde])+9gs(WC[G]+I iCPV WC[Gtilde]))Gu-gs(Cquqd1Gdc[psrt,pt]-1/6Cquqd8Gdc[psrt,pt])+2GuGuhCuG-2GdGdhCuG-CdGGdhGu+CuGGuhGu+\[Gamma]H WC[uG]+\[Gamma]qCuG+CuG\[Gamma]u;


\[Beta][uW]=-1/36(33g^2+19gp^2-96gs^2)WC[uW]+8/3g gs WC[uG]-1/6g gp WC[uB]-(g(WC[\[CurlyPhi]W]+I iCPV WC[\[CurlyPhi]Wtilde])-5/6gp(WC[\[CurlyPhi]WB]+I iCPV WC[\[CurlyPhi]WtildeB]))Gu+g/4(Cquqd1Gdc[psrt,pt]+4/3Cquqd8Gdc[psrt,pt])-2g Clequ3Gec[ptrs,tp]+2GdGdhCuW-CdWGdhGu+CuWGuhGu+\[Gamma]H WC[uW]+\[Gamma]qCuW+CuW\[Gamma]u;


\[Beta][uB]=-1/36(81g^2-313gp^2-96gs^2)WC[uB]+40/9gp gs WC[uG]-1/2g gp WC[uW]-(-3/2g(WC[\[CurlyPhi]WB]+I iCPV WC[\[CurlyPhi]WtildeB])+5/3gp(WC[\[CurlyPhi]B]+I iCPV WC[\[CurlyPhi]Btilde]))Gu+gp/12(Cquqd1Gdc[psrt,pt]+4/3Cquqd8Gdc[psrt,pt])-6gp Clequ3Gec[ptrs,tp]+2GuGuhCuB-2GdGdhCuB-CdBGdhGu+CuBGuhGu+\[Gamma]H WC[uB]+\[Gamma]qCuB+CuB\[Gamma]u;


\[Beta][dG]=-1/36(81g^2+31gp^2+204gs^2)WC[dG]+6g gs WC[dW]-2/3gp gs WC[dB]-gs(4(WC[\[CurlyPhi]G]+I iCPV WC[\[CurlyPhi]Gtilde])+9gs(WC[G]+I iCPV WC[Gtilde]))Gd-gs(Cquqd1Guc[rtps,pt]-1/6Cquqd8Guc[rtps,pt])-2GuGuhCdG+2GdGdhCdG-CuGGuhGd+CdGGdhGd+\[Gamma]H WC[dG]+\[Gamma]qCdG+CdG\[Gamma]d;


\[Beta][dW]=-1/36(33g^2+31gp^2-96gs^2)WC[dW]+8/3g gs WC[dG]+5/6g gp WC[dB]-(g(WC[\[CurlyPhi]W]+I iCPV WC[\[CurlyPhi]Wtilde])-gp/6(WC[\[CurlyPhi]WB]+I iCPV WC[\[CurlyPhi]WtildeB]))Gd+g/4(Cquqd1Guc[rtps,pt]+4/3Cquqd8Guc[rtps,pt])+2GuGuhCdW-CuWGuhGd+CdWGdhGd+\[Gamma]H WC[dW]+\[Gamma]qCdW+CdW\[Gamma]d;


\[Beta][dB]=-1/36(81g^2-253gp^2-96gs^2)WC[dB]-8/9gp gs WC[dG]+5/2g gp WC[dW]-(3/2g(WC[\[CurlyPhi]WB]+I iCPV WC[\[CurlyPhi]WtildeB])-gp/3(WC[\[CurlyPhi]B]+I iCPV WC[\[CurlyPhi]Btilde]))Gd-5/12gp(Cquqd1Guc[rtps,pt]+4/3Cquqd8Guc[rtps,pt])-2GuGuhCdB+2GdGdhCdB-CuBGuhGd+CdBGdhGd+\[Gamma]H WC[dB]+\[Gamma]qCdB+CdB\[Gamma]d;


\[Beta][\[CurlyPhi]l1]=-1/4\[Xi]B gp^2 I3+1/3gp^2WC[\[CurlyPhi]l1]-2/3gp^2(Cld[rstt]+Cle[rstt]+2Cll[rstt]+Cll[rtts]-Clq1[rstt]-2Clu[rstt])-1/2(WC[\[CurlyPhi]\[EmptySquare]]+WC[\[CurlyPhi]D])GeGeh-GeC\[CurlyPhi]eGeh+3/2(GeGehC\[CurlyPhi]l1+C\[CurlyPhi]l1GeGeh+3GeGehC\[CurlyPhi]l3+3C\[CurlyPhi]l3GeGeh)+2CleGehGe[rspt,tp]-2(2CllGeGeh[rspt,tp]+CllGeGeh[rtps,tp])-6Clq1GdGdh[rspt,tp]+6Clq1GuGuh[rspt,tp]-6CluGuhGu[rspt,tp]+6CldGdhGd[rspt,tp]+2\[Gamma]H WC[\[CurlyPhi]l1]+\[Gamma]lC\[CurlyPhi]l1+C\[CurlyPhi]l1\[Gamma]l;


\[Beta][\[CurlyPhi]l3]=2/3g^2(1/4WC[\[CurlyPhi]\[EmptySquare]]+TrC\[CurlyPhi]l3+3TrC\[CurlyPhi]q3)I3-17/3g^2WC[\[CurlyPhi]l3]+2/3g^2Cll[rtts]+2g^2Clq3[rstt]-1/2WC[\[CurlyPhi]\[EmptySquare]]GeGeh+1/2(3GeGehC\[CurlyPhi]l1+3C\[CurlyPhi]l1GeGeh+GeGehC\[CurlyPhi]l3+C\[CurlyPhi]l3GeGeh)-2(CllGeGeh[rtps,tp])-6Clq3GdGdh[rspt,tp]-6Clq3GuGuh[rspt,tp]+2\[Gamma]H WC[\[CurlyPhi]l3]+\[Gamma]lC\[CurlyPhi]l3+C\[CurlyPhi]l3\[Gamma]l;


\[Beta][\[CurlyPhi]e]=-1/2\[Xi]B gp^2 I3+1/3 gp^2 WC[\[CurlyPhi]e]-2/3gp^2(Ced[rstt]+4Cee[rstt]-2Ceu[rstt]+Cle[ttrs]-Cqe[ttrs])+(WC[\[CurlyPhi]\[EmptySquare]]+WC[\[CurlyPhi]D])GehGe-2GehC\[CurlyPhi]l1Ge+3(GehGeC\[CurlyPhi]e+C\[CurlyPhi]eGehGe)-2CleGeGeh[ptrs,tp]+8CeeGehGe[rspt,tp]-6CeuGuhGu[rspt,tp]+6CedGdhGd[rspt,tp]-6CqeGdGdh[ptrs,tp]+6CqeGuGuh[ptrs,tp]+2\[Gamma]H WC[\[CurlyPhi]e]+\[Gamma]eC\[CurlyPhi]e+C\[CurlyPhi]e\[Gamma]e;


\[Beta][\[CurlyPhi]q1]=1/12\[Xi]B gp^2 I3+1/3gp^2WC[\[CurlyPhi]q1]-2/3gp^2(Clq1[ttrs]+Cqd1[rstt]-2Cqu1[rstt]+Cqe[rstt]-2Cqq1[rstt]-1/3Cqq1[rtts]-Cqq3[rtts])+1/2(WC[\[CurlyPhi]\[EmptySquare]]+WC[\[CurlyPhi]D])(GuGuh-GdGdh)-GuC\[CurlyPhi]uGuh-GdC\[CurlyPhi]dGdh+2CqeGehGe[rspt,tp]-2Clq1GeGeh[ptrs,tp]+3/2(GdGdhC\[CurlyPhi]q1+GuGuhC\[CurlyPhi]q1+C\[CurlyPhi]q1GdGdh+C\[CurlyPhi]q1GuGuh+3GdGdhC\[CurlyPhi]q3-3GuGuhC\[CurlyPhi]q3+3C\[CurlyPhi]q3GdGdh-3C\[CurlyPhi]q3GuGuh)-2(6Cqq1GdGdh[ptrs,tp]+Cqq1GdGdh[psrt,tp]+3Cqq3GdGdh[psrt,tp]-6Cqq1GuGuh[ptrs,tp]-Cqq1GuGuh[psrt,tp]-3Cqq3GuGuh[psrt,tp])-6Cqu1GuhGu[rspt,tp]+6Cqd1GdhGd[rspt,tp]+2\[Gamma]H WC[\[CurlyPhi]q1]+\[Gamma]qC\[CurlyPhi]q1+C\[CurlyPhi]q1\[Gamma]q;


\[Beta][\[CurlyPhi]q3]=2/3g^2(1/4WC[\[CurlyPhi]\[EmptySquare]]+TrC\[CurlyPhi]l3+3TrC\[CurlyPhi]q3)I3-17/3g^2WC[\[CurlyPhi]q3]+2/3g^2(Clq3[ttrs]+Cqq1[rtts]+6Cqq3[rstt]-Cqq3[rtts])-1/2WC[\[CurlyPhi]\[EmptySquare]](GuGuh+GdGdh)+1/2(3GdGdhC\[CurlyPhi]q1-3GuGuhC\[CurlyPhi]q1+3C\[CurlyPhi]q1GdGdh-3C\[CurlyPhi]q1GuGuh+GdGdhC\[CurlyPhi]q3+GuGuhC\[CurlyPhi]q3+C\[CurlyPhi]q3GdGdh+C\[CurlyPhi]q3GuGuh)-2(6Cqq3GdGdh[rspt,tp]+Cqq1GdGdh[rtps,tp]-Cqq3GdGdh[rtps,tp]+6Cqq3GuGuh[rspt,tp]+Cqq1GuGuh[rtps,tp]-Cqq3GuGuh[rtps,tp])-2Clq3GeGeh[ptrs,tp]+2\[Gamma]H WC[\[CurlyPhi]q3]+\[Gamma]qC\[CurlyPhi]q3+C\[CurlyPhi]q3\[Gamma]q;


\[Beta][\[CurlyPhi]u]=1/3\[Xi]B gp^2 I3+1/3gp^2WC[\[CurlyPhi]u]-2/3gp^2(Ceu[ttrs]+Clu[ttrs]-Cqu1[ttrs]+Cud1[rstt]-4Cuu[rstt]-4/3Cuu[rtts])-(WC[\[CurlyPhi]\[EmptySquare]]+WC[\[CurlyPhi]D])GuhGu-2GuhC\[CurlyPhi]q1Gu+3(GuhGuC\[CurlyPhi]u+C\[CurlyPhi]uGuhGu)+GuhGdC\[CurlyPhi]udh+C\[CurlyPhi]udGdhGu-4(3CuuGuhGu[rspt,tp]+CuuGuhGu[rtps,tp])+2CeuGehGe[ptrs,tp]-2CluGeGeh[ptrs,tp]+6Cud1GdhGd[rspt,tp]-6Cqu1GdGdh[ptrs,tp]+6Cqu1GuGuh[ptrs,tp]+2\[Gamma]H WC[\[CurlyPhi]u]+\[Gamma]uC\[CurlyPhi]u+C\[CurlyPhi]u\[Gamma]u;


\[Beta][\[CurlyPhi]d]=-1/6\[Xi]B gp^2I3+1/3gp^2WC[\[CurlyPhi]d]-2/3gp^2(2Cdd[rstt]+2/3Cdd[rtts]+Ced[ttrs]+Cld[ttrs]-Cqd1[ttrs]-2Cud1[ttrs])+(WC[\[CurlyPhi]\[EmptySquare]]+WC[\[CurlyPhi]D])GdhGd-2GdhC\[CurlyPhi]q1Gd+3(GdhGdC\[CurlyPhi]d+C\[CurlyPhi]dGdhGd)-GdhGuC\[CurlyPhi]ud-C\[CurlyPhi]udhGuhGd+4(3CddGdhGd[rspt,tp]+CddGdhGd[rtps,tp])+2CedGehGe[ptrs,tp]-2CldGeGeh[ptrs,tp]-6Cud1GuhGu[ptrs,tp]-6Cqd1GdGdh[ptrs,tp]+6Cqd1GuGuh[ptrs,tp]+2\[Gamma]H WC[\[CurlyPhi]d]+\[Gamma]dC\[CurlyPhi]d+C\[CurlyPhi]d\[Gamma]d;


\[Beta][\[CurlyPhi]ud]=-3gp^2WC[\[CurlyPhi]ud]+(2WC[\[CurlyPhi]\[EmptySquare]]-WC[\[CurlyPhi]D])GuhGd-2GuhGdC\[CurlyPhi]d+2C\[CurlyPhi]uGuhGd+4(Cud1GuhGd[rtps,tp]+4/3Cud8GuhGd[rtps,tp])+2GuhGuC\[CurlyPhi]ud+2C\[CurlyPhi]udGdhGd+2\[Gamma]H WC[\[CurlyPhi]ud]+\[Gamma]uC\[CurlyPhi]ud+C\[CurlyPhi]ud\[Gamma]d;


\[Beta][ll]=-1/6gp^2C\[CurlyPhi]l1\[Delta][st,pr]-1/6g^2(C\[CurlyPhi]l3\[Delta][st,pr]-2C\[CurlyPhi]l3\[Delta][sr,pt])+1/3gp^2(2Cll\[Delta][prww,st]+Cll\[Delta][pwwr,st])-1/3g^2Cll\[Delta][pwwr,st]+2/3g^2Cll\[Delta][swwr,pt]-1/3gp^2Clq1\[Delta][prww,st]-g^2Clq3\[Delta][prww,st]+2g^2Clq3\[Delta][ptww,rs]+1/3gp^2(-2Clu\[Delta][prww,st]+Cld\[Delta][prww,st]+Cle\[Delta][prww,st])-1/2(GeGehxC\[CurlyPhi]l1[pr,st]-GeGehxC\[CurlyPhi]l3[pr,st])-GeGehxC\[CurlyPhi]l3[pt,sr]-1/2GeGecCle[sv,tw,prvw]+\[Gamma]lCll[pv,vrst]+Cll\[Gamma]l[pvst,vr]-1/6gp^2C\[CurlyPhi]l1\[Delta][pr,st]-1/6g^2(C\[CurlyPhi]l3\[Delta][pr,st]-2C\[CurlyPhi]l3\[Delta][pt,sr])+1/3gp^2(2Cll\[Delta][stww,pr]+Cll\[Delta][swwt,pr])-1/3g^2Cll\[Delta][swwt,pr]+2/3g^2Cll\[Delta][pwwt,sr]-1/3gp^2Clq1\[Delta][stww,pr]-g^2Clq3\[Delta][stww,pr]+2g^2Clq3\[Delta][srww,tp]+1/3gp^2(-2Clu\[Delta][stww,pr]+Cld\[Delta][stww,pr]+Cle\[Delta][stww,pr])-1/2(GeGehxC\[CurlyPhi]l1[st,pr]-GeGehxC\[CurlyPhi]l3[st,pr])-GeGehxC\[CurlyPhi]l3[sr,pt]-1/2GeGecCle[pv,rw,stvw]+\[Gamma]lCll[sv,vtpr]+Cll\[Gamma]l[svpr,vt]+6g^2Cll[ptsr]+3(gp^2-g^2)Cll[prst];


\[Beta][qq1]=1/18gp^2C\[CurlyPhi]q1\[Delta][st,pr]-1/9gp^2Clq1\[Delta][wwst,pr]+1/9gp^2(2Cqq1\[Delta][prww,st]+1/3(Cqq1\[Delta][pwwr,st]+3Cqq3\[Delta][pwwr,st]))+1/3gs^2(Cqq1\[Delta][swwr,pt]+3Cqq3\[Delta][swwr,pt])-2/9gs^2(Cqq1\[Delta][pwwr,st]+3Cqq3\[Delta][pwwr,st])+2/9gp^2Cqu1\[Delta][prww,st]-1/9gp^2Cqd1\[Delta][prww,st]+1/12gs^2(Cqu8\[Delta][srww,pt]+Cqd8\[Delta][srww,pt])-1/18gs^2(Cqu8\[Delta][prww,st]+Cqd8\[Delta][prww,st])-1/9gp^2Cqe\[Delta][prww,st]+1/2(GuGuhxC\[CurlyPhi]q1[pr,st]-GdGdhxC\[CurlyPhi]q1[pr,st])-1/2(GuGucCqu1[pv,rw,stvw]-1/6GuGucCqu8[pv,rw,stvw])-1/2(GdGdcCqd1[pv,rw,stvw]-1/6GdGdcCqd8[pv,rw,stvw])-1/8(GuGucCqu8[pv,tw,srvw]+GdGdcCqd8[pv,tw,srvw])-1/8(GdcGucCquqd1[tw,rv,pvsw]-1/6GdcGucCquqd8[tw,rv,pvsw])-1/8(GdGuCquqd1c[sw,pv,rvtw]-1/6GdGuCquqd8c[sw,pv,rvtw])+1/16(GdcGucCquqd8[tw,rv,svpw]+GdGuCquqd8c[sw,pv,tvrw])+\[Gamma]qCqq1[pv,vrst]+Cqq1\[Gamma]q[pvst,vr]+1/18gp^2C\[CurlyPhi]q1\[Delta][pr,st]-1/9gp^2Clq1\[Delta][wwpr,st]+1/9gp^2(2Cqq1\[Delta][stww,pr]+1/3(Cqq1\[Delta][swwt,pr]+3Cqq3\[Delta][swwt,pr]))+1/3gs^2(Cqq1\[Delta][pwwt,sr]+3Cqq3\[Delta][pwwt,sr])-2/9gs^2(Cqq1\[Delta][swwt,pr]+3Cqq3\[Delta][swwt,pr])+2/9gp^2Cqu1\[Delta][stww,pr]-1/9gp^2Cqd1\[Delta][stww,pr]+1/12gs^2(Cqu8\[Delta][ptww,sr]+Cqd8\[Delta][ptww,sr])-1/18gs^2(Cqu8\[Delta][stww,pr]+Cqd8\[Delta][stww,pr])-1/9gp^2Cqe\[Delta][stww,pr]+1/2(GuGuhxC\[CurlyPhi]q1[st,pr]-GdGdhxC\[CurlyPhi]q1[st,pr])-1/2(GuGucCqu1[sv,tw,prvw]-1/6GuGucCqu8[sv,tw,prvw])-1/2(GdGdcCqd1[sv,tw,prvw]-1/6GdGdcCqd8[sv,tw,prvw])-1/8(GuGucCqu8[sv,rw,ptvw]+GdGdcCqd8[sv,rw,ptvw])-1/8(GdcGucCquqd1[rw,tv,svpw]-1/6GdcGucCquqd8[rw,tv,svpw])-1/8(GdGuCquqd1c[pw,sv,tvrw]-1/6GdGuCquqd8c[pw,sv,tvrw])+1/16(GdcGucCquqd8[rw,tv,pvsw]+GdGuCquqd8c[pw,sv,rvtw])+\[Gamma]qCqq1[sv,vtpr]+Cqq1\[Gamma]q[svpr,vt]+9g^2Cqq3[prst]-2(gs^2-1/6gp^2)Cqq1[prst]+3gs^2(Cqq1[ptsr]+3Cqq3[ptsr]);


\[Beta][qq3]=1/6g^2C\[CurlyPhi]q3\[Delta][st,pr]+1/3g^2Clq3\[Delta][wwst,pr]+1/3g^2(Cqq1\[Delta][pwwr,st]-Cqq3\[Delta][pwwr,st])+2g^2Cqq3\[Delta][prww,st]+1/3gs^2(Cqq1\[Delta][swwr,pt]+3Cqq3\[Delta][swwr,pt])+1/12gs^2(Cqu8\[Delta][srww,pt]+Cqd8\[Delta][srww,pt])-1/2(GuGuhxC\[CurlyPhi]q3[pr,st]+GdGdhxC\[CurlyPhi]q3[pr,st])-1/8(GuGucCqu8[pv,tw,srvw]+GdGdcCqd8[pv,tw,srvw])+1/8(GdcGucCquqd1[tw,rv,pvsw]-1/6GdcGucCquqd8[tw,rv,pvsw])+1/8(GdGuCquqd1c[sw,pv,rvtw]-1/6GdGuCquqd8c[sw,pv,rvtw])-1/16(GdcGucCquqd8[tw,rv,svpw]+GdGuCquqd8c[sw,pv,tvrw])+\[Gamma]qCqq3[pv,vrst]+Cqq3\[Gamma]q[pvst,vr]+1/6g^2C\[CurlyPhi]q3\[Delta][pr,st]+1/3g^2Clq3\[Delta][wwpr,st]+1/3g^2(Cqq1\[Delta][swwt,pr]-Cqq3\[Delta][swwt,pr])+2g^2Cqq3\[Delta][stww,pr]+1/3gs^2(Cqq1\[Delta][pwwt,sr]+3Cqq3\[Delta][pwwt,sr])+1/12gs^2(Cqu8\[Delta][ptww,sr]+Cqd8\[Delta][ptww,sr])-1/2(GuGuhxC\[CurlyPhi]q3[st,pr]+GdGdhxC\[CurlyPhi]q3[st,pr])-1/8(GuGucCqu8[sv,rw,ptvw]+GdGdcCqd8[sv,rw,ptvw])+1/8(GdcGucCquqd1[rw,tv,svpw]-1/6GdcGucCquqd8[rw,tv,svpw])+1/8(GdGuCquqd1c[pw,sv,tvrw]-1/6GdGuCquqd8c[pw,sv,tvrw])-1/16(GdcGucCquqd8[rw,tv,pvsw]+GdGuCquqd8c[pw,sv,rvtw])+\[Gamma]qCqq3[sv,vtpr]+Cqq3\[Gamma]q[svpr,vt]+3gs^2(Cqq1[ptsr]-Cqq3[ptsr])-2(gs^2+3g^2-1/6gp^2)Cqq3[prst]+3g^2Cqq1[prst];


\[Beta][lq1]=-1/3gp^2C\[CurlyPhi]q1\[Delta][st,pr]+1/9gp^2C\[CurlyPhi]l1\[Delta][pr,st]-2/9gp^2(2Cll\[Delta][prww,st]+Cll\[Delta][pwwr,st])+2/9gp^2Clq1\[Delta][prww,st]+2/3gp^2Clq1\[Delta][wwst,pr]-2/9gp^2(6Cqq1\[Delta][stww,pr]+Cqq1\[Delta][swwt,pr]+3Cqq3\[Delta][swwt,pr])-2/3gp^2(2Cqu1\[Delta][stww,pr]-Cqd1\[Delta][stww,pr]-Cqe\[Delta][stww,pr])+2/9gp^2(2Clu\[Delta][prww,st]-Cld\[Delta][prww,st]-Cle\[Delta][prww,st])-gp^2Clq1[prst]+9g^2Clq3[prst]-GeGehxC\[CurlyPhi]q1[pr,st]+GuGuhxC\[CurlyPhi]l1[st,pr]-GdGdhxC\[CurlyPhi]l1[st,pr]+1/4(GucGecClequ1[tw,rv,pvsw]-12GucGecClequ3[tw,rv,pvsw]+GuGeClequ1c[sw,pv,rvtw]-12GuGeClequ3c[sw,pv,rvtw])-GuGucClu[sv,tw,prvw]-GdGdcCld[sv,tw,prvw]-GeGecCqe[pv,rw,stvw]+1/4(GdGecCledq[sw,rv,pvwt]+GeGdcCledqc[pv,tw,rvws])+\[Gamma]lClq1[pv,vrst]+\[Gamma]qClq1[sv,prvt]+Clq1\[Gamma]l[pvst,vr]+Clq1\[Gamma]q[prsv,vt];


\[Beta][lq3]=1/3g^2(C\[CurlyPhi]q3\[Delta][st,pr]+C\[CurlyPhi]l3\[Delta][pr,st])+2/3g^2(3Clq3\[Delta][prww,st]+Clq3\[Delta][wwst,pr])+2/3g^2(6Cqq3\[Delta][stww,pr]+Cqq1\[Delta][swwt,pr]-Cqq3\[Delta][swwt,pr])+2/3g^2Cll\[Delta][pwwr,st]+3g^2Clq1[prst]-(6g^2+gp^2)Clq3[prst]-GeGehxC\[CurlyPhi]q3[pr,st]-GuGuhxC\[CurlyPhi]l3[st,pr]-GdGdhxC\[CurlyPhi]l3[st,pr]-1/4(GucGecClequ1[tw,rv,pvsw]-12GucGecClequ3[tw,rv,pvsw]+GuGeClequ1c[sw,pv,rvtw]-12GuGeClequ3c[sw,pv,rvtw])+1/4(GdGecCledq[sw,rv,pvwt]+GeGdcCledqc[pv,tw,rvws])+\[Gamma]lClq3[pv,vrst]+\[Gamma]qClq3[sv,prvt]+Clq3\[Gamma]l[pvst,vr]+Clq3\[Gamma]q[prsv,vt];


\[Beta][ee]=-1/3gp^2C\[CurlyPhi]e\[Delta][st,pr]+2/3gp^2(Cle\[Delta][wwpr,st]-Cqe\[Delta][wwpr,st]-2Ceu\[Delta][prww,st]+Ced\[Delta][prww,st]+4Cee\[Delta][prww,st])+GehGexC\[CurlyPhi]e[pr,st]-GeGecCle[wr,vp,vwst]+\[Gamma]eCee[pv,vrst]+Cee\[Gamma]e[pvst,vr]-1/3gp^2C\[CurlyPhi]e\[Delta][pr,st]+2/3gp^2(Cle\[Delta][wwst,pr]-Cqe\[Delta][wwst,pr]-2Ceu\[Delta][stww,pr]+Ced\[Delta][stww,pr]+4Cee\[Delta][wwst,pr])+GehGexC\[CurlyPhi]e[st,pr]-GeGecCle[wt,vs,vwpr]+\[Gamma]eCee[sv,vtpr]+Cee\[Gamma]e[svpr,vt]+12gp^2Cee[prst];


\[Beta][uu]=2/9gp^2C\[CurlyPhi]u\[Delta][st,pr]-4/9gp^2(Ceu\[Delta][wwst,pr]+Clu\[Delta][wwst,pr]-Cqu1\[Delta][wwst,pr]-4Cuu\[Delta][wwst,pr]-4/3Cuu\[Delta][swwt,pr])-1/9gs^2(Cqu8\[Delta][wwst,pr]-3Cqu8\[Delta][wwsr,pt])+2/3gs^2Cuu\[Delta][pwwt,rs]-2/9gs^2Cuu\[Delta][swwt,pr]-4/9gp^2Cud1\[Delta][stww,pr]-1/18gs^2(Cud8\[Delta][stww,pr]-3Cud8\[Delta][srww,pt])-GuhGuxC\[CurlyPhi]u[pr,st]-(GuGucCqu1[wr,vp,vwst]-1/6GuGucCqu8[wr,vp,vwst])-1/2GuGucCqu8[wr,vs,vwpt]+\[Gamma]uCuu[pv,vrst]+Cuu\[Gamma]u[pvst,vr]+2/9gp^2C\[CurlyPhi]u\[Delta][pr,st]-4/9gp^2(Ceu\[Delta][wwpr,st]+Clu\[Delta][wwpr,st]-Cqu1\[Delta][wwpr,st]-4Cuu\[Delta][wwpr,st]-4/3Cuu\[Delta][pwwr,st])-1/9gs^2(Cqu8\[Delta][wwpr,st]-3Cqu8\[Delta][wwpt,sr])+2/3gs^2Cuu\[Delta][swwr,tp]-2/9gs^2Cuu\[Delta][pwwr,st]-4/9gp^2Cud1\[Delta][prww,st]-1/18gs^2(Cud8\[Delta][prww,st]-3Cud8\[Delta][ptww,sr])-GuhGuxC\[CurlyPhi]u[st,pr]-(GuGucCqu1[wt,vs,vwpr]-1/6GuGucCqu8[wt,vs,vwpr])-1/2GuGucCqu8[wt,vp,vwsr]+\[Gamma]uCuu[sv,vtpr]+Cuu\[Gamma]u[svpr,vt]+2(8/3gp^2-gs^2)Cuu[prst]+6gs^2Cuu[ptsr];


\[Beta][dd]=-1/9gp^2C\[CurlyPhi]d\[Delta][st,pr]+2/9gp^2(Ced\[Delta][wwst,pr]+Cld\[Delta][wwst,pr]-Cqd1\[Delta][wwst,pr]+2Cdd\[Delta][wwst,pr]+2/3Cdd\[Delta][swwt,pr])-1/9gs^2(Cqd8\[Delta][wwst,pr]-3Cqd8\[Delta][wwsr,pt])+2/3gs^2Cdd\[Delta][pwwt,rs]-2/9gs^2Cdd\[Delta][swwt,pr]-4/9gp^2Cud1\[Delta][wwst,pr]-1/18gs^2(Cud8\[Delta][wwst,pr]-3Cud8\[Delta][wwsr,pt])+GdhGdxC\[CurlyPhi]d[pr,st]-(GdGdcCqd1[wr,vp,vwst]-1/6GdGdcCqd8[wr,vp,vwst])-1/2GdGdcCqd8[wr,vs,vwpt]+\[Gamma]dCdd[pv,vrst]+Cdd\[Gamma]d[pvst,vr]-1/9gp^2C\[CurlyPhi]d\[Delta][pr,st]+2/9gp^2(Ced\[Delta][wwpr,st]+Cld\[Delta][wwpr,st]-Cqd1\[Delta][wwpr,st]+2Cdd\[Delta][wwpr,st]+2/3Cdd\[Delta][pwwr,st])-1/9gs^2(Cqd8\[Delta][wwpr,st]-3Cqd8\[Delta][wwpt,sr])+2/3gs^2Cdd\[Delta][swwr,tp]-2/9gs^2Cdd\[Delta][pwwr,st]-4/9gp^2Cud1\[Delta][wwpr,st]-1/18gs^2(Cud8\[Delta][wwpr,st]-3Cud8\[Delta][wwpt,sr])+GdhGdxC\[CurlyPhi]d[st,pr]-(GdGdcCqd1[wt,vs,vwpr]-1/6GdGdcCqd8[wt,vs,vwpr])-1/2GdGdcCqd8[wt,vp,vwsr]+\[Gamma]dCdd[sv,vtpr]+Cdd\[Gamma]d[svpr,vt]+2(2/3gp^2-gs^2)Cdd[prst]+6gs^2Cdd[ptsr];


\[Beta][eu]=-2/3gp^2(C\[CurlyPhi]u\[Delta][st,pr]+2(Cqu1\[Delta][wwst,pr]-Clu\[Delta][wwst,pr]+4Cuu\[Delta][wwst,pr]-Ceu\[Delta][wwst,pr]-Cud1\[Delta][stww,pr])+8/3Cuu\[Delta][swwt,pr])+4/9gp^2(C\[CurlyPhi]e\[Delta][pr,st]+2(Cqe\[Delta][wwpr,st]-Cle\[Delta][wwpr,st]-4Cee\[Delta][prww,st]+2Ceu\[Delta][prww,st]-Ced\[Delta][prww,st]))-8gp^2Ceu[prst]+2GehGexC\[CurlyPhi]u[pr,st]-2GuhGuxC\[CurlyPhi]e[st,pr]+GecGucClequ1[vp,ws,vrwt]-12GecGucClequ3[vp,ws,vrwt]+GeGuClequ1c[vr,wt,vpws]-12GeGuClequ3c[vr,wt,vpws]-2GecGeClu[vp,wr,vwst]-2GucGuCqe[vs,wt,vwpr]+\[Gamma]eCeu[pv,vrst]+\[Gamma]uCeu[sv,prvt]+Ceu\[Gamma]e[pvst,vr]+Ceu\[Gamma]u[prsv,vt];


\[Beta][ed]=-2/3gp^2(C\[CurlyPhi]d\[Delta][st,pr]+2(Cqd1\[Delta][wwst,pr]-Cld\[Delta][wwst,pr]-2Cdd\[Delta][wwst,pr]-Ced\[Delta][wwst,pr]+2Cud1\[Delta][wwst,pr])-4/3Cdd\[Delta][swwt,pr])-2/9gp^2(C\[CurlyPhi]e\[Delta][pr,st]+2(Cqe\[Delta][wwpr,st]-Cle\[Delta][wwpr,st]-4Cee\[Delta][prww,st]-Ced\[Delta][prww,st]+2Ceu\[Delta][prww,st]))+4gp^2Ced[prst]+2GehGexC\[CurlyPhi]d[pr,st]+2GdhGdxC\[CurlyPhi]e[st,pr]-2GecGeCld[vp,wr,vwst]-2GdcGdCqe[vs,wt,vwpr]+GecGdCledq[vp,wt,vrsw]+GeGdcCledqc[vr,ws,vptw]+\[Gamma]eCed[pv,vrst]+\[Gamma]dCed[sv,prvt]+Ced\[Gamma]e[pvst,vr]+Ced\[Gamma]d[prsv,vt];


\[Beta][ud1]=4/9gp^2(C\[CurlyPhi]d\[Delta][st,pr]+2(Cqd1\[Delta][wwst,pr]-Cld\[Delta][wwst,pr]-2Cdd\[Delta][wwst,pr]+2Cud1\[Delta][wwst,pr]-Ced\[Delta][wwst,pr])-4/3Cdd\[Delta][swwt,pr])-2/9gp^2(C\[CurlyPhi]u\[Delta][pr,st]+2(Cqu1\[Delta][wwpr,st]-Clu\[Delta][wwpr,st]+4Cuu\[Delta][wwpr,st]-Cud1\[Delta][prww,st]-Ceu\[Delta][wwpr,st])+8/3Cuu\[Delta][pwwr,st])-8/3(gp^2Cud1[prst]-gs^2Cud8[prst])-2GuhGuxC\[CurlyPhi]d[pr,st]+2GdhGdxC\[CurlyPhi]u[st,pr]+2/3GdhGuxC\[CurlyPhi]ud[sr,pt]+2/3GuhGdxC\[CurlyPhi]udc[pt,rs]+1/3(GdcGucCquqd1[vs,wp,vrwt]+4/3GdcGucCquqd8[vs,wp,vrwt]+GdGuCquqd1c[vt,wr,vpws]+4/3GdGuCquqd8c[vt,wr,vpws])-GdcGucCquqd1[ws,vp,vrwt]-GdGuCquqd1c[wt,vr,vpws]-2GucGuCqd1[vp,wr,vwst]-2GdcGdCqu1[vs,wt,vwpr]+\[Gamma]uCud1[pv,vrst]+\[Gamma]dCud1[sv,prvt]+Cud1\[Gamma]u[pvst,vr]+Cud1\[Gamma]d[prsv,vt];


\[Beta][ud8]=8/3gs^2Cuu\[Delta][pwwr,st]+8/3gs^2Cdd\[Delta][swwt,pr]+4/3gs^2Cqu8\[Delta][wwpr,st]+4/3gs^2Cqd8\[Delta][wwst,pr]+2/3gs^2Cud8\[Delta][prww,st]+2/3gs^2Cud8\[Delta][wwst,pr]-4(2/3gp^2+gs^2)Cud8[prst]+12gs^2Cud1[prst]+4GdhGuxC\[CurlyPhi]ud[sr,pt]+4GuhGdxC\[CurlyPhi]udc[pt,rs]+2(GdcGucCquqd1[vs,wp,vrwt]-1/6GdcGucCquqd8[vs,wp,vrwt]+GdGuCquqd1c[vt,wr,vpws]-1/6GdGuCquqd8c[vt,wr,vpws])-2GucGuCqd8[vp,wr,vwst]-2GdcGdCqu8[vs,wt,vwpr]-(GdcGucCquqd8[ws,vp,vrwt]+GdGuCquqd8c[wt,vr,vpws])+\[Gamma]uCud8[pv,vrst]+\[Gamma]dCud8[sv,prvt]+Cud8\[Gamma]u[pvst,vr]+Cud8\[Gamma]d[prsv,vt];


\[Beta][le]=-1/3gp^2C\[CurlyPhi]e\[Delta][st,pr]-2/3gp^2C\[CurlyPhi]l1\[Delta][pr,st]+8/3gp^2Cll\[Delta][prww,st]+4/3gp^2Cll\[Delta][pwwr,st]-4/3gp^2Clq1\[Delta][prww,st]-2/3gp^2Cqe\[Delta][wwst,pr]+4/3gp^2Cle\[Delta][prww,st]+2/3gp^2Cle\[Delta][wwst,pr]-8/3gp^2Clu\[Delta][prww,st]+4/3gp^2Cld\[Delta][prww,st]-4/3gp^2 Ceu\[Delta][stww,pr]+2/3gp^2Ced\[Delta][stww,pr]+8/3gp^2Cee\[Delta][wwst,pr]-6gp^2Cle[prst]+Gec\[Xi]e[rs,pt]+Ge\[Xi]ec[pt,rs]-GeGehxC\[CurlyPhi]e[pr,st]+2GehGexC\[CurlyPhi]l1[st,pr]-4GeGecCee[pv,rw,vtsw]+GeGecCle[pw,vs,vrwt]-2GeGecCll[wt,vs,pwvr]-4GeGecCll[wt,vs,prvw]+GeGecCle[vt,rw,pvsw]+\[Gamma]lCle[pv,vrst]+\[Gamma]eCle[sv,prvt]+Cle\[Gamma]l[pvst,vr]+Cle\[Gamma]e[prsv,vt];


\[Beta][lu]=-1/3gp^2C\[CurlyPhi]u\[Delta][st,pr]+4/9gp^2C\[CurlyPhi]l1\[Delta][pr,st]-16/9gp^2Cll\[Delta][prww,st]-8/9gp^2Cll\[Delta][pwwr,st]+8/9gp^2Clq1\[Delta][prww,st]-2/3gp^2Cqu1\[Delta][wwst,pr]+16/9gp^2Clu\[Delta][prww,st]+2/3gp^2Clu\[Delta][wwst,pr]-8/9gp^2Cld\[Delta][prww,st]-8/9gp^2Cle\[Delta][prww,st]+2/3gp^2Cud1\[Delta][stww,pr]+2/3gp^2Ceu\[Delta][wwst,pr]-8/3gp^2Cuu\[Delta][stww,pr]-8/9gp^2Cuu\[Delta][swwt,pr]+4gp^2Clu[prst]-GeGehxC\[CurlyPhi]u[pr,st]-2GuhGuxC\[CurlyPhi]l1[st,pr]-1/2(GecGucClequ1[rv,ws,pvwt]+12GecGucClequ3[rv,ws,pvwt])-1/2(GeGuClequ1c[pv,wt,rvws]+12GeGuClequ3c[pv,wt,rvws])-2GucGuClq1[vs,wt,prvw]-GecGeCeu[rw,pv,vwst]+\[Gamma]lClu[pv,vrst]+\[Gamma]uClu[sv,prvt]+Clu\[Gamma]l[pvst,vr]+Clu\[Gamma]u[prsv,vt];


\[Beta][ld]=-1/3gp^2C\[CurlyPhi]d\[Delta][st,pr]-2/9gp^2C\[CurlyPhi]l1\[Delta][pr,st]+8/9gp^2Cll\[Delta][prww,st]+4/9gp^2Cll\[Delta][pwwr,st]-4/9gp^2Clq1\[Delta][prww,st]-2/3gp^2Cqd1\[Delta][wwst,pr]+4/9gp^2Cld\[Delta][prww,st]+2/3gp^2Cld\[Delta][wwst,pr]-8/9gp^2Clu\[Delta][prww,st]+4/9gp^2Cle\[Delta][prww,st]-4/3gp^2Cud1\[Delta][wwst,pr]+2/3gp^2Ced\[Delta][wwst,pr]+4/3gp^2Cdd\[Delta][stww,pr]+4/9gp^2Cdd\[Delta][swwt,pr]-2gp^2Cld[prst]-GeGehxC\[CurlyPhi]d[pr,st]+2GdhGdxC\[CurlyPhi]l1[st,pr]-1/2GecGdCledq[rv,wt,pvsw]-1/2GeGdcCledqc[pv,ws,rvtw]-2GdcGdClq1[vs,wt,prvw]-GecGeCed[rw,pv,vwst]+\[Gamma]lCld[pv,vrst]+\[Gamma]dCld[sv,prvt]+Cld\[Gamma]l[pvst,vr]+Cld\[Gamma]d[prsv,vt];


\[Beta][qe]=1/9gp^2C\[CurlyPhi]e\[Delta][st,pr]-2/3gp^2C\[CurlyPhi]q1\[Delta][pr,st]-8/3gp^2Cqq1\[Delta][prww,st]-4/9gp^2(Cqq1\[Delta][pwwr,st]+3Cqq3\[Delta][pwwr,st])+4/3gp^2Clq1\[Delta][wwpr,st]-2/9gp^2Cle\[Delta][wwst,pr]+4/3gp^2Cqe\[Delta][prww,st]+2/9gp^2Cqe\[Delta][wwst,pr]-8/3gp^2Cqu1\[Delta][prww,st]+4/3gp^2Cqd1\[Delta][prww,st]+4/9gp^2Ceu\[Delta][stww,pr]-2/9gp^2Ced\[Delta][stww,pr]-8/9gp^2Cee\[Delta][wwst,pr]+2gp^2Cqe[prst]+GuGuhxC\[CurlyPhi]e[pr,st]-GdGdhxC\[CurlyPhi]e[pr,st]+2GehGexC\[CurlyPhi]q1[st,pr]-1/2GdGecCledq[pw,vs,vtwr]-1/2GeGdcCledqc[vt,rw,vswp]-2GecGeClq1[vs,wt,vwpr]-1/2(GucGecClequ1[rw,vs,vtpw]+12GucGecClequ3[rw,vs,vtpw])-1/2(GuGeClequ1c[pw,vt,vsrw]+12GuGeClequ3c[pw,vt,vsrw])-GdcGdCed[rw,pv,stvw]-GucGuCeu[rw,pv,stvw]+\[Gamma]qCqe[pv,vrst]+\[Gamma]eCqe[sv,prvt]+Cqe\[Gamma]q[pvst,vr]+Cqe\[Gamma]e[prsv,vt];


\[Beta][qu1]=1/9gp^2C\[CurlyPhi]u\[Delta][st,pr]+4/9gp^2C\[CurlyPhi]q1\[Delta][pr,st]+16/9gp^2Cqq1\[Delta][prww,st]+8/27gp^2(Cqq1\[Delta][pwwr,st]+3Cqq3\[Delta][pwwr,st])-8/9gp^2Clq1\[Delta][wwpr,st]-8/9gp^2Cqe\[Delta][prww,st]-8/9gp^2Cqd1\[Delta][prww,st]+16/9gp^2Cqu1\[Delta][prww,st]+2/9gp^2Cqu1\[Delta][wwst,pr]-2/9gp^2Clu\[Delta][wwst,pr]-2/9gp^2Ceu\[Delta][wwst,pr]-2/9gp^2Cud1\[Delta][stww,pr]+8/9gp^2Cuu\[Delta][stww,pr]+8/27gp^2Cuu\[Delta][swwt,pr]-4/3gp^2Cqu1[prst]-8/3gs^2Cqu8[prst]+1/3Guc\[Xi]u[rs,pt]+1/3Gu\[Xi]uc[pt,rs]+GuGuhxC\[CurlyPhi]u[pr,st]-GdGdhxC\[CurlyPhi]u[pr,st]-2GuhGuxC\[CurlyPhi]q1[st,pr]+1/3(GuGucCqu1[pw,vs,vrwt]+4/3GuGucCqu8[pw,vs,vrwt])+1/3(GuGucCqu1[vt,rw,pvsw]+4/3GuGucCqu8[vt,rw,pvsw])+1/3(GdcGucCquqd1[rw,vs,ptvw]+4/3GdcGucCquqd8[rw,vs,ptvw])+1/3(GdGuCquqd1c[pw,vt,rsvw]+4/3GdGuCquqd8c[pw,vt,rsvw])+1/2GdcGucCquqd1[rw,vs,vtpw]+1/2GdGuCquqd1c[pw,vt,vsrw]-2/3(GuGucCqq1[vt,ws,pvwr]+3GuGucCqq3[vt,ws,pvwr])-4GuGucCqq1[wt,vs,prvw]-2/3GuGucCuu[pv,rw,vtsw]-2GuGucCuu[pv,rw,vwst]-GdGdcCud1[pv,rw,stvw]+\[Gamma]qCqu1[pv,vrst]+\[Gamma]uCqu1[sv,prvt]+Cqu1\[Gamma]q[pvst,vr]+Cqu1\[Gamma]u[prsv,vt];


\[Beta][qd1]=1/9gp^2C\[CurlyPhi]d\[Delta][st,pr]-2/9gp^2C\[CurlyPhi]q1\[Delta][pr,st]-8/9gp^2Cqq1\[Delta][prww,st]-4/27gp^2(Cqq1\[Delta][pwwr,st]+3Cqq3\[Delta][pwwr,st])+4/9gp^2Clq1\[Delta][wwpr,st]+4/9gp^2Cqe\[Delta][prww,st]-8/9gp^2Cqu1\[Delta][prww,st]+4/9gp^2Cqd1\[Delta][prww,st]+2/9gp^2Cqd1\[Delta][wwst,pr]-2/9gp^2Cld\[Delta][wwst,pr]-2/9gp^2Ced\[Delta][wwst,pr]+4/9gp^2Cud1\[Delta][wwst,pr]-4/9gp^2Cdd\[Delta][stww,pr]-4/27gp^2Cdd\[Delta][swwt,pr]+2/3gp^2Cqd1[prst]-8/3gs^2Cqd8[prst]+1/3Gdc\[Xi]d[rs,pt]+1/3Gd\[Xi]dc[pt,rs]+GuGuhxC\[CurlyPhi]d[pr,st]-GdGdhxC\[CurlyPhi]d[pr,st]+2GdhGdxC\[CurlyPhi]q1[st,pr]+1/3(GdGdcCqd1[pw,vs,vrwt]+4/3GdGdcCqd8[pw,vs,vrwt])+1/3(GdGdcCqd1[vt,rw,pvsw]+4/3GdGdcCqd8[vt,rw,pvsw])+1/3(GucGdcCquqd1[rw,vs,vwpt]+4/3GucGdcCquqd8[rw,vs,vwpt])+1/3(GuGdCquqd1c[pw,vt,vwrs]+4/3GuGdCquqd8c[pw,vt,vwrs])+1/2GdcGucCquqd1[ws,rv,pvwt]+1/2GuGdCquqd1c[pv,wt,rvws]-2/3(GdGdcCqq1[vt,ws,pvwr]+3GdGdcCqq3[vt,ws,pvwr])-4GdGdcCqq1[wt,vs,prvw]-2/3GdGdcCdd[pv,rw,vtsw]-2GdGdcCdd[pv,rw,vwst]-GuGucCud1[pv,rw,vwst]+\[Gamma]qCqd1[pv,vrst]+\[Gamma]dCqd1[sv,prvt]+Cqd1\[Gamma]q[pvst,vr]+Cqd1\[Gamma]d[prsv,vt];


\[Beta][qu8]=8/3gs^2(Cqq1\[Delta][pwwr,st]+3Cqq3\[Delta][pwwr,st])+2/3gs^2Cqu8\[Delta][prww,st]+2/3gs^2Cqd8\[Delta][prww,st]+4/3gs^2Cqu8\[Delta][wwst,pr]+2/3gs^2Cud8\[Delta][stww,pr]+8/3gs^2Cuu\[Delta][swwt,pr]-(4/3gp^2+14gs^2)Cqu8[prst]-12gs^2Cqu1[prst]+2Guc\[Xi]u[rs,pt]+2Gu\[Xi]uc[pt,rs]+2(GuGucCqu1[pw,vs,vrwt]-1/6GuGucCqu8[pw,vs,vrwt])+2(GuGucCqu1[vt,rw,pvsw]-1/6GuGucCqu8[vt,rw,pvsw])+2(GdcGucCquqd1[rw,vs,ptvw]-1/6GdcGucCquqd8[rw,vs,ptvw])+2(GdGuCquqd1c[pw,vt,rsvw]-1/6GdGuCquqd8c[pw,vt,rsvw])+1/2GucGdcCquqd8[vs,rw,vtpw]+1/2GuGdCquqd8c[vt,pw,vsrw]-4(GuGucCqq1[vt,ws,pvwr]+3GuGucCqq3[vt,ws,pvwr])-4GuGucCuu[pv,rw,vtsw]-GdGdcCud8[pv,rw,stvw]+\[Gamma]qCqu8[pv,vrst]+\[Gamma]uCqu8[sv,prvt]+Cqu8\[Gamma]q[pvst,vr]+Cqu8\[Gamma]u[prsv,vt];


\[Beta][qd8]=8/3gs^2(Cqq1\[Delta][pwwr,st]+3Cqq3\[Delta][pwwr,st])+2/3gs^2Cqu8\[Delta][prww,st]+2/3gs^2Cqd8\[Delta][prww,st]+4/3gs^2Cqd8\[Delta][wwst,pr]+2/3gs^2Cud8\[Delta][wwst,pr]+8/3gs^2Cdd\[Delta][swwt,pr]-(-2/3gp^2+14gs^2)Cqd8[prst]-12gs^2Cqd1[prst]+2Gdc\[Xi]d[rs,pt]+2Gd\[Xi]dc[pt,rs]+2(GdGdcCqd1[pw,vs,vrwt]-1/6GdGdcCqd8[pw,vs,vrwt])+2(GdGdcCqd1[vt,rw,pvsw]-1/6GdGdcCqd8[vt,rw,pvsw])+2(GucGdcCquqd1[rw,vs,vwpt]-1/6GucGdcCquqd8[rw,vs,vwpt])+2(GuGdCquqd1c[pw,vt,vwrs]-1/6GuGdCquqd8c[pw,vt,vwrs])+1/2GdcGucCquqd8[vs,rw,pwvt]+1/2GdGuCquqd8c[vt,pw,rwvs]-4(GdGdcCqq1[vt,ws,pvwr]+3GdGdcCqq3[vt,ws,pvwr])-4GdGdcCdd[pv,rw,vtsw]-GuGucCud8[pv,rw,vwst]+\[Gamma]qCqd8[pv,vrst]+\[Gamma]dCqd8[sv,prvt]+Cqd8\[Gamma]q[pvst,vr]+Cqd8\[Gamma]d[prsv,vt];


\[Beta][ledq]=-(8/3gp^2+8gs^2)Cledq[prst]-2Gdc\[Xi]e[ts,pr]-2Ge\[Xi]dc[rp,st]+2GeGdcCed[pv,tw,vrsw]-2GeGdcCld[vr,tw,pvsw]+2GeGdcClq1[vr,ws,pvwt]+6GeGdcClq3[vr,ws,pvwt]-2GeGdcCqe[pw,vs,vtwr]+2GdcGucClequ1[vs,tw,prvw]+\[Gamma]lCledq[pv,vrst]+\[Gamma]qCledq[sv,prvt]+Cledq\[Gamma]e[pvst,vr]+Cledq\[Gamma]d[prsv,vt];


\[Beta][quqd1]=10/3gp CdBGu[st,pr]-6g CdWGu[st,pr]-20/9gp CdBGu[pt,sr]+4g CdWGu[pt,sr]-64/9gs CdGGu[pt,sr]-2/3 gp CuBGd[pr,st]-6g CuWGd[pr,st]+4/9gp CuBGd[sr,pt]+4g CuWGd[sr,pt]-64/9gs CuGGd[sr,pt]-1/2(11/9gp^2+3g^2+32gs^2)Cquqd1[prst]-1/3(-5/9gp^2-3g^2+64/3gs^2)Cquqd1[srpt]-4/9(-5/9gp^2-3g^2+28/3gs^2)Cquqd8[srpt]+16/9gs^2Cquqd8[prst]-2Gu\[Xi]d[pr,st]-2Gd\[Xi]u[st,pr]+4/3(GuGdCqd1[vr,pw,svwt]+4/3GuGdCqd8[vr,pw,svwt]+GdGuCqu1[vt,sw,pvwr]+4/3GdGuCqu8[vt,sw,pvwr]+GdGuCud1[pw,sv,vrwt]+4/3GdGuCud8[pw,sv,vrwt])+8/3(GdGuCqq1[wt,vr,svpw]-3GdGuCqq3[wt,vr,svpw]-3GdGuCqq1[wt,vr,swpv]+9GdGuCqq3[wt,vr,swpv])-4GdGuCud1[sw,pv,vrwt]+\[Gamma]qCquqd1[pv,vrst]+\[Gamma]qCquqd1[sv,prvt]+Cquqd1\[Gamma]u[pvst,vr]+Cquqd1\[Gamma]d[prsv,vt];


\[Beta][quqd8]=8gs CdGGu[st,pr]-40/3gp CdBGu[pt,sr]+24g CdWGu[pt,sr]+16/3gs CdGGu[pt,sr]+8gs CuGGd[pr,st]+8/3gp CuBGd[sr,pt]+24g CuWGd[sr,pt]+16/3gs CuGGd[sr,pt]+8gs^2Cquqd1[prst]+(10/9gp^2+6g^2+16/3gs^2)Cquqd1[srpt]+(-11/18gp^2-3/2g^2+16/3gs^2)Cquqd8[prst]-1/3(5/9gp^2+3g^2+44/3gs^2)Cquqd8[srpt]+8(GuGdCqd1[vr,pw,svwt]-1/6GuGdCqd8[vr,pw,svwt]+GdGuCqu1[vt,sw,pvwr]-1/6GdGuCqu8[vt,sw,pvwr]+GdGuCud1[pw,sv,vrwt]-1/6GdGuCud8[pw,sv,vrwt])+16(GdGuCqq1[wt,vr,svpw]-3GdGuCqq3[wt,vr,svpw])-4GdGuCud8[sw,pv,vrwt]+\[Gamma]qCquqd8[pv,vrst]+\[Gamma]qCquqd8[sv,prvt]+Cquqd8\[Gamma]u[pvst,vr]+Cquqd8\[Gamma]d[prsv,vt];


\[Beta][lequ1]=-(11/3gp^2+8gs^2)Clequ1[prst]+(30gp^2+18g^2)Clequ3[prst]+2Gu\[Xi]e[st,pr]+2Ge\[Xi]u[pr,st]+2GdGuCledq[sv,wt,prvw]+2GeGuCeu[pv,sw,vrwt]+2GeGuClq1[vr,wt,pvsw]-6GeGuClq3[vr,wt,pvsw]-2GeGuClu[vr,sw,pvwt]-2GeGuCqe[pw,vt,svwr]+\[Gamma]lClequ1[pv,vrst]+\[Gamma]qClequ1[sv,prvt]+Clequ1\[Gamma]e[pvst,vr]+Clequ1\[Gamma]u[prsv,vt];


\[Beta][lequ3]=5/6gp CeBGu[pr,st]-3/2g CuWGe[st,pr]-3/2gp CuBGe[st,pr]-3/2g CeWGu[pr,st]+(2/9gp^2-3g^2+8/3gs^2)Clequ3[prst]+1/8(5gp^2+3g^2)Clequ1[prst]-1/2GuGeCeu[sw,pv,vrwt]-1/2GeGuClq1[vr,wt,pvsw]+3/2GeGuClq3[vr,wt,pvsw]-1/2GeGuClu[vr,sw,pvwt]-1/2GeGuCqe[pw,vt,svwr]+\[Gamma]lClequ3[pv,vrst]+\[Gamma]qClequ3[sv,prvt]+Clequ3\[Gamma]e[pvst,vr]+Clequ3\[Gamma]u[prsv,vt];


\[Beta][duql]=-(9/2g^2+11/6gp^2+4gs^2)Cduql[prst]-GdcGdCduql[sv,wp,vrwt]-GucGuCduql[sv,wr,pvwt]+2GecGucCduue[tv,sw,prwv]+GecGucCduue[tv,sw,pwrv]+4GdGuCqqql[vp,wr,vwst]+4GdGuCqqql[vp,wr,wvst]-GdGuCqqql[vp,wr,vswt]-GdGuCqqql[vp,wr,wsvt]+2GdGecCqque[wp,tv,wsrv]+GdhGdCduql[vp,vrst]+GuhGuCduql[vr,pvst]+1/2(GuGuhCduql[vs,prvt]+GdGdhCduql[vs,prvt])+1/2GeGehCduql[vt,prsv];


\[Beta][qque]=-(9/2g^2+23/6gp^2+4gs^2)Cqque[prst]-GucGuCqque[rv,ws,pwvt]+1/2GeGdcCduql[wt,rv,vspw]-1/2(2GdcGucCduue[pv,rw,vwst]+GdcGucCduue[pv,rw,vswt])+1/2(-2GuGeCqqql[ws,vt,prwv]+GuGeCqqql[ws,vt,pwrv]-2GuGeCqqql[ws,vt,wprv])+1/2(GuGuhCqque[vp,vrst]+GdGdhCqque[vp,vrst])-GucGuCqque[pv,ws,rwvt]+1/2GeGdcCduql[wt,pv,vsrw]-1/2(2GdcGucCduue[rv,pw,vwst]+GdcGucCduue[rv,pw,vswt])+1/2(-2GuGeCqqql[ws,vt,rpwv]+GuGeCqqql[ws,vt,rwpv]-2GuGeCqqql[ws,vt,wrpv])+1/2(GuGuhCqque[vr,vpst]+GdGdhCqque[vr,vpst])+GuhGuCqque[vs,prvt]+GehGeCqque[vt,prsv];


\[Beta][qqql]=-(3g^2+1/3gp^2+4gs^2)Cqqql[prst]-4g^2(Cqqql[rpst]+Cqqql[srpt]+Cqqql[psrt])-4GecGucCqque[tv,sw,prwv]+2(GdcGucCduql[pv,rw,vwst]+GdcGucCduql[rv,pw,vwst])+1/2(GuGuhCqqql[vp,vrst]+GdGdhCqqql[vp,vrst])+1/2(GuGuhCqqql[vr,pvst]+GdGdhCqqql[vr,pvst])+1/2(GuGuhCqqql[vs,prvt]+GdGdhCqqql[vs,prvt])+1/2GeGehCqqql[vt,prsv];


\[Beta][duue]=-(2gp^2+4gs^2)Cduue[prst]-20/3gp^2Cduue[psrt]+4GuGeCduql[ws,vt,prwv]-8GdGuCqque[vp,wr,vwst]+GdhGdCduue[vp,vrst]+GuhGuCduue[vr,pvst]+GuhGuCduue[vs,prvt]+GehGeCduue[vt,prsv];


\[Beta][ll\[CurlyPhi]\[CurlyPhi]]=(2\[Lambda]-3g^2+2\[Gamma]H)WC[ll\[CurlyPhi]\[CurlyPhi]]-3/2(Cll\[CurlyPhi]\[CurlyPhi]GeGeh+GecGeTCll\[CurlyPhi]\[CurlyPhi]);
