(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* Note: we multiply the beta functions by Log(10) so that t = Subscript[Log, 10](\[Mu]) *)


(* Method 1: using Mathematica's NDSolve function *) 
If[
RGEsMethod==1,

run=RunRGEs[inputSMEFTrunner,tHIGH,tLOW];
Var=Parameters/.insertt/.SubRedundant;
];


(* Method 2: using leading log approximation *) 
If[
RGEsMethod==2,

\[Beta]Constant=RGEs/.inputSMEFTrunner;
cHIGH=Parameters/.inputSMEFTrunner;

run=Table[Parameters[[i]]->Log[10]\[Beta]Constant[[i]]/(16 Pi^2)(t-tHIGH)+cHIGH[[i]],{i,1,Length[Parameters]}];
Var=Parameters/.SubRedundantNot;
];
