(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(* Format for output real numbers *)
outR[x_]:=NumberForm[x,{7,6},NumberPadding->{"","0"},NumberFormat->(If[#3==="",#1,Row[{#1,"E",#3}]]&)];


(* Auxiliary functions to restrict the indices to specific numbers of generations *)
ToGens2F[x_,n1_,n2_]:=Select[x,(#[[1]]<=n1&&#[[2]]<=n2)&];
ToGens4F[x_,n1_,n2_,n3_,n4_]:=Select[x,(#[[1]]<=n1&&#[[2]]<=n2&&#[[3]]<=n3&&#[[4]]<=n4)&];


(* ::Input::Initialization:: *)
(* Indices for the independent WCs *)

(* 1 - 2F general 3x3 matrix *)
indices1={{1,1},{1,2},{1,3},{2,1},{2,2},{2,3},{3,1},{3,2},{3,3}};

(* 2 - 2F Hermitian matrix *)
indices2Re={{1,1},{1,2},{1,3},{2,2},{2,3},{3,3}};
indices2Im={{1,2},{1,3},{2,3}};

(* 3 - 2F symmetric matrix *)
indices3={{1,1},{1,2},{1,3},{2,2},{2,3},{3,3}};

(* 4 - 2F antisymmetric matrix *)
indices4={{1,2},{1,3},{2,3}};

(* 5 - 4F general 3x3x3x3 object *)
indices5={{1,1,1,1},{1,1,1,2},{1,1,1,3},{1,1,2,1},{1,1,2,2},{1,1,2,3},{1,1,3,1},{1,1,3,2},{1,1,3,3},{1,2,1,1},{1,2,1,2},{1,2,1,3},{1,2,2,1},{1,2,2,2},{1,2,2,3},{1,2,3,1},{1,2,3,2},{1,2,3,3},{1,3,1,1},{1,3,1,2},{1,3,1,3},{1,3,2,1},{1,3,2,2},{1,3,2,3},{1,3,3,1},{1,3,3,2},{1,3,3,3},{2,1,1,1},{2,1,1,2},{2,1,1,3},{2,1,2,1},{2,1,2,2},{2,1,2,3},{2,1,3,1},{2,1,3,2},{2,1,3,3},{2,2,1,1},{2,2,1,2},{2,2,1,3},{2,2,2,1},{2,2,2,2},{2,2,2,3},{2,2,3,1},{2,2,3,2},{2,2,3,3},{2,3,1,1},{2,3,1,2},{2,3,1,3},{2,3,2,1},{2,3,2,2},{2,3,2,3},{2,3,3,1},{2,3,3,2},{2,3,3,3},{3,1,1,1},{3,1,1,2},{3,1,1,3},{3,1,2,1},{3,1,2,2},{3,1,2,3},{3,1,3,1},{3,1,3,2},{3,1,3,3},{3,2,1,1},{3,2,1,2},{3,2,1,3},{3,2,2,1},{3,2,2,2},{3,2,2,3},{3,2,3,1},{3,2,3,2},{3,2,3,3},{3,3,1,1},{3,3,1,2},{3,3,1,3},{3,3,2,1},{3,3,2,2},{3,3,2,3},{3,3,3,1},{3,3,3,2},{3,3,3,3}};

(* 6 - 4F two identical XX currents non-singlets *)
indices6Re={{1,1,1,1},{1,1,1,2},{1,1,1,3},{1,1,2,2},{1,1,2,3},{1,1,3,3},{1,2,1,2},{1,2,1,3},{1,2,2,1},{1,2,2,2},{1,2,2,3},{1,2,3,1},{1,2,3,2},{1,2,3,3},{1,3,1,3},{1,3,2,2},{1,3,2,3},{1,3,3,1},{1,3,3,2},{1,3,3,3},{2,2,2,2},{2,2,2,3},{2,2,3,3},{2,3,2,3},{2,3,3,2},{2,3,3,3},{3,3,3,3}};
indices6Im={{1,1,1,2},{1,1,1,3},{1,1,2,3},{1,2,1,2},{1,2,1,3},{1,2,2,2},{1,2,2,3},{1,2,3,1},{1,2,3,2},{1,2,3,3},{1,3,1,3},{1,3,2,2},{1,3,2,3},{1,3,3,2},{1,3,3,3},{2,2,2,3},{2,3,2,3},{2,3,3,3}};

(* 7 - 4F two independent XX currents *)
indices7Re={{1,1,1,1},{1,1,1,2},{1,1,1,3},{1,1,2,2},{1,1,2,3},{1,1,3,3},{1,2,1,1},{1,2,1,2},{1,2,1,3},{1,2,2,1},{1,2,2,2},{1,2,2,3},{1,2,3,1},{1,2,3,2},{1,2,3,3},{1,3,1,1},{1,3,1,2},{1,3,1,3},{1,3,2,1},{1,3,2,2},{1,3,2,3},{1,3,3,1},{1,3,3,2},{1,3,3,3},{2,2,1,1},{2,2,1,2},{2,2,1,3},{2,2,2,2},{2,2,2,3},{2,2,3,3},{2,3,1,1},{2,3,1,2},{2,3,1,3},{2,3,2,1},{2,3,2,2},{2,3,2,3},{2,3,3,1},{2,3,3,2},{2,3,3,3},{3,3,1,1},{3,3,1,2},{3,3,1,3},{3,3,2,2},{3,3,2,3},{3,3,3,3}};
indices7Im={{1,1,1,2},{1,1,1,3},{1,1,2,3},{1,2,1,1},{1,2,1,2},{1,2,1,3},{1,2,2,1},{1,2,2,2},{1,2,2,3},{1,2,3,1},{1,2,3,2},{1,2,3,3},{1,3,1,1},{1,3,1,2},{1,3,1,3},{1,3,2,1},{1,3,2,2},{1,3,2,3},{1,3,3,1},{1,3,3,2},{1,3,3,3},{2,2,1,2},{2,2,1,3},{2,2,2,3},{2,3,1,1},{2,3,1,2},{2,3,1,3},{2,3,2,1},{2,3,2,2},{2,3,2,3},{2,3,3,1},{2,3,3,2},{2,3,3,3},{3,3,1,2},{3,3,1,3},{3,3,2,3}};

(* 8 - 4F two identical XX currents singlets *)
indices8Re={{1,1,1,1},{1,1,1,2},{1,1,1,3},{1,1,2,2},{1,1,2,3},{1,1,3,3},{1,2,1,2},{1,2,1,3},{1,2,2,2},{1,2,2,3},{1,2,3,2},{1,2,3,3},{1,3,1,3},{1,3,2,3},{1,3,3,3},{2,2,2,2},{2,2,2,3},{2,2,3,3},{2,3,2,3},{2,3,3,3},{3,3,3,3}};
indices8Im={{1,1,1,2},{1,1,1,3},{1,1,2,3},{1,2,1,2},{1,2,1,3},{1,2,2,2},{1,2,2,3},{1,2,3,2},{1,2,3,3},{1,3,1,3},{1,3,2,3},{1,3,3,3},{2,2,2,3},{2,3,2,3},{2,3,3,3}};

(* 9 - 4F symmetric current \[Times] general current *)
indices9={{1,1,1,1},{1,1,1,2},{1,1,1,3},{1,1,2,1},{1,1,2,2},{1,1,2,3},{1,1,3,1},{1,1,3,2},{1,1,3,3},{1,2,1,1},{1,2,1,2},{1,2,1,3},{1,2,2,1},{1,2,2,2},{1,2,2,3},{1,2,3,1},{1,2,3,2},{1,2,3,3},{1,3,1,1},{1,3,1,2},{1,3,1,3},{1,3,2,1},{1,3,2,2},{1,3,2,3},{1,3,3,1},{1,3,3,2},{1,3,3,3},{2,2,1,1},{2,2,1,2},{2,2,1,3},{2,2,2,1},{2,2,2,2},{2,2,2,3},{2,2,3,1},{2,2,3,2},{2,2,3,3},{2,3,1,1},{2,3,1,2},{2,3,1,3},{2,3,2,1},{2,3,2,2},{2,3,2,3},{2,3,3,1},{2,3,3,2},{2,3,3,3},{3,3,1,1},{3,3,1,2},{3,3,1,3},{3,3,2,1},{3,3,2,2},{3,3,2,3},{3,3,3,1},{3,3,3,2},{3,3,3,3}};

(* 10 - 4F antisymmetric current \[Times] general current *)
indices10={{1,2,1,1},{1,2,1,2},{1,2,1,3},{1,2,2,1},{1,2,2,2},{1,2,2,3},{1,2,3,1},{1,2,3,2},{1,2,3,3},{1,3,1,1},{1,3,1,2},{1,3,1,3},{1,3,2,1},{1,3,2,2},{1,3,2,3},{1,3,3,1},{1,3,3,2},{1,3,3,3},{2,3,1,1},{2,3,1,2},{2,3,1,3},{2,3,2,1},{2,3,2,2},{2,3,2,3},{2,3,3,1},{2,3,3,2},{2,3,3,3}};

(* 11 - 4F SMEFT special case qqql *)
indices11={{1,1,1,1},{1,1,1,2},{1,1,1,3},{1,1,2,1},{1,1,2,2},{1,1,2,3},{1,1,3,1},{1,1,3,2},{1,1,3,3},{1,2,1,1},{1,2,1,2},{1,2,1,3},{1,2,2,1},{1,2,2,2},{1,2,2,3},{1,2,3,1},{1,2,3,2},{1,2,3,3},{1,3,1,1},{1,3,1,2},{1,3,1,3},{1,3,2,1},{1,3,2,2},{1,3,2,3},{1,3,3,1},{1,3,3,2},{1,3,3,3},{2,1,2,1},{2,1,2,2},{2,1,2,3},{2,1,3,1},{2,1,3,2},{2,1,3,3},{2,2,2,1},{2,2,2,2},{2,2,2,3},{2,2,3,1},{2,2,3,2},{2,2,3,3},{2,3,1,1},{2,3,1,2},{2,3,1,3},{2,3,2,1},{2,3,2,2},{2,3,2,3},{2,3,3,1},{2,3,3,2},{2,3,3,3},{3,1,3,1},{3,1,3,2},{3,1,3,3},{3,2,3,1},{3,2,3,2},{3,2,3,3},{3,3,3,1},{3,3,3,2},{3,3,3,3}};

(* 12 - 4F LEFT special case \[CapitalDelta]L = 4 *)
indices12={{1,1,2,2},{1,1,3,3},{2,2,3,3},{1,1,2,3},{1,2,2,3},{1,2,3,3}};

(* 13 - 4F LEFT special cases dddSLL and dddSRR *) 
indices13={{1,2,1,1},{1,2,1,2},{1,2,1,3},{1,2,2,1},{1,2,2,2},{1,2,2,3},{1,2,3,1},{1,2,3,2},{1,2,3,3},{1,3,1,1},{1,3,1,2},{1,3,1,3},{1,3,2,1},{1,3,2,2},{1,3,2,3},{1,3,3,1},{1,3,3,2},{1,3,3,3},{2,3,1,2},{2,3,1,3},{2,3,2,2},{2,3,2,3},{2,3,3,2},{2,3,3,3}};


(* ::Input::Initialization:: *)
WriteScales[module_]:=Block[{},
Write[outfile,"Block SCALES"];
If[module=="SMEFTrunner",Write[outfile,1," ",HIGHSCALE,"\t","# UV scale [GeV]"];];
Write[outfile,2," ",EWSCALE,"\t","# EW scale [GeV]"];
If[module=="LEFTrunner",Write[outfile,3," ",LOWSCALE,"\t","# IR scale [GeV]"]; 
];
];


(* ::Input::Initialization:: *)
WriteOptions:=Block[{},
Write[outfile,"Block OPTIONS"];
Write[outfile,1," ",RGEsMethod,"\t","# RGEs method"];
Write[outfile,2," ",UseRGEsSM,"\t","# Use SM RGEs"];
Write[outfile,3," ",SMEFTLoopOrder,"\t","# SMEFT RGEs loop order"];
Write[outfile,4," ",LEFTLoopOrder,"\t","# LEFT RGEs loop order"];
Write[outfile,5," ",MatchingLoopOrder,"\t","# Matching loop order"];
];


(* ::Input::Initialization:: *)
WriteWC2F[nameblock_,name_,n_,cat_,ReIm_,n1_,n2_]:=Block[{},

Write[outfile,"Block "<>nameblock];
If[cat==1,indices=indices1;indicesIm=indices;];  (* general 3x3 matrix *)
If[cat==2&&ReIm==0,indices=indices2Re;]; (* Hermitian 3x3 matrix - Real part *)
If[cat==2&&ReIm==1,indices=indices2Re;indicesIm=indices2Im;]; (* Hermitian 3x3 matrix - Imaginary part *)
If[cat==3,indices=indices3;indicesIm=indices;];  (* symmetric 3x3 matrix *)
If[cat==4,indices=indices4;indicesIm=indices;];  (* antisymmetric 3x3 matrix *)

indices=ToGens2F[indices,n1,n2];
indicesIm=ToGens2F[indicesIm,n1,n2];

Do[
If[ReIm==0&&IntersectingQ[{{i,j}},indices],
k=Position[indices,{i,j}][[1,1]];
Write[outfile,i," ",j," ",outR[Re[dataOutput[[n-1+k]]]],"\t","# "<>name<>"["<>ToString[i]<>","<>ToString[j]<>"]"];
];
If[ReIm==1&&IntersectingQ[{{i,j}},indicesIm],
k=Position[indices,{i,j}][[1,1]];
Write[outfile,i," ",j," ",outR[Im[dataOutput[[n-1+k]]]],"\t","# "<>name<>"["<>ToString[i]<>","<>ToString[j]<>"]"];
];
,{i,1,3},{j,1,3}];
];


(* WriteWC2F SMEFT default *)
WriteWC2F[nameblock_,name_,n_,cat_,ReIm_]:=WriteWC2F[nameblock,name,n,cat,ReIm,3,3];


(* ::Input::Initialization:: *)
WriteWC4F[nameblock_,name_,n_,cat_,ReIm_,n1_,n2_,n3_,n4_]:=Block[{},

Write[outfile,"Block "<>nameblock];
If[cat==5,indices=indices5;indicesIm=indices;]; (* general 3x3x3x3 object *)
If[cat==6&&ReIm==0,indices=indices6Re;]; (* two identical XX currents non-singlets - Real part *)
If[cat==6&&ReIm==1,indices=indices6Re;indicesIm=indices6Im;]; (* two identical XX currents non-singlets - Imaginary part *)
If[cat==7&&ReIm==0,indices=indices7Re;]; (* two independent XX currents - Real part *)
If[cat==7&&ReIm==1,indices=indices7Re;indicesIm=indices7Im;]; (* two independent XX currents - Imaginary part *)
If[cat==8&&ReIm==0,indices=indices8Re;]; (* two identical XX currents singlets - Real part *)
If[cat==8&&ReIm==1,indices=indices8Re;indicesIm=indices8Im;]; (* two identical XX currents singlets - Imaginary part *)
If[cat==9,indices=indices9;indicesIm=indices;]; (* symmetric current \[Times] general current *)
If[cat==10,indices=indices10;indicesIm=indices;]; (* antisymmetric current \[Times] general current *)
If[cat==11,indices=indices11;indicesIm=indices;]; (* SMEFT special case qqql *)
If[cat==12,indices=indices12;indicesIm=indices;]; (* LEFT special case \[CapitalDelta]L = 4 *)
If[cat==13,indices=indices13;indicesIm=indices;]; (* LEFT special cases dddSLL and dddSRR *)

indices=ToGens4F[indices,n1,n2,n3,n4];
If[ReIm==1,indicesIm=ToGens4F[indicesIm,n1,n2,n3,n4]];

Do[
If[ReIm==0&&IntersectingQ[{{p,r,s,m}},indices],
k=Position[indices,{p,r,s,m}][[1,1]];
Write[outfile,p," ",r," ",s," ",m," ",outR[Re[dataOutput[[n-1+k]]]],"\t","# "<>name<>"["<>ToString[p]<>","<>ToString[r]<>","<>ToString[s]<>","<>ToString[m]<>"]"];
];
If[ReIm==1&&IntersectingQ[{{p,r,s,m}},indicesIm],
k=Position[indices,{p,r,s,m}][[1,1]];
Write[outfile,p," ",r," ",s," ",m," ",outR[Im[dataOutput[[n-1+k]]]],"\t","# "<>name<>"["<>ToString[p]<>","<>ToString[r]<>","<>ToString[s]<>","<>ToString[m]<>"]"];
];
,{p,1,3},{r,1,3},{s,1,3},{m,1,3}];
];


(* WriteWC4F SMEFT default *)
WriteWC4F[nameblock_,name_,n_,cat_,ReIm_]:=WriteWC4F[nameblock,name,n,cat,ReIm,3,3,3,3];


(* ::Input::Initialization:: *)
WriteGaugeSMEFT:=Block[{},
Write[outfile,"Block GAUGE"];
Write[outfile,1," ",outR[dataOutput[[SMEFTFindParameter[g]//First]]],"\t","# g"];
Write[outfile,2," ",outR[dataOutput[[SMEFTFindParameter[gp]//First]]],"\t","# gp"];
Write[outfile,3," ",outR[dataOutput[[SMEFTFindParameter[gs]//First]]],"\t","# gs"];
];


(* ::Input::Initialization:: *)
WriteScalar:=Block[{},
Write[outfile,"Block SCALAR"];
Write[outfile,1," ",outR[dataOutput[[SMEFTFindParameter[\[Lambda]]//First]]],"\t","# lambda"];
Write[outfile,2," ",outR[dataOutput[[SMEFTFindParameter[m2]//First]]],"\t","# m2 [GeV^2]"];
];


WriteYukawa[nameblock_,name_,n_,ReIm_]:=Block[{},

Write[outfile,"Block "<>nameblock];

indices=indices1;
Do[
i=indices[[k,1]];
j=indices[[k,2]];
If[ReIm==0,
Write[outfile,i," ",j," ",outR[Re[dataOutput[[n-1+k]]]],"\t","# "<>name<>"("<>ToString[i]<>","<>ToString[j]<>")"];
];
If[ReIm==1&&IntersectingQ[{{i,j}},indices],
Write[outfile,i," ",j," ",outR[Im[dataOutput[[n-1+k]]]],"\t","# "<>name<>"("<>ToString[i]<>","<>ToString[j]<>")"];
];
,{k,1,Length[indices]}];
];


WriteThetaSMEFT:=Block[{},
Write[outfile,"Block THETA"];
Write[outfile,1," ",outR[dataOutput[[SMEFTFindParameter[\[Theta]]//First]]],"\t","# theta"];
Write[outfile,2," ",outR[dataOutput[[SMEFTFindParameter[\[Theta]p]//First]]],"\t","# thetap"];
Write[outfile,3," ",outR[dataOutput[[SMEFTFindParameter[\[Theta]s]//First]]],"\t","# thetas"];
];


(* ::Input::Initialization:: *)
WriteSM:=Block[{},

WriteGaugeSMEFT;
WriteScalar;
WriteYukawa["GU","Gamma_u",SMEFTFindParameter[Gu]//First,0]; 
WriteYukawa["IMGU","Gamma_u",SMEFTFindParameter[Gu]//First,1];
WriteYukawa["GD","Gamma_d",SMEFTFindParameter[Gd]//First,0]; 
WriteYukawa["IMGD","Gamma_d",SMEFTFindParameter[Gd]//First,1];
WriteYukawa["GE","Gamma_e",SMEFTFindParameter[Ge]//First,0]; 
WriteYukawa["IMGE","Gamma_e",SMEFTFindParameter[Ge]//First,1];
WriteThetaSMEFT;

];


(* ::Input::Initialization:: *)
WriteWC1SMEFT:=Block[{},
Write[outfile,"Block WC1"];
Write[outfile,1," ",outR[Re[dataOutput[[SMEFTFindParameter[CG]//First]]]],"\t","# G"];
Write[outfile,2," ",outR[Re[dataOutput[[SMEFTFindParameter[CGtilde]//First]]]],"\t","# G tilde"];
Write[outfile,3," ",outR[Re[dataOutput[[SMEFTFindParameter[CW]//First]]]],"\t","# W"];
Write[outfile,4," ",outR[Re[dataOutput[[SMEFTFindParameter[CWtilde]//First]]]],"\t","# W tilde"];
];


(* ::Input::Initialization:: *)
WriteWC2:=Block[{},
Write[outfile,"Block WC2"];
Write[outfile,1," ",outR[Re[dataOutput[[SMEFTFindParameter[CH]//First]]]],"\t","# H"];
];


(* ::Input::Initialization:: *)
WriteWC3:=Block[{},
Write[outfile,"Block WC3"];
Write[outfile,1," ",outR[Re[dataOutput[[SMEFTFindParameter[CHbox]//First]]]],"\t","# HBox"];
Write[outfile,2," ",outR[Re[dataOutput[[SMEFTFindParameter[CHD]//First]]]],"\t","# HD"];
];


(* ::Input::Initialization:: *)
WriteWC4:=Block[{},
Write[outfile,"Block WC4"];
Write[outfile,1," ",outR[Re[dataOutput[[SMEFTFindParameter[CHG]//First]]]],"\t","# HG"];
Write[outfile,2," ",outR[Re[dataOutput[[SMEFTFindParameter[CHB]//First]]]],"\t","# HB"];
Write[outfile,3," ",outR[Re[dataOutput[[SMEFTFindParameter[CHW]//First]]]],"\t","# HW"];
Write[outfile,4," ",outR[Re[dataOutput[[SMEFTFindParameter[CHWB]//First]]]],"\t","# HWB"];
Write[outfile,5," ",outR[Re[dataOutput[[SMEFTFindParameter[CHGtilde]//First]]]],"\t","# HGtilde"];
Write[outfile,6," ",outR[Re[dataOutput[[SMEFTFindParameter[CHBtilde]//First]]]],"\t","# HBtilde"];
Write[outfile,7," ",outR[Re[dataOutput[[SMEFTFindParameter[CHWtilde]//First]]]],"\t","# HWtilde"];
Write[outfile,8," ",outR[Re[dataOutput[[SMEFTFindParameter[CHWtildeB]//First]]]],"\t","# HWtildeB"];
];


(* ::Input::Initialization:: *)
Write0FSMEFT:=Block[{},
WriteWC1SMEFT;
WriteWC2;
WriteWC3;
WriteWC4;
];


(* ::Input::Initialization:: *)
Write2FSMEFT:=Block[{},

(* \[Psi]^2\[CurlyPhi]^3 *)
WriteWC2F["WCuH","uH",SMEFTFindParameter[CuH]//First,1,0]; 
WriteWC2F["IMWCuH","uH",SMEFTFindParameter[CuH]//First,1,1];
WriteWC2F["WCdH","dH",SMEFTFindParameter[CdH]//First,1,0];
WriteWC2F["IMWCdH","dH",SMEFTFindParameter[CdH]//First,1,1];
WriteWC2F["WCeH","eH",SMEFTFindParameter[CeH]//First,1,0];
WriteWC2F["IMWCeH","eH",SMEFTFindParameter[CeH]//First,1,1];

(* \[Psi]^2X \[CurlyPhi] *)
WriteWC2F["WCeW","eW",SMEFTFindParameter[CeW]//First,1,0]; 
WriteWC2F["IMWCeW","eW",SMEFTFindParameter[CeW]//First,1,1];
WriteWC2F["WCeB","eB",SMEFTFindParameter[CeB]//First,1,0]; 
WriteWC2F["IMWCeB","eB",SMEFTFindParameter[CeB]//First,1,1];
WriteWC2F["WCuG","uG",SMEFTFindParameter[CuG]//First,1,0]; 
WriteWC2F["IMWCuG","uG",SMEFTFindParameter[CuG]//First,1,1];
WriteWC2F["WCuW","uW",SMEFTFindParameter[CuW]//First,1,0]; 
WriteWC2F["IMWCuW","uW",SMEFTFindParameter[CuW]//First,1,1];
WriteWC2F["WCuB","uB",SMEFTFindParameter[CuB]//First,1,0]; 
WriteWC2F["IMWCuB","uB",SMEFTFindParameter[CuB]//First,1,1];
WriteWC2F["WCdG","dG",SMEFTFindParameter[CdG]//First,1,0]; 
WriteWC2F["IMWCdG","dG",SMEFTFindParameter[CdG]//First,1,1];
WriteWC2F["WCdW","dW",SMEFTFindParameter[CdW]//First,1,0]; 
WriteWC2F["IMWCdW","dW",SMEFTFindParameter[CdW]//First,1,1];
WriteWC2F["WCdB","dB",SMEFTFindParameter[CdB]//First,1,0]; 
WriteWC2F["IMWCdB","dB",SMEFTFindParameter[CdB]//First,1,1];

(* \[Psi]^2\[CurlyPhi]^2D *)
WriteWC2F["WCHl1","Hl1",SMEFTFindParameter[CHl1]//First,2,0]; 
WriteWC2F["IMWCHl1","Hl1",SMEFTFindParameter[CHl1]//First,2,1];
WriteWC2F["WCHl3","Hl3",SMEFTFindParameter[CHl3]//First,2,0]; 
WriteWC2F["IMWCHl3","Hl3",SMEFTFindParameter[CHl3]//First,2,1];
WriteWC2F["WCHe","He",SMEFTFindParameter[CHe]//First,2,0]; 
WriteWC2F["IMWCHe","He",SMEFTFindParameter[CHe]//First,2,1];
WriteWC2F["WCHq1","Hq1",SMEFTFindParameter[CHq1]//First,2,0]; 
WriteWC2F["IMWCHq1","Hq1",SMEFTFindParameter[CHq1]//First,2,1];
WriteWC2F["WCHq3","Hq3",SMEFTFindParameter[CHq3]//First,2,0]; 
WriteWC2F["IMWCHq3","Hq3",SMEFTFindParameter[CHq3]//First,2,1];
WriteWC2F["WCHu","Hu",SMEFTFindParameter[CHu]//First,2,0]; 
WriteWC2F["IMWCHu","Hu",SMEFTFindParameter[CHu]//First,2,1];
WriteWC2F["WCHd","Hd",SMEFTFindParameter[CHd]//First,2,0]; 
WriteWC2F["IMWCHd","Hd",SMEFTFindParameter[CHd]//First,2,1];
WriteWC2F["WCHud","Hud",SMEFTFindParameter[CHud]//First,1,0]; 
WriteWC2F["IMWCHud","Hud",SMEFTFindParameter[CHud]//First,1,1];

];


(* ::Input::Initialization:: *)
Write4FSMEFT:=Block[{},

(* LL LL *)
WriteWC4F["WCll","ll",SMEFTFindParameter[Cll]//First,6,0]; 
WriteWC4F["IMWCll","ll",SMEFTFindParameter[Cll]//First,6,1];
WriteWC4F["WCqq1","qq1",SMEFTFindParameter[Cqq1]//First,6,0]; 
WriteWC4F["IMWCqq1","qq1",SMEFTFindParameter[Cqq1]//First,6,1];
WriteWC4F["WCqq3","qq3",SMEFTFindParameter[Cqq3]//First,6,0]; 
WriteWC4F["IMWCqq3","qq3",SMEFTFindParameter[Cqq3]//First,6,1];
WriteWC4F["WClq1","lq1",SMEFTFindParameter[Clq1]//First,7,0]; 
WriteWC4F["IMWClq1","lq1",SMEFTFindParameter[Clq1]//First,7,1];
WriteWC4F["WClq3","lq3",SMEFTFindParameter[Clq3]//First,7,0]; 
WriteWC4F["IMWClq3","lq3",SMEFTFindParameter[Clq3]//First,7,1];

(* RR RR *)
WriteWC4F["WCee","ee",SMEFTFindParameter[Cee]//First,8,0]; 
WriteWC4F["IMWCee","ee",SMEFTFindParameter[Cee]//First,8,1];
WriteWC4F["WCuu","uu",SMEFTFindParameter[Cuu]//First,6,0]; 
WriteWC4F["IMWCuu","uu",SMEFTFindParameter[Cuu]//First,6,1];
WriteWC4F["WCdd","dd",SMEFTFindParameter[Cdd]//First,6,0]; 
WriteWC4F["IMWCdd","dd",SMEFTFindParameter[Cdd]//First,6,1];
WriteWC4F["WCeu","eu",SMEFTFindParameter[Ceu]//First,7,0]; 
WriteWC4F["IMWCeu","eu",SMEFTFindParameter[Ceu]//First,7,1];
WriteWC4F["WCed","ed",SMEFTFindParameter[Ced]//First,7,0]; 
WriteWC4F["IMWCed","ed",SMEFTFindParameter[Ced]//First,7,1];
WriteWC4F["WCud1","ud1",SMEFTFindParameter[Ced]//First,7,0]; 
WriteWC4F["IMWCud1","ud1",SMEFTFindParameter[Cud1]//First,7,1];
WriteWC4F["WCud8","ud8",SMEFTFindParameter[Cud1]//First,7,0]; 
WriteWC4F["IMWCud8","ud8",SMEFTFindParameter[Cud8]//First,7,1];

(* LL RR *)
WriteWC4F["WCle","le",SMEFTFindParameter[Cle]//First,7,0]; 
WriteWC4F["IMWCle","le",SMEFTFindParameter[Cle]//First,7,1];
WriteWC4F["WClu","lu",SMEFTFindParameter[Clu]//First,7,0]; 
WriteWC4F["IMWClu","lu",SMEFTFindParameter[Clu]//First,7,1];
WriteWC4F["WCld","ld",SMEFTFindParameter[Cld]//First,7,0]; 
WriteWC4F["IMWCld","ld",SMEFTFindParameter[Cld]//First,7,1];
WriteWC4F["WCqe","qe",SMEFTFindParameter[Cqe]//First,7,0]; 
WriteWC4F["IMWCqe","qe",SMEFTFindParameter[Cqe]//First,7,1];
WriteWC4F["WCqu1","qu1",SMEFTFindParameter[Cqu1]//First,7,0]; 
WriteWC4F["IMWCqu1","qu1",SMEFTFindParameter[Cqu1]//First,7,1];
WriteWC4F["WCqu8","qu8",SMEFTFindParameter[Cqu8]//First,7,0]; 
WriteWC4F["IMWCqu8","qu8",SMEFTFindParameter[Cqu8]//First,7,1];
WriteWC4F["WCqd1","qd1",SMEFTFindParameter[Cqd1]//First,7,0]; 
WriteWC4F["IMWCqd1","qd1",SMEFTFindParameter[Cqd1]//First,7,1];
WriteWC4F["WCqd8","qd8",SMEFTFindParameter[Cqd8]//First,7,0]; 
WriteWC4F["IMWCqd8","qd8",SMEFTFindParameter[Cqd8]//First,7,1];

(* LR RL *)
WriteWC4F["WCledq","ledq",SMEFTFindParameter[Cledq]//First,5,0]; 
WriteWC4F["IMWCledq","ledq",SMEFTFindParameter[Cledq]//First,5,1];

(* LR LR *)
WriteWC4F["WCquqd1","quqd1",SMEFTFindParameter[Cquqd1]//First,5,0]; 
WriteWC4F["IMWCquqd1","quqd1",SMEFTFindParameter[Cquqd1]//First,5,1];
WriteWC4F["WCquqd8","quqd8",SMEFTFindParameter[Cquqd8]//First,5,0]; 
WriteWC4F["IMWCquqd8","quqd8",SMEFTFindParameter[Cquqd8]//First,5,1];
WriteWC4F["WClequ1","lequ1",SMEFTFindParameter[Clequ1]//First,5,0]; 
WriteWC4F["IMWClequ1","lequ1",SMEFTFindParameter[Clequ1]//First,5,1];
WriteWC4F["WClequ3","lequ3",SMEFTFindParameter[Clequ3]//First,5,0]; 
WriteWC4F["IMWClequ3","lequ3",SMEFTFindParameter[Clequ3]//First,5,1];

(* B-violating *)
WriteWC4F["WCduql","duql",SMEFTFindParameter[Cduql]//First,5,0]; 
WriteWC4F["IMWCduql","duql",SMEFTFindParameter[Cduql]//First,5,1];
WriteWC4F["WCqque","qque",SMEFTFindParameter[Cqque]//First,9,0]; 
WriteWC4F["IMWCqque","qque",SMEFTFindParameter[Cqque]//First,9,1];
WriteWC4F["WCqqql","qqql",SMEFTFindParameter[Cqqql]//First,11,0]; 
WriteWC4F["IMWCqqql","qqql",SMEFTFindParameter[Cqqql]//First,11,1];
WriteWC4F["WCduue","duue",SMEFTFindParameter[Cduue]//First,5,0]; 
WriteWC4F["IMWCduue","duue",SMEFTFindParameter[Cduue]//First,5,1];

];


(* ::Input::Initialization:: *)
Writedim5:=Block[{},

(* dim-5 *)
WriteWC2F["WCllHH","llHH",SMEFTFindParameter[CllHH]//First,3,0]; 
WriteWC2F["IMWCllHH","llHH",SMEFTFindParameter[CllHH]//First,3,1];

];


(* ::Input::Initialization:: *)
WriteGaugeLEFT:=Block[{},
Write[outfile,"Block GAUGE"];
Write[outfile,1," ",outR[dataOutput[[LEFTFindParameter[gQCD]//First]]],"\t","# gQCD"];
Write[outfile,2," ",outR[dataOutput[[LEFTFindParameter[eQED]//First]]],"\t","# eQED"];
];


WriteThetaLEFT:=Block[{},
Write[outfile,"Block THETA"];
Write[outfile,1," ",outR[dataOutput[[LEFTFindParameter[\[Theta]QCD]//First]]],"\t","# thetaQCD"];
Write[outfile,2," ",outR[dataOutput[[LEFTFindParameter[\[Theta]QED]//First]]],"\t","# thetaQED"];
];


(* ::Input::Initialization:: *)
WriteMass[nameblock_,name_,n_,ReIm_,type_,n1_,n2_]:=Block[{},

Write[outfile,"Block "<>nameblock];

If[type=="Dirac",indices=indices1;];
If[type=="Majorana",indices=indices3;];

indices=ToGens2F[indices,n1,n2];

Do[
i=indices[[k,1]];
j=indices[[k,2]];
If[ReIm==0,
Write[outfile,i," ",j," ",outR[Re[dataOutput[[n-1+k]]]],"\t","# "<>name<>"("<>ToString[i]<>","<>ToString[j]<>")"];
];
If[ReIm==1&&IntersectingQ[{{i,j}},indices],
Write[outfile,i," ",j," ",outR[Im[dataOutput[[n-1+k]]]],"\t","# "<>name<>"("<>ToString[i]<>","<>ToString[j]<>")"];
];
,{k,1,Length[indices]}];
];


WriteQCDQED:=Block[{},

WriteGaugeLEFT;
WriteThetaLEFT;
WriteMass["MN","Mn",LEFTFindParameter[M\[Nu]]//First,0,"Majorana",n\[Nu],n\[Nu]]; 
WriteMass["IMMN","Mn",LEFTFindParameter[M\[Nu]]//First,1,"Majorana",n\[Nu],n\[Nu]];
WriteMass["ME","Me",LEFTFindParameter[Me]//First,0,"Dirac",ne,ne]; 
WriteMass["IMME","Me",LEFTFindParameter[Me]//First,1,"Dirac",ne,ne];
WriteMass["MU","Mu",LEFTFindParameter[Mu]//First,0,"Dirac",nu,nu]; 
WriteMass["IMMU","Mu",LEFTFindParameter[Mu]//First,1,"Dirac",nu,nu];
WriteMass["MD","Md",LEFTFindParameter[Md]//First,0,"Dirac",nd,nd]; 
WriteMass["IMMD","Md",LEFTFindParameter[Md]//First,1,"Dirac",nd,nd];

];


(* ::Input::Initialization:: *)
WriteWC1LEFT:=Block[{},
Write[outfile,"Block WC1"];
Write[outfile,1," ",outR[Re[dataOutput[[LEFTFindParameter[LG]//First]]]],"\t","# G"];
Write[outfile,2," ",outR[Re[dataOutput[[LEFTFindParameter[LGtilde]//First]]]],"\t","# G tilde"];
];


(* ::Input::Initialization:: *)
Write0FLEFT:=Block[{},
WriteWC1LEFT;
];


(* ::Input::Initialization:: *)
Write2FLEFT:=Block[{},

(* (\[Nu]\[Nu])X *)
WriteWC2F["WCNGAMMA","ngamma",LEFTFindParameter[L\[Nu]\[Gamma]]//First,4,0,n\[Nu],n\[Nu]]; 
WriteWC2F["IMWCNGAMMA","ngamma",LEFTFindParameter[L\[Nu]\[Gamma]]//First,4,1,n\[Nu],n\[Nu]];

(* (LR)X *)
WriteWC2F["WCEGAMMA","egamma",LEFTFindParameter[Le\[Gamma]]//First,1,0,n\[Nu],n\[Nu]];WriteWC2F["IMWCEGAMMA","egamma",LEFTFindParameter[Le\[Gamma]]//First,1,1,n\[Nu],n\[Nu]];
WriteWC2F["WCuGAMMA","ugamma",LEFTFindParameter[Lu\[Gamma]]//First,1,0,nu,nu]; 
WriteWC2F["IMWCuGAMMA","ugamma",LEFTFindParameter[Lu\[Gamma]]//First,1,1,nu,nu];
WriteWC2F["WCdGAMMA","dgamma",LEFTFindParameter[Ld\[Gamma]]//First,1,0,nd,nd]; 
WriteWC2F["IMWCdGAMMA","dgamma",LEFTFindParameter[Ld\[Gamma]]//First,1,1,nd,nd];
WriteWC2F["WCuG","ug",LEFTFindParameter[LuG]//First,1,0,nu,nu]; 
WriteWC2F["IMWCuG","ug",LEFTFindParameter[LuG]//First,1,1,nu,nu];
WriteWC2F["WCdG","dg",LEFTFindParameter[LdG]//First,1,0,nd,nd]; 
WriteWC2F["IMWCdG","dg",LEFTFindParameter[LdG]//First,1,1,nd,nd];

];


(* ::Input::Initialization:: *)
Write4FLEFT:=Block[{},

(* LL LL *)
WriteWC4F["WCNNVLL","nnvll",LEFTFindParameter[L\[Nu]\[Nu]VLL]//First,8,0,n\[Nu],n\[Nu],n\[Nu],n\[Nu]]; 
WriteWC4F["IMWCNNVLL","nnvll",LEFTFindParameter[L\[Nu]\[Nu]VLL]//First,8,1,n\[Nu],n\[Nu],n\[Nu],n\[Nu]];
WriteWC4F["WCeeVLL","eevll",LEFTFindParameter[LeeVLL]//First,8,0,ne,ne,ne,ne]; 
WriteWC4F["IMWCeeVLL","eevll",LEFTFindParameter[LeeVLL]//First,8,1,ne,ne,ne,ne];
WriteWC4F["WCNEVLL","nevll",LEFTFindParameter[L\[Nu]eVLL]//First,5,0,n\[Nu],n\[Nu],ne,ne]; 
WriteWC4F["IMWCNEVLL","nevll",LEFTFindParameter[L\[Nu]eVLL]//First,5,1,n\[Nu],n\[Nu],ne,ne];
WriteWC4F["WCNUVLL","nuvll",LEFTFindParameter[L\[Nu]uVLL]//First,5,0,n\[Nu],n\[Nu],nu,nu]; 
WriteWC4F["IMWCNUVLL","nuvll",LEFTFindParameter[L\[Nu]uVLL]//First,5,1,n\[Nu],n\[Nu],nu,nu];
WriteWC4F["WCNDVLL","ndvll",LEFTFindParameter[L\[Nu]dVLL]//First,5,0,n\[Nu],n\[Nu],nd,nd]; 
WriteWC4F["IMWCNDVLL","ndvll",LEFTFindParameter[L\[Nu]dVLL]//First,5,1,n\[Nu],n\[Nu],nd,nd];
WriteWC4F["WCeuVLL","euvll",LEFTFindParameter[LeuVLL]//First,5,0,ne,ne,nu,nu]; 
WriteWC4F["IMWCeuVLL","euvll",LEFTFindParameter[LeuVLL]//First,5,1,ne,ne,nu,nu];
WriteWC4F["WCedVLL","edvll",LEFTFindParameter[LedVLL]//First,5,0,ne,ne,nd,nd]; 
WriteWC4F["IMWCedVLL","edvll",LEFTFindParameter[LedVLL]//First,5,1,ne,ne,nd,nd];
WriteWC4F["WCNEDUVLL","neduvll",LEFTFindParameter[L\[Nu]eduVLL]//First,5,0,n\[Nu],ne,nd,nu]; 
WriteWC4F["IMWCNEDUVLL","neduvll",LEFTFindParameter[L\[Nu]eduVLL]//First,5,1,n\[Nu],ne,nd,nu];
WriteWC4F["WCuuVLL","uuvll",LEFTFindParameter[LuuVLL]//First,6,0,nu,nu,nu,nu]; 
WriteWC4F["IMWCuuVLL","uuvll",LEFTFindParameter[LuuVLL]//First,6,1,nu,nu,nu,nu];
WriteWC4F["WCddVLL","ddvll",LEFTFindParameter[LddVLL]//First,6,0,nd,nd,nd,nd]; 
WriteWC4F["IMWCddVLL","ddvll",LEFTFindParameter[LddVLL]//First,6,1,nd,nd,nd,nd];
WriteWC4F["WCUDV1LL","udv1ll",LEFTFindParameter[LudV1LL]//First,5,0,nu,nu,nd,nd]; 
WriteWC4F["IMWCUDV1LL","udv1ll",LEFTFindParameter[LudV1LL]//First,5,1,nu,nu,nd,nd];
WriteWC4F["WCUDV8LL","udv8ll",LEFTFindParameter[LudV8LL]//First,5,0,nu,nu,nd,nd]; 
WriteWC4F["IMWCUDV8LL","udv8ll",LEFTFindParameter[LudV8LL]//First,5,1,nu,nu,nd,nd];

(* RR RR *)

WriteWC4F["WCeeVRR","eevrr",LEFTFindParameter[LeeVRR]//First,8,0,ne,ne,ne,ne]; 
WriteWC4F["IMWCeeVRR","eevrr",LEFTFindParameter[LeeVRR]//First,8,1,ne,ne,ne,ne];
WriteWC4F["WCeuVRR","euvrr",LEFTFindParameter[LeuVRR]//First,5,0,ne,ne,nu,nu]; 
WriteWC4F["IMWCeuVRR","euvrr",LEFTFindParameter[LeuVRR]//First,5,1,ne,ne,nu,nu];
WriteWC4F["WCedVRR","edvrr",LEFTFindParameter[LedVRR]//First,5,0,ne,ne,nd,nd]; 
WriteWC4F["IMWCedVRR","edvrr",LEFTFindParameter[LedVRR]//First,5,1,ne,ne,nd,nd];
WriteWC4F["WCuuVRR","uuvrr",LEFTFindParameter[LuuVRR]//First,6,0,nu,nu,nu,nu]; 
WriteWC4F["IMWCuuVRR","uuvrr",LEFTFindParameter[LuuVRR]//First,6,1,nu,nu,nu,nu];
WriteWC4F["WCddVRR","ddvrr",LEFTFindParameter[LddVRR]//First,6,0,nd,nd,nd,nd]; 
WriteWC4F["IMWCddVRR","ddvrr",LEFTFindParameter[LddVRR]//First,6,1,nd,nd,nd,nd];
WriteWC4F["WCUDV1RR","udv1rr",LEFTFindParameter[LudV1RR]//First,5,0,nu,nu,nd,nd]; 
WriteWC4F["IMWCUDV1RR","udv1rr",LEFTFindParameter[LudV1RR]//First,5,1,nu,nu,nd,nd];
WriteWC4F["WCUDV8RR","udv8rr",LEFTFindParameter[LudV8RR]//First,5,0,nu,nu,nd,nd]; 
WriteWC4F["IMWCUDV8RR","udv8rr",LEFTFindParameter[LudV8RR]//First,5,1,nu,nu,nd,nd];

(* LL RR *)
WriteWC4F["WCNEVLR","nevlr",LEFTFindParameter[L\[Nu]eVLR]//First,5,0,n\[Nu],n\[Nu],ne,ne]; 
WriteWC4F["IMWCNEVLR","nevlr",LEFTFindParameter[L\[Nu]eVLR]//First,5,1,n\[Nu],n\[Nu],ne,ne];
WriteWC4F["WCeeVLR","neelr",LEFTFindParameter[LeeVLR]//First,5,0,ne,ne,ne,ne]; 
WriteWC4F["IMWCeeVLR","neelr",LEFTFindParameter[LeeVLR]//First,5,1,ne,ne,ne,ne];
WriteWC4F["WCNUVLR","nuvlr",LEFTFindParameter[L\[Nu]uVLR]//First,5,0,n\[Nu],n\[Nu],nu,nu]; 
WriteWC4F["IMWCNUVLR","nuvlr",LEFTFindParameter[L\[Nu]uVLR]//First,5,1,n\[Nu],n\[Nu],nu,nu];
WriteWC4F["WCNDVLR","ndvlr",LEFTFindParameter[L\[Nu]dVLR]//First,5,0,n\[Nu],n\[Nu],nd,nd]; 
WriteWC4F["IMWCNDVLR","ndvlr",LEFTFindParameter[L\[Nu]dVLR]//First,5,1,n\[Nu],n\[Nu],nd,nd];
WriteWC4F["WCeuVLR","euvlr",LEFTFindParameter[LeuVLR]//First,5,0,ne,ne,nu,nu]; 
WriteWC4F["IMWCeuVLR","euvlr",LEFTFindParameter[LeuVLR]//First,5,1,ne,ne,nu,nu];
WriteWC4F["WCedVLR","edvlr",LEFTFindParameter[LedVLR]//First,5,0,ne,ne,nd,nd]; 
WriteWC4F["IMWCedVLR","edvlr",LEFTFindParameter[LedVLR]//First,5,1,ne,ne,nd,nd];
WriteWC4F["WCUEVLR","uevlr",LEFTFindParameter[LueVLR]//First,5,0,nu,nu,ne,ne]; 
WriteWC4F["IMWCUEVLR","uevlr",LEFTFindParameter[LueVLR]//First,5,1,nu,nu,ne,ne];
WriteWC4F["WCDEVLR","devlr",LEFTFindParameter[LdeVLR]//First,5,0,nd,nd,ne,ne]; 
WriteWC4F["IMWCDEVLR","devlr",LEFTFindParameter[LdeVLR]//First,5,1,nd,nd,ne,ne];
WriteWC4F["WCNEDUVLR","neduvlr",LEFTFindParameter[L\[Nu]eduVLR]//First,5,0,n\[Nu],ne,nd,nu]; 
WriteWC4F["IMWCNEDUVLR","neduvlr",LEFTFindParameter[L\[Nu]eduVLR]//First,5,1,n\[Nu],ne,nd,nu];
WriteWC4F["WCuuV1LR","uuv1lr",\!\(TraditionalForm\`LEFTFindParameter[LuuV1LR] // First\),5,0,nu,nu,nu,nu]; 
WriteWC4F["IMWCuuV1LR","uuv1lr",\!\(TraditionalForm\`LEFTFindParameter[LuuV1LR] // First\),5,1,nu,nu,nu,nu];
WriteWC4F["WCuuV8LR","uuv8lr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuuV8LR] // First\)\),5,0,nu,nu,nu,nu]; 
WriteWC4F["IMWCuuV8LR","uuv8lr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuuV8LR] // First\)\),5,1,nu,nu,nu,nu];
WriteWC4F["WCUDV1LR","udv1lr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudV1LR] // First\)\),5,0,nu,nu,nd,nd]; 
WriteWC4F["IMWCUDV1LR","udv1lr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudV1LR] // First\)\),5,1,nu,nu,nd,nd];
WriteWC4F["WCUDV8LR","udv8lr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudV8LR] // First\)\)\),5,0,nu,nu,nd,nd]; 
WriteWC4F["IMWCUDV8LR","udv8lr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudV8LR] // First\)\)\),5,1,nu,nu,nd,nd];
WriteWC4F["WCDUV1LR","duv1lr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LduV1LR] // First\)\),5,0,nd,nd,nu,nu]; 
WriteWC4F["IMWCDUV1LR","duv1lr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LduV1LR] // First\)\),5,1,nd,nd,nu,nu];
WriteWC4F["WCDUV8LR","duv8lr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LduV8LR] // First\)\)\),5,0,nd,nd,nu,nu]; 
WriteWC4F["IMWCDUV8LR","duv8lr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LduV8LR] // First\)\)\),5,1,nd,nd,nu,nu];
WriteWC4F["WCddV1LR","ddv1lr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LddV1LR] // First\)\)\),5,0,nd,nd,nd,nd]; 
WriteWC4F["IMWCddV1LR","ddv1lr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LddV1LR] // First\)\)\),5,1,nd,nd,nd,nd];
WriteWC4F["WCddV8LR","ddv8lr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LddV8LR] // First\)\)\)\),5,0,nd,nd,nd,nd]; 
WriteWC4F["IMWCddV8LR","ddv8lr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LddV8LR] // First\)\)\)\),5,1,nd,nd,nd,nd];
WriteWC4F["WCUDDUV1LR","udduv1lr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudduV1LR] // First\)\)\)\)\),5,0,nu,nd,nd,nu]; 
WriteWC4F["IMWCUDDUV1LR","udduv1lr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudduV1LR] // First\)\)\)\)\),5,1,nu,nd,nd,nu];
WriteWC4F["WCUDDUV8LR","udduv8lr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudduV8LR] // First\)\)\)\)\)\),5,0,nu,nd,nd,nu]; 
WriteWC4F["IMWCUDDUV8LR","udduv8lr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudduV8LR] // First\)\)\)\)\)\),5,1,nu,nd,nd,nu];

(* LR LR *)
WriteWC4F["WCeeSRR","eesrr",\!\(TraditionalForm\`LEFTFindParameter[LeeSRR] // First\),6,0,ne,ne,ne,ne]; 
WriteWC4F["IMWCeeSRR","eesrr",\!\(TraditionalForm\`LEFTFindParameter[LeeSRR] // First\),6,1,ne,ne,ne,ne];
WriteWC4F["WCeuSRR","eusrr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LeuSRR] // First\)\),5,0,ne,ne,nu,nu]; 
WriteWC4F["IMWCeuSRR","eusrr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LeuSRR] // First\)\),5,1,ne,ne,nu,nu];
WriteWC4F["WCeuTRR","eutrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LeuTRR] // First\)\)\),5,0,ne,ne,nu,nu]; 
WriteWC4F["IMWCeuTRR","eutrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LeuTRR] // First\)\)\),5,1,ne,ne,nu,nu];
WriteWC4F["WCedSRR","edsrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LedSRR] // First\)\)\),5,0,ne,ne,nd,nd]; 
WriteWC4F["IMWCedSRR","edsrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LedSRR] // First\)\)\),5,1,ne,ne,nd,nd];
WriteWC4F["WCedTRR","edtrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LedTRR] // First\)\)\)\),5,0,ne,ne,nd,nd]; 
WriteWC4F["IMWCedTRR","edtrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LedTRR] // First\)\)\)\),5,1,ne,ne,nd,nd];
WriteWC4F["WCNEDUSRR","nedusrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduSRR] // First\)\)\)\)\),5,0,n\[Nu],ne,nd,nu]; 
WriteWC4F["IMWCNEDUSRR","nedusrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduSRR] // First\)\)\)\)\),5,1,n\[Nu],ne,nd,nu];
WriteWC4F["WCNEDUTRR","nedutrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduTRR] // First\)\)\)\)\),5,0,n\[Nu],ne,nd,nu]; 
WriteWC4F["IMWCNEDUTRR","nedutrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduTRR] // First\)\)\)\)\),5,1,n\[Nu],ne,nd,nu];
WriteWC4F["WCuuS1RR","uus1rr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuuS1RR] // First\)\),6,0,nu,nu,nu,nu]; 
WriteWC4F["IMWCuuS1RR","uus1rr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuuS1RR] // First\)\),6,1,nu,nu,nu,nu];
WriteWC4F["WCuuS8RR","uus8rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuuS8RR] // First\)\)\),6,0,nu,nu,nu,nu]; 
WriteWC4F["IMWCuuS8RR","uus8rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuuS8RR] // First\)\)\),6,1,nu,nu,nu,nu];
WriteWC4F["WCUDS1RR","uds1rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudS1RR] // First\)\)\),5,0,nu,nu,nd,nd]; 
WriteWC4F["IMWCUDS1RR","uds1rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudS1RR] // First\)\)\),5,1,nu,nu,nd,nd];
WriteWC4F["WCUDS8RR","uds8rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudS8RR] // First\)\)\)\),5,0,nu,nu,nd,nd]; 
WriteWC4F["IMWCUDS8RR","uds8rr",\!\(TraditionalForm\`LEFTFindParameter[LudS8RR] // First\),5,1,nu,nu,nd,nd];
WriteWC4F["WCddS1RR","dds1rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LddS1RR] // First\)\)\)\),6,0,nd,nd,nd,nd]; 
WriteWC4F["IMWCddS1RR","dds1rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LddS1RR] // First\)\)\)\),6,1,nd,nd,nd,nd];
WriteWC4F["WCddS8RR","dds8rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LddS8RR] // First\)\)\)\)\),6,0,nd,nd,nd,nd]; 
WriteWC4F["IMWCddS8RR","dds8rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LddS8RR] // First\)\)\)\)\),6,1,nd,nd,nd,nd];
WriteWC4F["WCUDDUS1RR","uddus1rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudduS1RR] // First\)\)\)\)\)\),5,0,nu,nd,nd,nu]; 
WriteWC4F["IMWCUDDUS1RR","uddus1rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudduS1RR] // First\)\)\)\)\)\),5,1,nu,nd,nd,nu];
WriteWC4F["WCUDDUS8RR","uddus8rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudduS8RR] // First\)\)\)\)\)\)\),5,0,nu,nd,nd,nu]; 
WriteWC4F["IMWCUDDUS8RR","uddus8rr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LudduS8RR] // First\)\)\)\)\)\)\),5,1,nu,nd,nd,nu];

(* LR RL *)
WriteWC4F["WCeuSRL","eusrl",\!\(TraditionalForm\`LEFTFindParameter[LeuSRL] // First\),5,0,ne,ne,nu,nu]; 
WriteWC4F["IMWCeuSRL","eusrl",\!\(TraditionalForm\`LEFTFindParameter[LeuSRL] // First\),5,1,ne,ne,nu,nu];
WriteWC4F["WCedSRL","edsrl",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LedSRL] // First\)\),5,0,ne,ne,nd,nd]; 
WriteWC4F["IMWCedSRL","edsrl",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LedSRL] // First\)\),5,1,ne,ne,nd,nd];
WriteWC4F["WCNEDUSRL","nedusrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduSRL] // First\)\)\),5,0,n\[Nu],ne,nd,nu]; 
WriteWC4F["IMWCNEDUSRL","nedusrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduSRL] // First\)\)\),5,1,n\[Nu],ne,nd,nu];

(* \[CapitalDelta]L = 4 *)
WriteWC4F["WCNNSLL","nnsll",LEFTFindParameter[L\[Nu]\[Nu]SLL]//First,12,0,n\[Nu],n\[Nu],n\[Nu],n\[Nu]]; 
WriteWC4F["IMWCNNSLL","nnsll",LEFTFindParameter[L\[Nu]\[Nu]SLL]//First,12,1,n\[Nu],n\[Nu],n\[Nu],n\[Nu]];

 (* \[CapitalDelta]L = 2 *)
WriteWC4F["WCNESLL","nesll",\!\(TraditionalForm\`LEFTFindParameter[L\[Nu]eSLL] // First\),9,0,n\[Nu],n\[Nu],ne,ne]; 
WriteWC4F["IMWCNESLL","nesll",\!\(TraditionalForm\`LEFTFindParameter[L\[Nu]eSLL] // First\),9,1,n\[Nu],n\[Nu],ne,ne];
WriteWC4F["WCNETLL","netll",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eTLL] // First\)\),10,0,n\[Nu],n\[Nu],ne,ne]; 
WriteWC4F["IMWCNETLL","netll",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eTLL] // First\)\),10,1,n\[Nu],n\[Nu],ne,ne];
WriteWC4F["WCNESLR","neslr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eSLR] // First\)\),9,0,n\[Nu],n\[Nu],ne,ne]; 
WriteWC4F["IMWCNESLR","neslr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eSLR] // First\)\),9,1,n\[Nu],n\[Nu],ne,ne];
WriteWC4F["WCNUSLL","nusll",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]uSLL] // First\)\),9,0,n\[Nu],n\[Nu],nu,nu]; 
WriteWC4F["IMWCNUSLL","nusll",LEFTFindParameter[L\[Nu]uSLL]//First,9,1,n\[Nu],n\[Nu],nu,nu];
WriteWC4F["WCNUTLL","nutll",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]uTLL] // First\)\)\),10,0,n\[Nu],n\[Nu],nu,nu]; 
WriteWC4F["IMWCNUTLL","nutll",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]uTLL] // First\)\)\),10,1,n\[Nu],n\[Nu],nu,nu];
WriteWC4F["WCNUSLR","nuslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]uSLR] // First\)\)\),9,0,n\[Nu],n\[Nu],nu,nu]; 
WriteWC4F["IMWCNUSLR","nuslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]uSLR] // First\)\)\),9,1,n\[Nu],n\[Nu],nu,nu];
WriteWC4F["WCNDSLL","ndsll",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]dSLL] // First\)\)\),9,0,n\[Nu],n\[Nu],nd,nd]; 
WriteWC4F["IMWCNDSLL","ndsll",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]dSLL] // First\)\)\),9,1,n\[Nu],n\[Nu],nd,nd];
WriteWC4F["WCNDTLL","ndtll",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]dTLL] // First\)\)\)\),10,0,n\[Nu],n\[Nu],nd,nd]; 
WriteWC4F["IMWCNDTLL","ndtll",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]dTLL] // First\)\)\)\),10,1,n\[Nu],n\[Nu],nd,nd];
WriteWC4F["WCNDSLR","ndslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]dSLR] // First\)\)\)\),9,0,n\[Nu],n\[Nu],nd,nd]; 
WriteWC4F["IMWCNDSLR","ndslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]dSLR] // First\)\)\)\),9,1,n\[Nu],n\[Nu],nd,nd];
WriteWC4F["WCNEDUSLL","nedusll",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduSLL] // First\)\)\)\),5,0,n\[Nu],ne,nd,nu]; 
WriteWC4F["IMWCNEDUSLL","nedusll",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduSLL] // First\)\)\)\),5,1,n\[Nu],ne,nd,nu];
WriteWC4F["WCNEDUTLL","nedutll",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduTLL] // First\)\)\)\)\),5,0,n\[Nu],ne,nd,nu]; 
WriteWC4F["IMWCNEDUTLL","nedutll",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduTLL] // First\)\)\)\)\),5,1,n\[Nu],ne,nd,nu];
WriteWC4F["WCNEDUSLR","neduslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduSLR] // First\)\)\)\)\),5,0,n\[Nu],ne,nd,nu]; 
WriteWC4F["IMWCNEDUSLR","neduslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduSLR] // First\)\)\)\)\),5,1,n\[Nu],ne,nd,nu];
WriteWC4F["WCNEDUVRL","neduvrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduVLR] // First\)\)\)\)\)\),5,0,n\[Nu],ne,nd,nu]; 
WriteWC4F["IMWCNEDUVRL","neduvrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduVLR] // First\)\)\)\)\)\),5,1,n\[Nu],ne,nd,nu];
WriteWC4F["WCNEDUVRR","neduvrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduVRR] // First\)\)\)\)\)\)\),5,0,n\[Nu],ne,nd,nu]; 
WriteWC4F["IMWCNEDUVRR","neduvrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[L\[Nu]eduVRR] // First\)\)\)\)\)\)\),5,1,n\[Nu],ne,nd,nu];

(* \[CapitalDelta]B = \[CapitalDelta]L = 1 *)
WriteWC4F["WCUDDSLL","uddsll",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuddSLL] // First\)\),5,0,nu,nd,nd,n\[Nu]]; 
WriteWC4F["IMWCUDDSLL","uddsll",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuddSLL] // First\)\),5,1,nu,nd,nd,n\[Nu]];
WriteWC4F["WCDUUSLL","duusll",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LduuSLL] // First\)\)\),5,0,nd,nu,nu,ne]; 
WriteWC4F["IMWCDUUSLL","duusll",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LduuSLL] // First\)\)\),5,1,nd,nu,nu,ne];
WriteWC4F["WCuuDSLR","uudslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuudSLR] // First\)\)\)\),10,0,nu,nu,nd,ne]; 
WriteWC4F["IMWCuuDSLR","uudslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuudSLR] // First\)\)\)\),10,1,nu,nu,nd,ne];
WriteWC4F["WCDUUSLR","duuslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LduuSLR] // First\)\)\)\),5,0,nd,nu,nu,ne]; 
WriteWC4F["IMWCDUUSLR","duuslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LduuSLR] // First\)\)\)\),5,1,nd,nu,nu,ne];
WriteWC4F["WCuuDSRL","uudsrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuudSRL] // First\)\)\)\)\),10,0,nu,nu,nd,ne]; 
WriteWC4F["IMWCuuDSRL","uudsrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuudSRL] // First\)\)\)\)\),10,1,nu,nu,nd,ne];
WriteWC4F["WCDUUSRL","duusrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LduuSRL] // First\)\)\)\)\),5,0,nd,nu,nu,ne]; 
WriteWC4F["IMWCDUUSRL","duusrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LduuSRL] // First\)\)\)\)\),5,1,nd,nu,nu,ne];
WriteWC4F["WCDUDSRL","dudsrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LdudSRL] // First\)\)\)\)\)\),5,0,nd,nu,nd,n\[Nu]]; 
WriteWC4F["IMWCDUDSRL","dudsrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LdudSRL] // First\)\)\)\)\)\),5,1,nd,nu,nd,n\[Nu]];
WriteWC4F["WCddUSRL","ddusrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LdduSRL] // First\)\)\)\)\)\),10,0,nd,nd,nu,n\[Nu]]; 
WriteWC4F["IMWCddUSRL","ddusrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LdduSRL] // First\)\)\)\)\)\),10,1,nd,nd,nu,n\[Nu]];
WriteWC4F["WCDUUSRR","duusrr",LEFTFindParameter[LduuSRR]//First,5,0,nd,nu,nu,ne]; 
WriteWC4F["IMWCDUUSRR","duusrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LduuSRR] // First\)\)\)\)\)\)\),5,1,nd,nu,nu,ne];

(* \[CapitalDelta]B = -\[CapitalDelta]L = 1 *)
WriteWC4F["WCDDDSLL","dddsll",\!\(TraditionalForm\`LEFTFindParameter[LdddSLL] // First\),13,0,nd,nd,ne,nd]; 
WriteWC4F["IMWCDDDSLL","dddsll",\!\(TraditionalForm\`LEFTFindParameter[LdddSLL] // First\),13,1,nd,nd,ne,nd];
WriteWC4F["WCUDDSLR","uddslr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuddSLR] // First\)\),5,0,nu,nd,n\[Nu],nd]; 
WriteWC4F["IMWCUDDSLR","uddslr",\!\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuddSLR] // First\)\),5,1,nu,nd,n\[Nu],nd];
WriteWC4F["WCddUSLR","dduslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LdduSLR] // First\)\)\),10,0,nd,nd,n\[Nu],nu]; 
WriteWC4F["IMWCddUSLR","dduslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LdduSLR] // First\)\)\),10,1,nd,nd,n\[Nu],nu];
WriteWC4F["WCddDSLR","dddslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LdddSLR] // First\)\)\)\),10,0,nd,nd,ne,nd]; 
WriteWC4F["IMWCddDSLR","dddslr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LdddSLR] // First\)\)\)\),10,1,nd,nd,ne,nd];
WriteWC4F["WCddDSRL","dddsrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LdddSRL] // First\)\)\)\)\),10,0,nd,nd,ne,nd]; 
WriteWC4F["IMWCddDSRL","dddsrl",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LdddSRL] // First\)\)\)\)\),10,1,nd,nd,ne,nd];
WriteWC4F["WCUDDSRR","uddsrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuddSRR] // First\)\)\)\)\)\),5,0,nu,nd,n\[Nu],nd]; 
WriteWC4F["IMWCUDDSRR","uddsrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LuddSRR] // First\)\)\)\)\)\),5,1,nu,nd,n\[Nu],nd];
WriteWC4F["WCDDDSRR","dddsrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LdddSRR] // First\)\)\)\)\)\)\),13,0,nd,nd,ne,nd]; 
WriteWC4F["IMWCDDDSRR","dddsrr",\!\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`\(TraditionalForm\`LEFTFindParameter[LdddSRR] // First\)\)\)\)\)\)\),13,1,nd,nd,ne,nd];

];


(* ::Input::Initialization:: *)
WriteWCs[EFT_]:=Block[{},

If[EFT=="SMEFT",
Write0FSMEFT;
Write2FSMEFT;
Write4FSMEFT;
Writedim5;
];

If[EFT=="LEFT",
Write0FLEFT;
Write2FLEFT;
Write4FLEFT;
];

];


WriteWCsSMEFTJSON[scale_]:=Block[{last},

last=SMEFTFindParameter[\[Theta]s]//First;

Write[outfile,"{"];
Write[outfile,"  \"eft\": \"SMEFT\","];
Write[outfile,"  \"basis\": \"Warsaw\","];
Write[outfile,"  \"scale\": ",outR[scale],","];
Write[outfile,"  \"values\": {"];
Do[
If[Element[dataOutput[[i+last]],Reals],
If[i<Length[SMEFTWCsWCXF],
Write[outfile,"    \""<>ToString[SMEFTWCsWCXF[[i]]]<>"\": ",outR[dataOutput[[i+last]]],","];
,
Write[outfile,"    \""<>ToString[SMEFTWCsWCXF[[i]]]<>"\": ",outR[dataOutput[[i+last]]]];
];
,
Write[outfile,"    \""<>ToString[SMEFTWCsWCXF[[i]]]<>"\": {"];
Write[outfile,"      \"Re\": ",outR[Re[dataOutput[[i+last]]]],","];
Write[outfile,"      \"Im\": ",outR[Im[dataOutput[[i+last]]]]];
If[i<Length[SMEFTWCsWCXF],Write[outfile,"    },"];,Write[outfile,"    }"];];
];
,{i,1,Length[SMEFTWCsWCXF]}];
Write[outfile,"  }"];
Write[outfile,"}"];

];


WriteWCsSMEFTYAML[scale_]:=Block[{last},

last=SMEFTFindParameter[\[Theta]s]//First;

Write[outfile,"eft: SMEFT"];
Write[outfile,"basis: Warsaw"];
Write[outfile,"scale: ",outR[scale]];
Write[outfile,"values:"];
Do[
If[Element[dataOutput[[i+last]],Reals],
Write[outfile,"  "<>ToString[SMEFTWCsWCXF[[i]]]<>": ",outR[dataOutput[[i+last]]]];
,
Write[outfile,"  "<>ToString[SMEFTWCsWCXF[[i]]]<>":"];
Write[outfile,"    Re: ",outR[Re[dataOutput[[i+last]]]]];
Write[outfile,"    Im: ",outR[Im[dataOutput[[i+last]]]]];
];
,{i,1,Length[SMEFTWCsWCXF]}];

];


WriteWCsLEFTJSON[scale_]:=Block[{last},

last=LEFTFindParameter[Md[3,3]]//First;

Write[outfile,"{"];
Write[outfile,"  \"eft\": \"LEFT\","];
Write[outfile,"  \"basis\": \"San Diego\","];
Write[outfile,"  \"scale\": ",outR[scale],","];
Write[outfile,"  \"values\": {"];
Do[
If[Element[dataOutput[[i+last]],Reals],
If[i<Length[LEFTWCsWCXF],
Write[outfile,"    \""<>ToString[LEFTWCsWCXF[[i]]]<>"\": ",outR[dataOutput[[i+last]]],","];
,
Write[outfile,"    \""<>ToString[LEFTWCsWCXF[[i]]]<>"\": ",outR[dataOutput[[i+last]]]];
];
,
Write[outfile,"    \""<>ToString[LEFTWCsWCXF[[i]]]<>"\": {"];
Write[outfile,"      \"Re\": ",outR[Re[dataOutput[[i+last]]]],","];
Write[outfile,"      \"Im\": ",outR[Im[dataOutput[[i+last]]]]];
If[i<Length[LEFTWCsWCXF],Write[outfile,"    },"];,Write[outfile,"    }"];];
];
,{i,1,Length[LEFTWCsWCXF]}];
Write[outfile,"  }"];
Write[outfile,"}"];

];


WriteWCsLEFTYAML[scale_]:=Block[{last},

last=LEFTFindParameter[Md[3,3]]//First;

Write[outfile,"eft: LEFT"];
Write[outfile,"basis: San Diego"];
Write[outfile,"scale: ",outR[scale]];
Write[outfile,"values:"];
Do[
If[Element[dataOutput[[i+last]],Reals],
Write[outfile,"  "<>ToString[LEFTWCsWCXF[[i]]]<>": ",outR[dataOutput[[i+last]]]];
,
Write[outfile,"  "<>ToString[LEFTWCsWCXF[[i]]]<>":"];
Write[outfile,"    Re: ",outR[Re[dataOutput[[i+last]]]]];
Write[outfile,"    Im: ",outR[Im[dataOutput[[i+last]]]]];
];
,{i,1,Length[LEFTWCsWCXF]}];

];


(* ::Input::Initialization:: *)
(* Routine used in WriteInputFileSLHA and necessary for WCXF to SLHA format translation *)
WriteWCsFile[outname_,dataOutput_,EFT_]:=Block[{outfile},

(* Open file *)
outfile=OpenWrite[outname,FormatType->StandardForm];

(* Write output blocks *)
WriteWCs[EFT];

(* Close file *)
Close[outfile];
];


(* ::Input::Initialization:: *)
WriteSMEFTOutputFile[outname_,dataOutput_]:=Block[{outfile},

(* Open file *)
outfile=OpenWrite[outname,FormatType->StandardForm];

(* Write output blocks *)
WriteScales["SMEFTrunner"];
WriteSM;
WriteWCs["SMEFT"];
WriteOptions;

(* Close file *)
Close[outfile];
];


(* ::Input::Initialization:: *)
WriteLEFTOutputFile[outname_,dataOutput_,option_]:=Block[{outfile},

(* Open file *)
outfile=OpenWrite[outname,FormatType->StandardForm];

(* Write output blocks *)
If[option==1,WriteScales["EWmatcher"];];
If[option==2,WriteScales["LEFTrunner"];];
WriteQCDQED;
WriteWCs["LEFT"];
WriteOptions;

(* Close file *)
Close[outfile];
];


(* ::Input::Initialization:: *)
WriteWCXFOutputFile[outname_,format_,EFT_,scale_]:=Block[{outfile},

(* Open file *)
outfile=OpenWrite[outname,FormatType->StandardForm];

If[format=="JSON"&&EFT=="SMEFT",WriteWCsSMEFTJSON[scale];];
If[format=="JSON"&&EFT=="LEFT",WriteWCsLEFTJSON[scale];];
If[format=="YAML"&&EFT=="SMEFT",WriteWCsSMEFTYAML[scale];];
If[format=="YAML"&&EFT=="LEFT",WriteWCsLEFTYAML[scale];];

(* Close file *)
Close[outfile];
];


(* Printing function *)
MyPrint[string_]:=Block[{},
If[PrintMessages,Print[string]];
];


TurnOnMessages:=Block[{},
PrintMessages=True;
];


TurnOffMessages:=Block[{},
PrintMessages=False;
];


(* ::Input::Initialization:: *)
SMEFTrunnerExport:=Block[{},

Which[
Length[{##}]==0,
MyPrint["Exporting SMEFTrunner results"];
dataOutput=Chop[SMEFTrun/@ParametersSMEFT/.\[Mu]->EWSCALE,$MachineEpsilon];
outname="Output_SMEFTrunner.dat";
WriteSMEFTOutputFile[outname,dataOutput];
,
Length[{##}]==2,
MyPrint["Exporting SMEFTrunner results"];
If[{##}[[1]]=="SLHA",
dataOutput=Chop[SMEFTrun/@ParametersSMEFT/.\[Mu]->EWSCALE,$MachineEpsilon];
outname={##}[[2]]<>".dat";
WriteSMEFTOutputFile[outname,dataOutput];
,
dataOutput=ComputeSMEFTrunnerInd;
If[{##}[[1]]=="JSON",outname={##}[[2]]<>".json";];
If[{##}[[1]]=="YAML",outname={##}[[2]]<>".yaml";];
WriteWCXFOutputFile[outname,{##}[[1]],"SMEFT",EWSCALE];
];
,
Length[{##}]!=0&&Length[{##}]!=2,
Message[SMEFTrunnerExport::WrongInput]
];

]&;


(* ::Input::Initialization:: *)
EWmatcherExport:=Block[{},

Which[
Length[{##}]==0,
MyPrint["Exporting EWmatcher results"];
dataOutput=Chop[ParametersLEFT/.Match,$MachineEpsilon];
outname="Output_EWmatcher.dat";
WriteLEFTOutputFile[outname,dataOutput,1];
,
Length[{##}]==2,
MyPrint["Exporting EWmatcher results"];
If[{##}[[1]]=="SLHA",
dataOutput=Chop[ParametersLEFT/.Match,$MachineEpsilon];
outname={##}[[2]]<>".dat";
WriteLEFTOutputFile[outname,dataOutput,1];
,
dataOutput=ComputeEWmatcherInd;
If[{##}[[1]]=="JSON",outname={##}[[2]]<>".json";];
If[{##}[[1]]=="YAML",outname={##}[[2]]<>".yaml";];
WriteWCXFOutputFile[outname,{##}[[1]],"LEFT",EWSCALE];
];
,
Length[{##}]!=0&&Length[{##}]!=2,
Message[EWmatcherExport::WrongInput]
];

]&;


(* ::Input::Initialization:: *)
LEFTrunnerExport:=Block[{},

Which[
Length[{##}]==0,
MyPrint["Exporting LEFTrunner results"];
dataOutput=Chop[LEFTrun/@ParametersLEFT/.\[Mu]->LOWSCALE,$MachineEpsilon];
outname="Output_LEFTrunner.dat";
WriteLEFTOutputFile[outname,dataOutput,2];
,
Length[{##}]==2,
MyPrint["Exporting LEFTrunner results"];
If[{##}[[1]]=="SLHA",
dataOutput=Chop[LEFTrun/@ParametersLEFT/.\[Mu]->LOWSCALE,$MachineEpsilon];
outname={##}[[2]]<>".dat";
WriteLEFTOutputFile[outname,dataOutput,2];
,
dataOutput=ComputeLEFTrunnerInd;
If[{##}[[1]]=="JSON",outname={##}[[2]]<>".json";];
If[{##}[[1]]=="YAML",outname={##}[[2]]<>".yaml";];
WriteWCXFOutputFile[outname,{##}[[1]],"LEFT",LOWSCALE];
];
,
Length[{##}]!=0&&Length[{##}]!=2,
Message[LEFTrunnerExport::WrongInput]
];

]&;


ComputeSMEFTrunnerInd:=Block[{},
If[!ValueQ[ParametersSMEFTInd],ParametersSMEFTInd=ToIndependentSingle/@ParametersSMEFT;];
Return[Chop[SMEFTrun/@ParametersSMEFTInd/.\[Mu]->EWSCALE,$MachineEpsilon]];
];


ComputeEWmatcherInd:=Block[{},
If[!ValueQ[ParametersLEFTInd],ParametersLEFTInd=ToIndependentSingle/@ParametersLEFT;];
Return[Chop[ParametersLEFTInd/.Match,$MachineEpsilon]];
];


ComputeLEFTrunnerInd:=Block[{},
If[!ValueQ[ParametersLEFTInd],ParametersLEFTInd=ToIndependentSingle/@ParametersLEFT;];
Return[Chop[LEFTrun/@ParametersLEFTInd/.\[Mu]->LOWSCALE,$MachineEpsilon]];
];
